Repository thanos-io/thanos, pull requests merged in 2018-10, with the labels that each got.

#563 Proxy Store should not lock when all clients error.
  CHANGELOG.md
  pkg/store/proxy.go
  pkg/store/proxy_test.go
Labels: bug

#571 Fixed clean up old compact chunks when compact starts
  cmd/thanos/compact.go
  pkg/compact/compact.go
Labels: bugfix, difficulty: medium, help wanted

#570 tests: add ctx to the minio spinup command
  test/e2e/spinup_test.go
Labels: bugfix

#546 [file-sd-part-1] Added file sd to query
  Gopkg.lock
  benchmark/cmd/thanosbench/resources.go
  cmd/thanos/query.go
  cmd/thanos/rule.go
  docs/components/query.md
  docs/components/rule.md
  pkg/discovery/cache/cache.go
  pkg/query/api/v1.go
  pkg/store/proxy_test.go
  test/e2e/query_test.go
  test/e2e/rule_test.go
  test/e2e/spinup_test.go
Labels: difficulty: medium, feature request / improvement, help wanted

#581 do not clean root, instead explicitly clean downsample dir
  cmd/thanos/compact.go
Labels: bug, bugfix, difficulty: easy, help wanted

#574 Add /-/healthy endpoint to Querier
  CHANGELOG.md
  cmd/thanos/query.go
  kube/manifests/thanos-query.yaml
Labels: difficulty: easy, feature request / improvement, help wanted

#583 Changed the file SD flags names
  cmd/thanos/query.go
  cmd/thanos/rule.go
  docs/components/query.md
  docs/components/rule.md
  test/e2e/spinup_test.go
Labels: difficulty: easy

#404 Add proposal for store instance high availability
  docs/proposals/201807_store_instance_high_availability.md
Labels: feature request / improvement, proposal
