Repository thanos-io/thanos, pull requests merged in 2019-02, with the labels that each got.

#724 [sync part1] bucket: Improved bucket flag handling when no store is specifed; simplified factory and bucket commands code.
  CHANGELOG.md
  cmd/thanos/bucket.go
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/flags.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  docs/components/bucket.md
  pkg/objstore/client/factory.go
  pkg/objstore/client/factory_test.go
  scripts/genflagdocs.sh
Labels: feature request / improvement, priority: P0

#729 [sync part2] Moved client prometheus code to separate promclient package.
  Gopkg.lock
  cmd/thanos/rule.go
  cmd/thanos/rule_test.go
  cmd/thanos/sidecar.go
  cmd/thanos/sidecar_test.go
  pkg/extprom/extprom.go
  pkg/promclient/promclient.go
  pkg/promclient/promclient_e2e_test.go
  pkg/testutil/prometheus.go
  test/e2e/query_test.go
  test/e2e/rule_test.go
  test/e2e/store_gateway_test.go
Labels: feature request / improvement, priority: P0

#730 [sync part3] promclient: Added method for Prometheus snapshot.
  CHANGELOG.md
  Makefile
  pkg/promclient/promclient.go
  pkg/promclient/promclient_e2e_test.go
  pkg/store/bucket_e2e_test.go
  pkg/testutil/prometheus.go
Labels: feature request / improvement, priority: P0

#750 storeApi: add component information to gRPC's Info response (resolves #739)
  cmd/thanos/downsample.go
  cmd/thanos/query.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  pkg/compact/downsample/downsample_test.go
  pkg/component/component.go
  pkg/query/storeset.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/rpc.pb.go
  pkg/store/storepb/rpc.proto
  pkg/store/tsdb.go
  pkg/store/tsdb_test.go
  pkg/ui/bindata.go
  pkg/ui/query.go
  pkg/ui/templates/stores.html
Labels: priority: P0

#529 compact: Improved memory usage while downsampling
  .errcheck_excludes.txt
  cmd/thanos/downsample.go
  pkg/block/metadata/meta.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compact/downsample/streamed_block_writer.go
Labels: difficulty: hard, feature request / improvement, priority: P0

#731 Added shipper capability to sync compacted blocks once.
  Gopkg.lock
  cmd/thanos/bucket.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  pkg/promclient/promclient.go
  pkg/shipper/shipper.go
  pkg/shipper/shipper_e2e_test.go
  pkg/testutil/prometheus.go
Labels: feature request / improvement, priority: P0

#826 Updating Release documentation.
  docs/release_process.md
Labels: docs

#853 updating version and changelog for v0.3.1
  CHANGELOG.md
  VERSION
Labels: docs
