Repository thanos-io/thanos, pull requests merged in 2019-10, with the labels that each got.

#1591 Adds UBIO to the adopters
  website/data/adopters.yml
  website/static/logos/ubio.png
Labels: website/docs

#1582 fix rule: fixed issue with alertmanager URL containing +
  CHANGELOG.md
  cmd/thanos/rule.go
  cmd/thanos/rule_test.go
Labels: component: rule

#1602 feat: bump version of go-grpc-prometheus@v1.2.1-0.20191002090509-6af2…
  go.mod
  go.sum
Labels: dependencies

#1603 chore: updated github PR template with changelog entry format
  .github/PULL_REQUEST_TEMPLATE.md
Labels: website/docs

#1658 Upgraded minio-go dep.
  go.mod
  go.sum
Labels: dependencies
