Repository thanos-io/thanos, pull requests merged in 2021-12, with the labels that each got.

#4938 resolver: Improve logs when A record does not resolve from SRV record set
  pkg/discovery/dns/resolver.go
Labels: size/XS

#4922 Sidecar: Use flag to ignore overlap check, add test for it
  pkg/shipper/shipper.go
  pkg/shipper/shipper_e2e_test.go
Labels: size/L

#4909 Compactor support time filter (#4884)
  CHANGELOG.md
  cmd/thanos/compact.go
  docs/components/compact.md
Labels: size/S

#1906 support build docker images for arm64 arch
  .circleci/config.yml
  .dockerignore
  Dockerfile.multi-arch
  Makefile
Labels: size/M

#4942 Tracing: add `traceid_128bit` support for jaeger
  CHANGELOG.md
  docs/tracing.md
  pkg/tracing/jaeger/config_yaml.go
Labels: size/XS

#4950 Updated busybox image.
  Makefile
Labels: size/XS

#4939 sidecar: not ready when Prometheus is unavailable
  CHANGELOG.md
  cmd/thanos/sidecar.go
  test/e2e/query_test.go
Labels: size/M

#4957 *: Update BusyBox image sha
  Makefile
Labels: size/XS

#4958 *: Correct BusyBox SHA
  Makefile
Labels: size/XS

#4879 bucket verify: fix to parse all blocks
  CHANGELOG.md
  pkg/verifier/index_issue.go
Labels: size/L

#4945 Upgrade golang to 1.17
  .bingo/Variables.mk
  .bingo/faillint.mod
  .bingo/prometheus.mod
  .bingo/variables.env
  .circleci/config.yml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .github/workflows/mixin.yaml
  .go-version
  .promu.yml
  Dockerfile.multi-stage
  go.mod
  go.sum
Labels: size/M

#4931 docs: add changelog about redis cache
  CHANGELOG.md
  pkg/cacheutil/redis_client.go
  pkg/queryfrontend/cache.go
  pkg/store/cache/caching_bucket_factory.go
  pkg/store/cache/memcached.go
Labels: size/XS

#4917 Implement query pushdown for a subset of aggregations
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
  pkg/api/query/v1.go
  pkg/query/querier.go
  pkg/query/querier_test.go
  pkg/query/query_test.go
  pkg/store/prometheus.go
  pkg/store/proxy.go
  pkg/store/storepb/custom.go
  pkg/store/storepb/custom_test.go
  pkg/store/storepb/prompb/samples.go
  pkg/store/storepb/query_hints.go
  pkg/store/storepb/rpc.pb.go
  pkg/store/storepb/rpc.proto
  test/e2e/query_test.go
Labels: size/XXL

#4962 downsample: fix deadlock if error occurs
  CHANGELOG.md
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
Labels: size/L

#4946 Add custom certificate CA support for s3
  CHANGELOG.md
  docs/storage.md
  pkg/objstore/s3/s3.go
  pkg/objstore/s3/s3_test.go
Labels: size/L

#4969 Cut 0.23.2-rc.1
  CHANGELOG.md
  Makefile
  VERSION
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
Labels: size/L

#4973 Release 0.24.0-rc.2
  CHANGELOG.md
  Makefile
  VERSION
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
Labels: size/L

#4970 Exclude blocks marked for deletion
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
Labels: size/S

#4974 Add custom CA support for azure
  CHANGELOG.md
  docs/storage.md
  pkg/objstore/azure/azure.go
  pkg/objstore/azure/azure_test.go
  pkg/objstore/azure/helpers.go
  pkg/objstore/s3/s3.go
  pkg/objstore/tlsconfig.go
Labels: size/L

#4982 *: release 0.23.2
  CHANGELOG.md
  VERSION
Labels: size/XS

#4984 *: cut v0.24.0
  CHANGELOG.md
  VERSION
  docs/release-process.md
  tutorials/katacoda/thanos/1-globalview/courseBase.sh
  tutorials/katacoda/thanos/1-globalview/step2.md
  tutorials/katacoda/thanos/1-globalview/step3.md
  tutorials/katacoda/thanos/2-lts/courseBase.sh
  tutorials/katacoda/thanos/2-lts/step1.md
  tutorials/katacoda/thanos/2-lts/step2.md
  tutorials/katacoda/thanos/2-lts/step3.md
  tutorials/katacoda/thanos/2-lts/step4.md
  tutorials/katacoda/thanos/6-query-caching/courseBase.sh
  tutorials/katacoda/thanos/6-query-caching/step1.md
  tutorials/katacoda/thanos/6-query-caching/step2.md
  tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
  tutorials/katacoda/thanos/7-multi-tenancy/step1.md
  tutorials/katacoda/thanos/7-multi-tenancy/step2.md
  tutorials/katacoda/thanos/x-playground/courseBase.sh
  tutorials/katacoda/thanos/x-playground/step1.md
  tutorials/katacoda/thanos/x-playground/step2.md
Labels: size/M

#4985 store: fix label extending
  pkg/store/prometheus.go
Labels: size/S

#4932 New metric for measuring query duration proposal
  docs/proposals-accepted/202108-more-granular-query-performance-metrics.md
Labels: size/L

#5001 compactor: make time filter take first
  cmd/thanos/compact.go
Labels: component: compact, size/XS

#5000 Fix CI broken `make check-docs`
  Makefile
  docs/proposals-accepted/202108-more-granular-query-performance-metrics.md
Labels: component: website/docs, size/M

#4965 Adds GitHub flow to automate busybox container SHAs
  .busybox-versions
  .github/workflows/container-version.yaml
  Makefile
  scripts/busybox-updater.sh
Labels: size/M

#5005 Increase indexheader_lazy_load_duration_seconds buckets
  pkg/block/indexheader/lazy_binary_reader.go
Labels: size/XS

#4999 objectstore/cos: add `endpoint` field for config vpc internal endpoint
  CHANGELOG.md
  docs/storage.md
  pkg/objstore/cos/cos.go
  pkg/objstore/cos/cos_test.go
Labels: size/L

#5015 [Website] fixed overflow company images and hero section logo
  website/layouts/index.html
  website/static/main.css
Labels: size/S

#5017 Merge release 0.23 to main
  CHANGELOG.md
Labels: size/S
