Repository thanos-io/thanos, pull requests merged in 2022-12, with the labels that each got.

#5940 objstore: Update to latest
  CHANGELOG.md
  docs/storage.md
  go.mod
  go.sum
Labels: size/S

#5950 Added Filip and Saswata to maintainers list after internal vote.
  MAINTAINERS.md
Labels: size/M

#5953 add kakaopay as adoptors
  website/data/adopters.yml
  website/static/logos/kakaopay.png
Labels: size/XS

#5948 Fix values for the chunks_fetched_duration metric
  pkg/store/bucket.go
Labels: size/XS

#5955 Added bwplotka as community meetings and release shepherd for December.
  docs/contributing/community.md
  docs/release-process.md
Labels: size/S

#5958 docs: fix some typos
  docs/components/store.md
  docs/proposals-accepted/202012-receive-split.md
  docs/proposals-accepted/202106-automated-per-endpoint-mTLS.md
Labels: size/XS

#5927 *: Document development in WSL2
  CONTRIBUTING.md
Labels: size/XS

#5966 Fix mint and maxt for api/v1/series call
  CHANGELOG.md
  pkg/query/querier.go
Labels: size/XS

#5967 fixed blog list view in website
  website/hugo.yaml
  website/layouts/blog/list.html
Labels: size/XS

#5910 Fix ketama quorum
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/writer.go
Labels: size/XXL

#5973 cortex/transport: print grafana data if exists
  internal/cortex/frontend/transport/handler.go
Labels: size/S

#5972 query/endpointset: fix some races
  pkg/query/endpointset.go
Labels: size/XS

#5945 Added tools bucket marker for no-downsample.json
  CHANGELOG.md
  cmd/thanos/downsample.go
  cmd/thanos/tools_bucket.go
  pkg/block/block.go
  pkg/block/block_test.go
  pkg/block/fetcher.go
  pkg/block/metadata/markers.go
  pkg/compact/downsample/downsample.go
Labels: size/L

#5981 Changing store to match debug level
  pkg/store/proxy.go
Labels: size/XS

#5979 Github link to v0.25.2
  CHANGELOG.md
Labels: size/XS

#5989 mixin(Receive): Fix series/samples written rate
  examples/dashboards/receive.json
  mixin/dashboards/receive.libsonnet
Labels: size/XS

#5593 cache: switch to Rueidis client for Redis
  CHANGELOG.md
  docs/components/query-frontend.md
  docs/components/store.md
  docs/img/rueidis-client-side.png
  go.mod
  go.sum
  pkg/cacheutil/redis_client.go
  pkg/cacheutil/redis_client_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/store_gateway_test.go
Labels: size/L

#5977 tools: Added remove flag on bucket mark command to remove deletion, no-downsample or no-compact markers on the block
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
  pkg/block/block.go
  pkg/block/block_test.go
Labels: size/L

#5991 Changelog split for next release.
  CHANGELOG.md
  VERSION
Labels: size/XS

#5923 compact: remove cancel on SyncMetas errors
  cmd/thanos/compact.go
Labels: size/XS

#5992 Cut v0.30.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/M

#5997 Sets the default sd-dns-resolver for ruler miekgdns
  CHANGELOG.md
  cmd/thanos/config.go
Labels: size/XS

#5998 cacheutil: upgrade rueidis to 0.0.90 to reduce allocations
  go.mod
  go.sum
Labels: size/XS

#5999 Update alertmanager to latest release v0.25.0
  CHANGELOG.md
  go.mod
  go.sum
  pkg/httpconfig/http.go
Labels: size/L
