Repository thanos-io/thanos, pull requests merged in 2022-02, with the labels that each got.

#5103 Fix race condition in filesystem bucket client Delete()
  pkg/objstore/filesystem/filesystem.go
  pkg/objstore/filesystem/filesystem_test.go
Labels: size/M

#5114 Use time.RFC3339 in bucket inspect command for consistency
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
Labels: size/S

#5116 docs: add groupcache docs
  docs/components/store.md
  docs/img/groupcache.png
  pkg/cache/groupcache.go
Labels: size/M

#5111 Add matcher support to Query Rules endpoint
  CHANGELOG.md
  pkg/api/query/v1.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/rules/rulespb/rpc.pb.go
  pkg/rules/rulespb/rpc.proto
Labels: size/XL

#4987 Fix pushdown with deduplication on
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/dedup/pushdown_iter.go
  pkg/query/querier.go
  pkg/query/querier_test.go
  pkg/store/prometheus.go
  test/e2e/query_test.go
Labels: size/XL

#5122 Fix typo in step2.md_2-lts_katacoda-tutorial
  tutorials/katacoda/thanos/2-lts/step2.md
Labels: size/XS

#5120 bump codemirror-promql to v0,19,0
  pkg/ui/react-app/package-lock.json
  pkg/ui/react-app/package.json
Labels: size/XS

#5113 docs: Added Matej to Triage Team and Wiard to Core Maintainers.
  MAINTAINERS.md
Labels: size/M

#5129 Docs: Add mixin design doc again
  mixin/README.md
Labels: size/XS

#5132 fix(tutorials): fix typos in katacoda/thanos/1-globalview
  tutorials/katacoda/thanos/1-globalview/step3.md
Labels: size/XS

#4667 Add a pure aws-sdk-go auth
  CHANGELOG.md
  docs/storage.md
  go.mod
  go.sum
  pkg/objstore/s3/s3.go
  pkg/objstore/s3/s3_aws_sdk_auth.go
Labels: size/M

#5117 feat bucket replicate: added flag to ignore blocks marked for deletion
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
  pkg/replicate/replicator.go
  pkg/replicate/scheme.go
  pkg/replicate/scheme_test.go
Labels: size/M

#5138 cache: fix quickstart script, improve checking
  pkg/cache/groupcache.go
  scripts/quickstart.sh
Labels: size/XS

#4934 Document request logging configuration
  docs/components/query-frontend.md
  docs/components/query.md
  docs/components/receive.md
  docs/components/rule.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/logging.md
  pkg/extkingpin/flags.go
Labels: size/L

#5139 objectstore/cos: support multi-part upload (#5137)
  CHANGELOG.md
  pkg/objstore/cos/cos.go
Labels: size/M

#5142 sidecar: fix for --min-time with pushdown
  pkg/store/prometheus.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/info_api_test.go
  test/e2e/metadata_api_test.go
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
  test/e2e/rules_api_test.go
  test/e2e/targets_api_test.go
Labels: size/L

#5143 Add Kollective as Adopter
  website/data/adopters.yml
  website/static/logos/kollective.png
Labels: size/XS

#5148 Receive: Added tenant ID tag for span
  CHANGELOG.md
  pkg/store/multitsdb.go
Labels: size/XS

#5102 Fix: Filter block rows in bucket UI according to searched block ID
  CHANGELOG.md
  pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
  pkg/ui/react-app/src/thanos/pages/blocks/helpers.test.tsx
  pkg/ui/react-app/src/thanos/pages/blocks/helpers.ts
Labels: size/L

#5162 fix tools bucket replicate: fix ignoring of deleted blocks
  CHANGELOG.md
  pkg/replicate/replicator.go
  pkg/replicate/scheme.go
  pkg/replicate/scheme_test.go
Labels: size/M

#5152 Add guide for troubleshooting compaction backlog
  CHANGELOG.md
  docs/img/compaction_progress_metrics.png
  docs/operating/compactor-backlog.md
Labels: size/M

#5174 shipper: better error message when thanos.shipper.json invalid
  pkg/shipper/shipper.go
  pkg/shipper/shipper_test.go
Labels: size/M

#5179 Cut version 0.25
  CHANGELOG.md
  VERSION
Labels: size/S

#5167 Docs: Tidy up docs-related make targets
  Makefile
Labels: size/S

#5185 store: fix division by zero with query-pushdown
  pkg/store/prometheus.go
Labels: size/XS

#5166 COS: Fix tools replicate
  pkg/objstore/cos/cos.go
  pkg/objstore/objstore.go
  pkg/objstore/objstore_test.go
Labels: size/M

#5184 *: Cut 0.25.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/M
