Repository thanos-io/thanos, pull requests merged in 2022-04, with the labels that each got.

#5264 webiste: Ukraine banner update
  website/layouts/index.html
Labels: size/XS

#5267 Add SumUp logo to adopters
  website/data/adopters.yml
  website/static/logos/sumup.png
Labels: size/XS

#5269 receive: Better error handling of remote write requests.
  pkg/receive/handler.go
  pkg/receive/writer.go
Labels: size/M

#5271 Fix miekgdns resolver to work with CNAME records too
  pkg/discovery/dns/miekgdns/resolver.go
Labels: size/S

#5285 docs: fix URLs preventing generation and unblock CI
  .mdox.validate.yaml
  MAINTAINERS.md
  docs/release-process.md
  tutorials/katacoda/thanos/3-receiver/intro.md
Labels: size/M

#5289 Add Vestiaire Collective to adopters
  website/data/adopters.yml
  website/static/logos/vestiairecollective.png
Labels: size/XS

#5291 Implement Query API discovery
  cmd/thanos/query.go
  pkg/info/info.go
  pkg/info/infopb/rpc.pb.go
  pkg/info/infopb/rpc.proto
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
Labels: size/L

#5290 Added support for ppc64le
  .promu.yml
  CHANGELOG.md
  Makefile
  scripts/installprotoc.sh
Labels: size/S

#5260 Added target API tests (+goleak).
  go.mod
  pkg/targets/prometheus_test.go
  pkg/targets/proxy_test.go
  pkg/targets/targets.go
Labels: size/L

#5297 Revert "Added target API tests (+goleak)."
  go.mod
  pkg/targets/prometheus_test.go
  pkg/targets/proxy_test.go
  pkg/targets/targets.go
Labels: size/L

#5281 Use correct filesystem/network path separators when uploading blocks
  CHANGELOG.md
  pkg/block/block.go
  pkg/objstore/objstore.go
Labels: size/S

#5300 query-frontend: Don't cache request with dedup=false
  CHANGELOG.md
  docs/components/query-frontend.md
  pkg/queryfrontend/labels_codec_test.go
  pkg/queryfrontend/queryrange_codec.go
  pkg/queryfrontend/request.go
  pkg/queryfrontend/roundtrip.go
  pkg/queryfrontend/roundtrip_test.go
  test/e2e/query_frontend_test.go
Labels: size/L

#5306 mixin: Fix typo in ThanosCompactHalted alert
  examples/alerts/alerts.md
  examples/alerts/alerts.yaml
  mixin/alerts/compact.libsonnet
  mixin/runbook.md
Labels: size/XS

#5301 Avoid starting goroutines for memcached batch requests before gate
  pkg/cacheutil/cacheutil.go
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/memcached_client_test.go
  pkg/cacheutil/redis_client.go
Labels: size/L

#5313 Reviewed and updated Changelog for 0.26-rc0
  CHANGELOG.md
Labels: size/S

#5317 Cut 0.26.0-rc.0 set version correctly
  VERSION
Labels: size/XS

#5314 Ensure memcached batched requests handle context cancelation
  pkg/cacheutil/cacheutil_test.go
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/memcached_client_test.go
Labels: size/L
