Repository thanos-io/thanos, pull requests merged in 2022-10, with the labels that each got.

#5746 store: fix nil panic in proxy heap
  pkg/store/proxy_heap.go
  pkg/store/proxy_test.go
  test/e2e/query_test.go
Labels: size/M

#5747 *: Stop failing fast on e2e tests
  .github/workflows/go.yaml
Labels: size/XS

#5552 Receiver: Use proxy store for MultiTSDB
  cmd/thanos/receive.go
  examples/interactive/interactive_test.go
  pkg/query/endpointset.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go
  pkg/query/test.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
  pkg/store/multitsdb.go
  pkg/store/multitsdb_test.go
  pkg/store/proxy.go
  pkg/store/proxy_heap.go
  pkg/store/proxy_test.go
  tutorials/interactive-example/README.md
Labels: size/XXL

#5757 Cut 0.28.1
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
Labels: size/XS

#5768 chore: Merge 0.28 to main
  CHANGELOG.md
Labels: size/XS

#5769 docs: fix typos
  docs/components/receive.md
  docs/components/store.md
  docs/governance.md
  docs/proposals-accepted/202206-active-series-limiting-hashring.md
Labels: size/XS

#5763 Compact: Enable metadata cache
  CHANGELOG.md
  cmd/thanos/compact.go
Labels: size/XS

#5770 Tests: Skip OCI objstore on local test
  Makefile
  docs/storage.md
Labels: size/S

#5767 *: Upgrade Prometheus to v2.39.0
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  go.mod
  go.sum
  internal/cortex/chunk/series_store.go
  internal/cortex/ingester/client/compat_test.go
  internal/cortex/querier/querier_test.go
  internal/cortex/util/metrics_helper.go
  pkg/alert/alert.go
  pkg/block/index.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compactv2/chunk_series_set.go
  pkg/compactv2/compactor_test.go
  pkg/compactv2/modifiers.go
  pkg/dedup/iter.go
  pkg/receive/multitsdb.go
  pkg/store/bucket_test.go
  pkg/store/postings_codec_test.go
  pkg/store/storepb/testutil/series.go
  pkg/testutil/e2eutil/prometheus.go
  test/e2e/query_test.go
Labels: size/L

#5771 *: Upgrade Prometheus to v2.39.1.
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/XS

#5779 chore: Bump objstore package to latest main
  CHANGELOG.md
  docs/storage.md
  go.mod
  go.sum
Labels: size/S

#5782 Add pooling for remote-write requests
  pkg/receive/handler.go
  pkg/receive/pool.go
Labels: size/L

#5673 Receive: Reload tenant limit configuration on file change
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  go.mod
  go.sum
  pkg/extkingpin/path_content_reloader.go
  pkg/extkingpin/path_content_reloader_test.go
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/limiter.go
  pkg/receive/limiter_config.go
  pkg/receive/limiter_config_test.go
  pkg/receive/limiter_test.go
  pkg/receive/request_limiter.go
  pkg/receive/request_limiter_test.go
  pkg/receive/testdata/limits.yaml
  pkg/receive/testdata/limits_config/invalid_limits.yaml
Labels: size/XL

#5741 Query: add query metrics to calls going through the Store API
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
  pkg/api/query/grpc.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/query/querier.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/query/query_test.go
  pkg/store/telemetry.go
  test/e2e/query_test.go
Labels: size/XL

#5799 Fix sharding behavior for vector matches
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
Labels: size/S

#5778 Update storage.md with Oracle Cloud Infrastructure provider
  docs/storage.md
Labels: size/M

#5806 *: cut 0.29.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/S

#5808 CHANGELOG: mark 0.29.0 as in progress
  CHANGELOG.md
  VERSION
Labels: size/S

#5814 store: add histogram for postings size
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/S

#5703 Store/Receivers: Calculating chunk hashes on stores/receivers
  cmd/thanos/store.go
  internal/cortex/storegateway/bucket_stores.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/storepb/types.pb.go
  pkg/store/storepb/types.proto
  pkg/store/tsdb.go
  pkg/store/tsdb_test.go
  test/e2e/query_frontend_test.go
Labels: size/L

#5817 Use pre-calculated hashes
  pkg/receive/multitsdb_test.go
  pkg/store/proxy_heap.go
  pkg/store/proxy_test.go
Labels: size/S

#5821 deps: Updated promql-engine to latest.
  go.mod
  go.sum
Labels: size/XS

#5785 Query: Trim very long external labels and add cmd flag to optionally specify metric labels to collect
  cmd/thanos/query.go
  docs/components/query.md
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
Labels: size/L

#5801 store: add downloaded bytes limit
  CHANGELOG.md
  cmd/thanos/store.go
  docs/components/store.md
  internal/cortex/storegateway/bucket_stores.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/limiter.go
  test/e2e/store_gateway_test.go
Labels: size/L

#5824 Mixin: Remove low ingestion rate warning for receiver
  examples/alerts/alerts.md
  examples/alerts/alerts.yaml
  mixin/alerts/receive.libsonnet
  mixin/runbook.md
Labels: size/M

#5831 Mixin: Remove low ingestion rate warning for receiver (fix tests)
  CHANGELOG.md
  pkg/rules/rules_test.go
Labels: size/XS

#5631 Fix Typo's in recieve.md
  docs/components/receive.md
Labels: size/XS

#5568 docs: Added guide for Community Office Hours shepherding.
  docs/contributing/community.md
  docs/contributing/mentorship.md
  docs/img/zoomedit.png
  docs/img/zoomrecording.png
Labels: size/M

#5834 *: Clean up stale bot config file
  .github/stale.yml
Labels: size/XS

#5836 Receive: Add experimental snapshot on shutdown
  CHANGELOG.md
  cmd/thanos/receive.go
  pkg/receive/multitsdb.go
Labels: size/M

#5716 Feature: Fix miekgdns resolver LookupSRV function to work with CNAME records too
  CHANGELOG.md
  pkg/discovery/dns/miekgdns/resolver.go
Labels: size/S
