Repository thanos-io/thanos, pull requests merged in 2022-05, with the labels that each got.

#5322 stalebot: add generic label to avoid stalebot
  .github/stale.yml
Labels: size/XS

#5308 Use proper replicalabels in GRPC Query API
  cmd/thanos/query.go
  pkg/api/query/grpc.go
Labels: size/S

#5323 groupcache: reduce log severity
  pkg/cache/groupcache.go
Labels: size/XS

#5325 Update release process
  docs/release-process.md
Labels: size/S

#5326 query-frontend: improve docs on requestes excluded from cache
  docs/components/query-frontend.md
Labels: size/XS

#5330 cut release 0.26.0
  CHANGELOG.md
  VERSION
  tutorials/katacoda/thanos/1-globalview/courseBase.sh
  tutorials/katacoda/thanos/1-globalview/step2.md
  tutorials/katacoda/thanos/1-globalview/step3.md
  tutorials/katacoda/thanos/2-lts/courseBase.sh
  tutorials/katacoda/thanos/2-lts/step1.md
  tutorials/katacoda/thanos/2-lts/step2.md
  tutorials/katacoda/thanos/2-lts/step3.md
  tutorials/katacoda/thanos/2-lts/step4.md
  tutorials/katacoda/thanos/6-query-caching/courseBase.sh
  tutorials/katacoda/thanos/6-query-caching/step1.md
  tutorials/katacoda/thanos/6-query-caching/step2.md
  tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
  tutorials/katacoda/thanos/7-multi-tenancy/step1.md
  tutorials/katacoda/thanos/7-multi-tenancy/step2.md
  tutorials/katacoda/thanos/x-playground/courseBase.sh
  tutorials/katacoda/thanos/x-playground/step1.md
  tutorials/katacoda/thanos/x-playground/step2.md
Labels: size/M

#5339 receive: fix deadlock on interrupt in routerOnly mode
  CHANGELOG.md
  cmd/thanos/receive.go
Labels: size/S

#5309 Updated information about our community call.
  docs/contributing/community.md
Labels: size/S

#5324 reloader: Force trigger reload when config rollbacked
  CHANGELOG.md
  pkg/reloader/reloader.go
  pkg/reloader/reloader_test.go
Labels: size/L

#5352 Add Cache metrics to groupcache
  CHANGELOG.md
  pkg/cache/groupcache.go
Labels: size/M

#5348 e2e: Refactored service helpers to be consistent with new API.
  go.mod
  go.sum
  pkg/objstore/s3/s3_e2e_test.go
  test/e2e/compact_test.go
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/service.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/info_api_test.go
  test/e2e/metadata_api_test.go
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
  test/e2e/rule_test.go
  test/e2e/rules_api_test.go
  test/e2e/store_gateway_test.go
  test/e2e/targets_api_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/XXL

#5357 groupcache: fix handling of slashes
  CHANGELOG.md
  pkg/cache/groupcache.go
  test/e2e/store_gateway_test.go
Labels: size/S

#5347 Adds more info about the formatting part.
  CONTRIBUTING.md
Labels: size/S

#5345 Update promdoc to solve #5344
  .bingo/Variables.mk
  .bingo/promdoc.mod
  .bingo/variables.env
Labels: size/S

#5358 e2e: Refactored Receive Builder to be consistent with other helpers.
  cmd/thanos/receive.go
  docs/components/receive.md
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
  test/e2e/rule_test.go
Labels: size/L

#5372 e2e: Fixed exemplar support in receive helper.
  test/e2e/e2ethanos/services.go
Labels: size/XS

#5360 Enforce memcached concurrency limit with unbatched requests
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/memcached_client_test.go
Labels: size/M

#5379 docs: fix link
  docs/contributing/coding-style-guide.md
Labels: size/XS

#5378 cache: do not copy data in groupcache
  pkg/cache/groupcache.go
Labels: size/S

#5377 Fix ruler send empty alerts
  pkg/alert/alert.go
  pkg/alert/alert_test.go
Labels: size/M

#5239 Write custom `errors` package with stack trace functionality
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/errors/stacktrace.go
  pkg/errors/stacktrace_test.go
Labels: size/L

#5356 Group memcached keys based on server when performing batch gets
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/memcached_client_test.go
  pkg/testutil/testutil.go
  pkg/testutil/testutil_test.go
Labels: size/L

#5383 QueryFrontend: pre-compile regexp
  pkg/queryfrontend/roundtrip.go
Labels: size/XS

#5394 rule: fix empty $externalLabels when templating labels in rule.
  pkg/rules/manager.go
Labels: size/XS
