Repository thanos-io/thanos, pull requests merged in 2022-11, with the labels that each got.

#5845 Update promql engine
  go.mod
  go.sum
Labels: size/XS

#5839 Receive: Add parameter to set out-of-order time window
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/writer.go
Labels: component: receive, size/S

#5844 Apply @ modifier start and end in QF split interval middleware
  CHANGELOG.md
  internal/cortex/querier/queryrange/split_by_interval.go
  internal/cortex/querier/queryrange/split_by_interval_test.go
  pkg/queryfrontend/roundtrip_test.go
  pkg/queryfrontend/split_by_interval.go
  pkg/queryfrontend/split_by_interval_test.go
Labels: size/L

#5846 Shard subqueries
  CHANGELOG.md
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
Labels: size/S

#5854 Support lookback_delta on query frontend
  CHANGELOG.md
  pkg/queryfrontend/cache.go
  pkg/queryfrontend/cache_test.go
  pkg/queryfrontend/queryinstant_codec.go
  pkg/queryfrontend/queryinstant_codec_test.go
  pkg/queryfrontend/queryrange_codec.go
  pkg/queryfrontend/queryrange_codec_test.go
  pkg/queryfrontend/request.go
Labels: size/M

#5851 Receive: Make out-of-order max cap parameter hidden
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/XS

#5855 *: release 0.29.0
  CHANGELOG.md
  VERSION
Labels: size/XS

#5858 Merge release 0.29 to main
  CHANGELOG.md
Labels: size/XS

#5856 store: add missing debugLogging set
  cmd/thanos/store.go
Labels: size/XS

#5867 Update minio to fix issue with Scaleway storage
  go.mod
  go.sum
Labels: size/XS

#5873 Added blog space on Thanos website.
  .mdox.yaml
  docs/blog/welcome.md
  netlify.toml
  website/layouts/_default/baseof.html
  website/layouts/partials/versioning/banner.html
  website/layouts/partials/versioning/version-picker.html
Labels: size/S

#5878 Adds medallia blog post
  docs/blog/2022-09-08-thanos-at-medallia.md
  docs/blog/img/architecture.png
  docs/blog/img/grafana-request-duration.png
  docs/blog/img/instant-query-latency.png
  docs/blog/img/query-trace.png
  docs/blog/img/range-query-latency.png
Labels: size/L

#5884 Update 2022-09-08-thanos-at-medallia.md
  docs/blog/2022-09-08-thanos-at-medallia.md
Labels: size/XS

#5886 change Hyperia logo
  website/static/logos/hyperia.png
Labels: size/XS

#5885 *:Fix stateless ruler config in quickstart
  scripts/quickstart.sh
Labels: size/XS

#5230 Stateless ruler restores alert state
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/rule.go
  docs/components/rule.md
  pkg/promclient/promclient.go
  pkg/rules/queryable.go
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/rule_test.go
Labels: size/XL

#5868 Update README.md
  README.md
Labels: size/XS

#5880 Fix querysharding labels analysis
  CHANGELOG.md
  pkg/queryfrontend/roundtrip.go
  pkg/querysharding/analysis.go
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
Labels: size/L

#5888 *: Fix lint
  scripts/quickstart.sh
Labels: size/XS

#5893 Cache: Fixed redis cache to use multi batch size config value
  CHANGELOG.md
  pkg/cacheutil/redis_client.go
Labels: size/XS

#5865 compact: retry on sync metas error
  CHANGELOG.md
  cmd/thanos/compact.go
Labels: size/S

#5853 Support matrix type response merge for instant query sharding
  internal/cortex/querier/queryrange/query_range.go
  pkg/queryfrontend/queryinstant_codec.go
  pkg/queryfrontend/queryinstant_codec_test.go
  pkg/querysharding/analyzer.go
Labels: size/L

#5889 Support vertical sharding for label_join and label_replace functions
  CHANGELOG.md
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
Labels: size/L

#5887 Tracing: Fix sampler defaults
  .circleci/config.yml
  CHANGELOG.md
  pkg/tracing/jaeger/config_yaml.go
  pkg/tracing/jaeger/jaeger_test.go
Labels: size/L

#5897 Update objstore to latest commit
  go.mod
  go.sum
Labels: size/XS

#5913 querier: Unhide `query.promql-engine` flag; added info in docs.
  cmd/thanos/query.go
  docs/components/query.md
Labels: size/S

#5909 Compact tenant TSDBs after 3h inactivity
  CHANGELOG.md
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/S

#5819 Store: Add a few objectives for Store's data touched/fetched amount and sizes
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/S

#5919 *: Quick CHANGELOG fix after #5819
  CHANGELOG.md
Labels: size/XS

#5838 Store: add data touched by type to the dashboard
  examples/dashboards/store.json
  mixin/dashboards/store.libsonnet
Labels: size/L

#5837 Implement lazy retrieval of series from object store.
  .gitignore
  cmd/thanos/query.go
  cmd/thanos/store.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/proxy_heap.go
  pkg/store/storepb/custom.go
Labels: size/XL

#5922 compact: retry on cleanPartialMarked errors if possible
  cmd/thanos/compact.go
Labels: size/S

#5928 docs: Updated documentation for OCI Object Storage, added link to blog post
  docs/getting-started.md
  docs/storage.md
Labels: size/S
