Repository thanos-io/thanos, pull requests merged in 2022-08, with the labels that each got.

#5556 Fix changed-docs grep regex
  Makefile
Labels: size/XS

#5558 Rule: Fix e2e test flake
  test/e2e/rule_test.go
Labels: size/M

#5554 Fix multi-tenant exemplar matchers
  CHANGELOG.md
  pkg/exemplars/proxy.go
  pkg/exemplars/proxy_test.go
Labels: size/L

#5527 Receive: add per request limits for remote write
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/limiter.go
  pkg/receive/limiter_test.go
Labels: size/XL

#5560 Announce sharding in ruler and store proxy
  cmd/thanos/query.go
  cmd/thanos/rule.go
Labels: size/S

#5563 Fix flaky e2e tests
  .github/workflows/go.yaml
  test/e2e/compact_test.go
  test/e2e/metadata_api_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/L

#5520 Meta-monitoring based active series limiting
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  go.mod
  go.sum
  pkg/receive/handler.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
Labels: size/XL

#5557 docs/contribution.md: Update required Go version
  CONTRIBUTING.md
Labels: size/XS

#5508 Receiver: Validate labels in write requests
  pkg/block/index.go
  pkg/compact/compact.go
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/writer.go
  pkg/receive/writer_test.go
  pkg/store/labelpb/label.go
  pkg/store/labelpb/label_test.go
Labels: size/L

#5574 test: use `T.TempDir` to create temporary test directory
  cmd/thanos/main_test.go
  pkg/api/blocks/v1_test.go
  pkg/api/query/v1_test.go
  pkg/block/block_test.go
  pkg/block/fetcher_test.go
  pkg/block/index_test.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader_test.go
  pkg/block/indexheader/reader_pool_test.go
  pkg/block/metadata/hash_test.go
  pkg/block/metadata/markers_test.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/downsample/downsample_test.go
  pkg/compactv2/compactor_test.go
  pkg/query/query_bench_test.go
  pkg/receive/handler_test.go
  pkg/receive/multitsdb_test.go
  pkg/receive/writer_test.go
  pkg/reloader/reloader_test.go
  pkg/rules/manager_test.go
  pkg/runutil/runutil_test.go
  pkg/shipper/shipper_e2e_test.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/multitsdb_test.go
  pkg/store/postings_codec_test.go
  pkg/store/proxy_test.go
  pkg/store/tsdb_test.go
  test/e2e/tls_test.go
Labels: size/L

#5555 Flag to add active query tracker.
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/query_test.go
  docs/components/query.md
Labels: size/M

#5559 docs: Add Thanos sidecar Prometheus HTTP client config format
  cmd/thanos/config.go
  docs/components/sidecar.md
Labels: size/M

#5566 receive: Expose write chunk queue as flag
  CHANGELOG.md
  cmd/thanos/receive.go
Labels: size/S

#5575 Add support for snappy compression in receivers
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/extgrpc/snappy/snappy.go
  pkg/extgrpc/snappy/snappy_test.go
Labels: size/L

#5439 Add Alert ThanosQueryOverload to Mixin
  CHANGELOG.md
  examples/alerts/alerts.md
  examples/alerts/alerts.yaml
  mixin/alerts/query.libsonnet
  mixin/runbook.md
  pkg/rules/rules_test.go
Labels: size/M

#5583 api: fix race between Respond() and query/queryRange
  CHANGELOG.md
  pkg/api/api.go
  pkg/api/blocks/v1.go
  pkg/api/blocks/v1_test.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/api/rule/v1.go
  pkg/api/status/v1.go
Labels: size/L

#5579 *: Add #5508 to CHANGELOG
  CHANGELOG.md
Labels: size/XS

#5544 Receive: Writer benchmark - address feedback from previous
  pkg/receive/writer_test.go
Labels: size/S

#5480 Expose Endpoint Info timeout parameter
  CHANGELOG.md
  cmd/thanos/query.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
Labels: size/M

#5596 Filter external labels from matchers on LabelValues/LabelNames
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#5588 Store: improve index header reading performance by sorting values
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#5608 add myself yeya24 to release shepherd for v0.28.0
  docs/release-process.md
Labels: size/XS

#5612 Query Frontend: Add tests and fix previous bugs for instant query tripperware
  CHANGELOG.md
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/queryrange.pb.go
  internal/cortex/querier/queryrange/queryrange.proto
  pkg/queryfrontend/queryinstant_codec.go
  pkg/queryfrontend/queryinstant_codec_test.go
  pkg/queryfrontend/request.go
  pkg/queryfrontend/shard_query.go
  test/e2e/compatibility_test.go
  test/e2e/query_frontend_test.go
Labels: size/XXL

#5629 Query: remove verbose info log
  pkg/store/proxy.go
Labels: size/XS

#5607 Support custom lookback delta from request for query api
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/query_test.go
  go.mod
  go.sum
  internal/cortex/querier/astmapper/astmapper_test.go
  internal/cortex/querier/astmapper/shard_summer_test.go
  internal/cortex/querier/queryrange/querysharding_test.go
  pkg/api/query/grpc.go
  pkg/api/query/querypb/query.pb.go
  pkg/api/query/querypb/query.proto
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/query/querier_test.go
  pkg/receive/handler_test.go
  pkg/rules/manager_test.go
Labels: size/L

#5604 Ensure distinct replication
  cmd/thanos/receive.go
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
Labels: size/L

#5632 Cut 0.28.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/M

#5642 Receiver: Fix labels debug logging in writer
  CHANGELOG.md
  pkg/receive/writer.go
Labels: size/XS

#5647 *: Cut v0.28.0
  CHANGELOG.md
  VERSION
Labels: size/XS

#5620 Update compact.md
  docs/components/compact.md
Labels: size/M

#5655 Fix creation of already pruned tenants
  CHANGELOG.md
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/M

#5652 *: merge release-0.28 branch to main
  CHANGELOG.md
  VERSION
  docs/release-process.md
Labels: size/M

#5654 query: add --grpc-compression for enabling compression
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
Labels: size/S

#5650 Add sharded queries metrics
  CHANGELOG.md
  pkg/queryfrontend/roundtrip.go
  pkg/queryfrontend/shard_query.go
Labels: size/S

#5615 macOS/arm64 e2e test improvements
  go.mod
  go.sum
  pkg/testutil/e2eutil/prometheus.go
  scripts/quickstart.sh
  test/e2e/compact_test.go
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/info_api_test.go
  test/e2e/metadata_api_test.go
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
  test/e2e/rule_test.go
  test/e2e/rules_api_test.go
  test/e2e/store_gateway_test.go
  test/e2e/targets_api_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/L
