Repository thanos-io/thanos, pull requests merged in 2022-03, with the labels that each got.

#5202 fix: add null check to exemplar data
  pkg/exemplars/exemplars.go
Labels: size/XS

#5192 Docs: Update release process doc
  docs/release-process.md
Labels: size/M

#5187 E2E Tests: Bump `efficientgo/e2e` version
  go.mod
  go.sum
  test/e2e/e2ethanos/service.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
  test/e2e/rule_test.go
  test/e2e/rules_api_test.go
  test/e2e/store_gateway_test.go
Labels: size/L

#5204 Store: Fix data race in advertised label set in bucket store
  pkg/info/info.go
  pkg/store/bucket.go
  test/e2e/query_test.go
Labels: size/M

#5205 Append ruler labels as external labels when using stateless ruler mode
  CHANGELOG.md
  cmd/thanos/rule.go
  test/e2e/rule_test.go
Labels: size/XS

#5206 cache: add timeout for groupcache's fetch operation
  CHANGELOG.md
  docs/components/store.md
  pkg/cache/groupcache.go
Labels: size/S

#5209 *: Cut v0.25.0
  CHANGELOG.md
  VERSION
  docs/release-process.md
  tutorials/katacoda/thanos/1-globalview/courseBase.sh
  tutorials/katacoda/thanos/1-globalview/step2.md
  tutorials/katacoda/thanos/1-globalview/step3.md
  tutorials/katacoda/thanos/2-lts/courseBase.sh
  tutorials/katacoda/thanos/2-lts/step1.md
  tutorials/katacoda/thanos/2-lts/step2.md
  tutorials/katacoda/thanos/2-lts/step3.md
  tutorials/katacoda/thanos/2-lts/step4.md
  tutorials/katacoda/thanos/6-query-caching/courseBase.sh
  tutorials/katacoda/thanos/6-query-caching/step1.md
  tutorials/katacoda/thanos/6-query-caching/step2.md
  tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
  tutorials/katacoda/thanos/7-multi-tenancy/step1.md
  tutorials/katacoda/thanos/7-multi-tenancy/step2.md
  tutorials/katacoda/thanos/x-playground/courseBase.sh
  tutorials/katacoda/thanos/x-playground/step1.md
  tutorials/katacoda/thanos/x-playground/step2.md
Labels: size/M

#5214 website: Add Ukraine support banner.
  website/layouts/index.html
Labels: size/XS

#5215 website: Fixing banner.
  website/layouts/index.html
  website/static/main.css
Labels: size/S

#5218 Run downsample tool continuously
  CHANGELOG.md
  cmd/thanos/downsample.go
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
Labels: size/M

#5216 unify and tidy objstore setup
  pkg/objstore/azure/azure.go
  pkg/objstore/bos/bos.go
  pkg/objstore/gcs/gcs.go
  pkg/objstore/oss/oss.go
Labels: component: store, size/M

#5170 Change Server TLS Min Version to 1.3
  pkg/tls/options.go
Labels: size/XS

#5224 receive: remove sort on label hashing
  CHANGELOG.md
  pkg/receive/hashring.go
Labels: size/XS

#5226 Create v0.25.1 built with Go 1.17.8
  CHANGELOG.md
  VERSION
Labels: size/S

#5220 query-frontend: support forward-header to downstream querier
  CHANGELOG.md
  cmd/thanos/query_frontend.go
  docs/components/query-frontend.md
  pkg/queryfrontend/config.go
  pkg/queryfrontend/labels_codec.go
  pkg/queryfrontend/queryrange_codec.go
  pkg/queryfrontend/request.go
  pkg/queryfrontend/roundtrip.go
Labels: size/M

#5231 ignore blocks with deletion markers
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
Labels: size/XS

#5181 E2E Tests: Improve Prometheus configurability and make query tests more resilient
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/info_api_test.go
  test/e2e/metadata_api_test.go
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
  test/e2e/rules_api_test.go
  test/e2e/targets_api_test.go
Labels: size/L

#5236 makefile: Fix Makefile support for arm64
  Makefile
Labels: size/S

#4838 Tracing: Migrate Google Cloud (Stackdriver) client to OpenTelemetry
  docs/tracing.md
  examples/interactive/interactive_test.go
  go.mod
  go.sum
  pkg/tracing/client/factory.go
  pkg/tracing/google_cloud/google_cloud.go
  pkg/tracing/google_cloud/google_cloud_test.go
  pkg/tracing/grpc.go
  pkg/tracing/http.go
  pkg/tracing/migration/bridge.go
  pkg/tracing/migration/sampler.go
  pkg/tracing/stackdriver/tracer_test.go
  scripts/cfggen/main.go
Labels: size/XL

#5242 Ruler: Fix WAL directory in stateless mode
  CHANGELOG.md
  cmd/thanos/rule.go
Labels: size/XS

#5243 Switch to prometheus notifier.Alert
  cmd/thanos/rule.go
  pkg/alert/alert.go
  pkg/alert/alert_test.go
Labels: size/M

#5244 query: promote negative offset and at-modifier to stable
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
Labels: size/S

#5245 Tracing: Remove forgotten debug line
  pkg/tracing/grpc.go
Labels: size/XS

#5246 e2e: fix compact test's flakiness
  test/e2e/compact_test.go
Labels: size/XS

#5247 *: Cut 0.25.2 rc.0
  .busybox-versions
  CHANGELOG.md
  VERSION
  cmd/thanos/rule.go
  pkg/exemplars/exemplars.go
Labels: size/S

#5253 *: Cut release 0.25.2
  CHANGELOG.md
  VERSION
  tutorials/katacoda/thanos/1-globalview/courseBase.sh
  tutorials/katacoda/thanos/1-globalview/step2.md
  tutorials/katacoda/thanos/1-globalview/step3.md
  tutorials/katacoda/thanos/2-lts/courseBase.sh
  tutorials/katacoda/thanos/2-lts/step1.md
  tutorials/katacoda/thanos/2-lts/step2.md
  tutorials/katacoda/thanos/2-lts/step3.md
  tutorials/katacoda/thanos/2-lts/step4.md
  tutorials/katacoda/thanos/6-query-caching/courseBase.sh
  tutorials/katacoda/thanos/6-query-caching/step1.md
  tutorials/katacoda/thanos/6-query-caching/step2.md
  tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
  tutorials/katacoda/thanos/7-multi-tenancy/step1.md
  tutorials/katacoda/thanos/7-multi-tenancy/step2.md
  tutorials/katacoda/thanos/x-playground/courseBase.sh
  tutorials/katacoda/thanos/x-playground/step1.md
  tutorials/katacoda/thanos/x-playground/step2.md
Labels: size/M

#5256 chore: bump prometheus version to v2.33.5
  go.mod
  go.sum
Labels: size/XS

#5255 info: Return store info only when the service is ready
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  pkg/prober/http.go
  pkg/prober/http_test.go
Labels: size/M

#5210 Merge release 0.25 to main
  CHANGELOG.md
  docs/release-process.md
  tutorials/katacoda/thanos/1-globalview/courseBase.sh
  tutorials/katacoda/thanos/1-globalview/step2.md
  tutorials/katacoda/thanos/1-globalview/step3.md
  tutorials/katacoda/thanos/2-lts/courseBase.sh
  tutorials/katacoda/thanos/2-lts/step1.md
  tutorials/katacoda/thanos/2-lts/step2.md
  tutorials/katacoda/thanos/2-lts/step3.md
  tutorials/katacoda/thanos/2-lts/step4.md
  tutorials/katacoda/thanos/6-query-caching/courseBase.sh
  tutorials/katacoda/thanos/6-query-caching/step1.md
  tutorials/katacoda/thanos/6-query-caching/step2.md
  tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
  tutorials/katacoda/thanos/7-multi-tenancy/step1.md
  tutorials/katacoda/thanos/7-multi-tenancy/step2.md
  tutorials/katacoda/thanos/x-playground/courseBase.sh
  tutorials/katacoda/thanos/x-playground/step1.md
  tutorials/katacoda/thanos/x-playground/step2.md
Labels: size/L

#5250 Implement GRPC query API
  CHANGELOG.md
  Makefile
  cmd/thanos/query.go
  docs/proposals-done/202203-grpc-query-api.md
  pkg/api/query/grpc.go
  pkg/api/query/querypb/query.pb.go
  pkg/api/query/querypb/query.proto
  pkg/api/query/querypb/responses.go
  pkg/api/query/querypb/store_matchers.go
  pkg/store/storepb/prompb/samples.go
  scripts/genproto.sh
  test/e2e/query_test.go
Labels: size/XXL

#5229 Change error cleanup in `objstore.DownloadDir` to delete files not destination dir
  pkg/objstore/objstore.go
  pkg/objstore/objstore_test.go
Labels: size/M
