Repository thanos-io/thanos, pull requests merged in 2022-01, with the labels that each got.

#5014 query: set default times for query_exemplars API
  pkg/api/query/v1.go
Labels: size/XS

#4997 [Website] Fixed community button spacing for smaller devices
  website/static/main.css
Labels: size/XS

#5018 Merge release 0.24 to main
  CHANGELOG.md
  VERSION
  docs/release-process.md
  tutorials/katacoda/thanos/1-globalview/courseBase.sh
  tutorials/katacoda/thanos/1-globalview/step2.md
  tutorials/katacoda/thanos/1-globalview/step3.md
  tutorials/katacoda/thanos/2-lts/courseBase.sh
  tutorials/katacoda/thanos/2-lts/step1.md
  tutorials/katacoda/thanos/2-lts/step2.md
  tutorials/katacoda/thanos/2-lts/step3.md
  tutorials/katacoda/thanos/2-lts/step4.md
  tutorials/katacoda/thanos/6-query-caching/courseBase.sh
  tutorials/katacoda/thanos/6-query-caching/step1.md
  tutorials/katacoda/thanos/6-query-caching/step2.md
  tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
  tutorials/katacoda/thanos/7-multi-tenancy/step1.md
  tutorials/katacoda/thanos/7-multi-tenancy/step2.md
  tutorials/katacoda/thanos/x-playground/courseBase.sh
  tutorials/katacoda/thanos/x-playground/step1.md
  tutorials/katacoda/thanos/x-playground/step2.md
Labels: size/L

#5023 *: Fix docker-build target
  Makefile
Labels: size/XS

#5019 [Website] Fixed `footer` items alignment
  website/layouts/_default/baseof.html
  website/static/main.css
Labels: size/S

#5020 store: close bkt properly
  cmd/thanos/store.go
Labels: size/XS

#5027 Update docs for new/correct way of building Thanos
  docs/getting-started.md
Labels: size/S

#5028 Feature/quick docs - only check docs that are changed for quick dev work
  Makefile
Labels: size/XS

#4883 mixin: adhere to RFC 1123 compatible component naming
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  examples/dashboards/bucket-replicate.json
  examples/dashboards/dashboards.md
  examples/dashboards/query-frontend.json
  mixin/alerts/absent.libsonnet
  mixin/alerts/add-runbook-links.libsonnet
  mixin/alerts/alerts.libsonnet
  mixin/alerts/bucket-replicate.libsonnet
  mixin/dashboards/bucket-replicate.libsonnet
  mixin/dashboards/dashboards.libsonnet
  mixin/dashboards/query-frontend.libsonnet
  mixin/lib/utils.libsonnet
  mixin/rules/bucket-replicate.libsonnet
  mixin/rules/rules.libsonnet
  mixin/separated-alerts.jsonnet
Labels: size/M

#5034 cli: print usage before error when argument parsing causes an error
  pkg/extkingpin/app.go
Labels: size/XS

#4818 store: Add Groupcache as a cache backend
  CHANGELOG.md
  cmd/thanos/store.go
  go.mod
  go.sum
  pkg/cache/caching_bucket_config.go
  pkg/cache/groupcache.go
  pkg/store/cache/cache_test.go
  pkg/store/cache/cachekey/cachekey.go
  pkg/store/cache/cachekey/cachekey_test.go
  pkg/store/cache/caching_bucket.go
  pkg/store/cache/caching_bucket_config.go
  pkg/store/cache/caching_bucket_factory.go
  pkg/store/cache/caching_bucket_test.go
  scripts/quickstart.sh
  test/e2e/store_gateway_test.go
Labels: size/XXL

#4662 lint: Do not check `*.md` files for white noise
  CHANGELOG.md
  Makefile
  docs/components/compact.md
  docs/components/query-frontend.md
  docs/components/query.md
  docs/components/receive.md
  docs/components/rule.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/components/tools.md
  docs/getting-started.md
  docs/proposals-accepted/202108-more-granular-query-performance-metrics.md
  pkg/ui/react-app/README.md
Labels: size/XL

#5046 chore: Use correct component name for bucket tools retention
  cmd/thanos/tools_bucket.go
  pkg/component/component.go
Labels: size/XS

#5035 query: fix querying with interleaved data
  pkg/query/querier.go
  test/e2e/query_test.go
Labels: size/L

#5053 Add hyperia as an adopter
  website/data/adopters.yml
  website/static/logos/hyperia.png
Labels: size/XS

#5051 prober: Remove spam of changing probe status
  CHANGELOG.md
  pkg/prober/intrumentation.go
Labels: size/M

#5063 Add redis to index cache support type list.
  docs/components/store.md
Labels: size/XS

#5054 cache: add benchmark + fix peer loading
  pkg/cache/groupcache.go
  pkg/cache/groupcache_test.go
  test/e2e/store_gateway_test.go
Labels: size/M

#4991 start minio server with tls
  pkg/objstore/s3/s3_e2e_test.go
  test/e2e/compact_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/info_api_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/L

#5067 Change company for Wiard
  MAINTAINERS.md
Labels: size/S

#5076 add NewBucketWithConfig for cos objstore
  pkg/objstore/cos/cos.go
Labels: size/XS

#5083 *: Attempt to fix multiarch builds by updating remote Docker engine version
  .circleci/config.yml
Labels: size/XS

#5059 Compactor: Adding minimum retention flag validation for downsampling retention
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
  docs/components/compact.md
  pkg/compact/compact.go
  pkg/compact/compact_test.go
  pkg/compact/downsample/downsample.go
Labels: size/M

#5092 Add talk and blog post of use cases at LastPass to the Getting Started section
  docs/getting-started.md
Labels: size/XS

#5098 Add Epidemic Sound as Adopter
  website/data/adopters.yml
  website/static/logos/epidemicsound.png
Labels: size/XS

#5093 Support triggering update sha workflow manually
  .github/workflows/container-version.yaml
Labels: size/XS

#5096 Use Milliseconds instead of Second since ResLevel1DownsampleRange is …
  cmd/thanos/compact.go
Labels: size/S

#5100 *: Fix missing white space in `compactor.md`
  docs/components/compact.md
Labels: size/XS

#5099 Fixed typo in sidecar docs
  docs/components/sidecar.md
Labels: size/XS

#5084 cache: add os.Exit if starting HTTP fails
  pkg/cache/groupcache_test.go
Labels: size/XS

#4963 compact+store+tools: Filter for duplicate block data only within a compaction group and in parallel
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
  cmd/thanos/store.go
  cmd/thanos/tools_bucket.go
  pkg/block/fetcher.go
  pkg/block/fetcher_test.go
  pkg/block/metadata/meta.go
  pkg/block/node.go
  pkg/compact/clean_test.go
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/compact_test.go
  pkg/compact/retention_test.go
  pkg/replicate/replicator.go
  pkg/replicate/scheme_test.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/verifier/overlapped_blocks.go
  test/e2e/compact_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/info_api_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
Labels: component: compact, size/L

#5107 Docs: Remove link to a deleted resource from mixin docs
  mixin/README.md
Labels: size/XS

#5110 Do not upload meta files to obj store
  CHANGELOG.md
  pkg/block/block.go
  pkg/block/block_test.go
  pkg/shipper/shipper_e2e_test.go
Labels: size/M
