Repository thanos-io/thanos, pull requests merged in 2022-06, with the labels that each got.

#5400 Expose block.GatherFileStats.
  pkg/block/block.go
Labels: size/XS

#5405 Rule: Error out earlier when building alertmanager config
  pkg/alert/config.go
  pkg/alert/config_test.go
Labels: size/S

#5392 [5130] [.*:] Upgrade Minio used for local development and e2e tests
  .bingo/.gitignore
  .bingo/Variables.mk
  .bingo/alertmanager.sum
  .bingo/goimports.sum
  .bingo/minio.mod
  .bingo/minio.sum
  .bingo/prometheus.1.sum
  .bingo/prometheus.2.sum
  .bingo/prometheus.sum
  .bingo/promu.sum
  .bingo/shfmt.sum
  .bingo/variables.env
Labels: size/XXL

#5350 Submit a proposal for vertical query sharding
  docs/img/latency-with-sharding.png
  docs/img/latency-without-sharding.png
  docs/img/memory-with-sharding.png
  docs/img/memory-without-sharding.png
  docs/img/vertical-sharding.png
  docs/proposals-accepted/202205-vertical-query-sharding.md
Labels: size/L

#5410 query: Close() after using query
  CHANGELOG.md
  pkg/api/query/grpc.go
  pkg/api/query/v1.go
Labels: size/XS

#5412 Avoided potential panic due to divide by 0
  pkg/tracing/google_cloud/google_cloud.go
Labels: size/XS

#5337 sidecar/compact/store/receiver - Add the prefix option to buckets
  CHANGELOG.md
  docs/components/receive.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/components/tools.md
  docs/storage.md
  pkg/objstore/client/factory.go
  pkg/objstore/objtesting/foreach.go
  pkg/objstore/prefixed_bucket.go
  pkg/objstore/prefixed_bucket_test.go
Labels: size/L

#5417 Ruler: Change default evaluation interval to 1m
  CHANGELOG.md
  cmd/thanos/rule.go
  docs/components/rule.md
Labels: size/XS

#5409 S3: Add config option to enforce the minio DNS lookup
  CHANGELOG.md
  docs/storage.md
  pkg/objstore/s3/s3.go
  test/e2e/e2ethanos/services.go
Labels: size/M

#5402 Expose tsdb status in receiver
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/api/status/v1.go
  pkg/receive/handler.go
  pkg/receive/multitsdb.go
Labels: size/L

#5153 Receive: option to extract tenant from client certificate
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/handler.go
Labels: size/M

#5427 Improve ketama hashring replication
  CHANGELOG.md
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
Labels: size/M

#5315 Added alert compliance test for Thanos
  cmd/thanos/rule.go
  docs/components/rule.md
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/services.go
Labels: size/L

#5430 0.27-rc0 Update readme and version
  CHANGELOG.md
  VERSION
Labels: size/S

#5433 Alert Compliance: Fix wrong ruler configuration
  test/e2e/compatibility_test.go
Labels: size/XS

#5424 [receive] Export metrics about remote write requests per tenant
  CHANGELOG.md
  pkg/extprom/http/instrument_server.go
  pkg/extprom/http/instrument_tenant_server.go
  pkg/extprom/http/metrics.go
  pkg/receive/handler.go
Labels: size/L

#5426 remove unused block-sync-concurrency flag
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/tools_bucket.go
  docs/components/compact.md
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
  test/e2e/e2ethanos/services.go
Labels: size/M

#5448 docs: fix typo in thanos_compact_halted
  docs/components/compact.md
Labels: size/XS

#5420 Implement tenant expiration
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/errutil/multierror.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/L

#5454 Docs: Remove Katacoda links
  CONTRIBUTING.md
  docs/getting-started.md
  docs/quick-tutorial.md
  tutorials/katacoda/README.md
Labels: size/S
