Repository thanos-io/thanos, pull requests merged in 2022-09, with the labels that each got.

#5640 block fetcher: hide TxGaugeVec behind an interface
  internal/cortex/storegateway/bucket_stores.go
  internal/cortex/storegateway/bucket_stores_test.go
  internal/cortex/storegateway/gateway_test.go
  internal/cortex/storegateway/metadata_fetcher_filters.go
  internal/cortex/storegateway/sharding_strategy.go
  pkg/block/fetcher.go
  pkg/block/fetcher_test.go
  pkg/compact/compact.go
Labels: size/M

#5573 sidecar: Add args prometheus.get_config_interval and prometheus.timeout_get_config
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/sidecar.go
  docs/components/sidecar.md
Labels: size/S

#5661 Created .devcontainer.json file for Github codespaces
  .devcontainer/devcontainer.json
Labels: size/S

#5648 Cache vertical shards in query frontend
  pkg/queryfrontend/cache.go
  pkg/queryfrontend/cache_test.go
  pkg/queryfrontend/roundtrip.go
  pkg/queryfrontend/roundtrip_test.go
Labels: size/L

#5670 website: Added OYO as an adopter
  website/data/adopters.yml
  website/static/logos/OYO.png
Labels: size/XS

#5666 Bump protoc version for better compability with Apple Silicon
  Makefile
  scripts/genproto.sh
  scripts/installprotoc.sh
Labels: size/S

#5565 Receive: Allow remote write request limits to be defined per file and tenant
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/limiter.go
  pkg/receive/limiter_config.go
  pkg/receive/limiter_config_test.go
  pkg/receive/request_limiter.go
  pkg/receive/request_limiter_test.go
  pkg/receive/testdata/limits_config/good_limits.yaml
Labels: size/XL

#5678 Adding udaan as adopter of Thanos
  website/data/adopters.yml
  website/static/logos/udaan.png
Labels: size/XS

#5296 store: use k-way merging for proxying logic
  CHANGELOG.md
  cmd/thanos/query.go
  pkg/query/query_test.go
  pkg/store/proxy.go
  pkg/store/proxy_heap.go
  pkg/store/proxy_test.go
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/XXL

#5649 Receiver: Simplify readiness behavior on hashring change
  cmd/thanos/receive.go
Labels: size/L

#5680 Updating udaan logo in adopters list
  website/static/logos/udaan.png
Labels: size/XS

#5656 treewide: fix typo of gRPC
  docs/proposals-accepted/202107-protobuf-openapi-httpapi.md
  examples/dashboards/overview.json
  mixin/dashboards/sidecar.libsonnet
  mixin/dashboards/store.libsonnet
Labels: size/S

#5660 chore: remove duplicate word in comments
  examples/dashboards/overview.json
  examples/dashboards/query-frontend.json
  examples/dashboards/query.json
  internal/cortex/chunk/schema.go
  internal/cortex/querier/batch/stream.go
  internal/cortex/ring/kv/client.go
  internal/cortex/ring/kv/etcd/etcd.go
  mixin/dashboards/query-frontend.libsonnet
  mixin/dashboards/query.libsonnet
  pkg/receive/handler.go
  pkg/server/http/option.go
Labels: size/M

#5684 Route parse errors from sharding through normal api path
  pkg/queryfrontend/shard_query.go
Labels: size/XS

#5658 Query Frontend: dynamic horizontal query sharding
  CHANGELOG.md
  cmd/thanos/query_frontend.go
  docs/components/query-frontend.md
  pkg/queryfrontend/config.go
  pkg/queryfrontend/config_test.go
  pkg/queryfrontend/roundtrip.go
  pkg/queryfrontend/roundtrip_test.go
Labels: size/L

#5688 QueryFrontend: fixing bug on cortex cache for range query when using dynamic sharding
  pkg/queryfrontend/cache.go
  pkg/queryfrontend/cache_test.go
  pkg/queryfrontend/roundtrip.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_frontend_test.go
Labels: size/L

#5690 Compact: update "accept malformed index" flag to apply to downsampling
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
Labels: size/S

#5696 .*: fix: re-enable some golang runtime metrics
  cmd/thanos/main.go
Labels: size/XS

#5698 chore: Update my company info
  MAINTAINERS.md
Labels: size/S

#5702 Updates minio-go to v7.0.37 from v7.0.32
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/XS

#5691 query: Enabled experimental thanos-community promql-engine behind the hidden flag.
  cmd/thanos/query.go
  go.mod
  go.sum
  pkg/api/query/grpc.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
Labels: size/M

#5708 Update my company info
  MAINTAINERS.md
Labels: size/XS

#5709 Send sorted series from Receiver
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  pkg/info/infopb/rpc.pb.go
  pkg/info/infopb/rpc.proto
  pkg/query/endpointset.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go
  pkg/query/test.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/tsdb.go
Labels: size/L

#5707 Objstore: Update objstore to latest version
  .circleci/config.yml
  .github/workflows/codeql-analysis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  docs/getting-started.md
  go.mod
  go.sum
Labels: size/S

#5718 Announce sorted series from Ruler
  cmd/thanos/rule.go
Labels: size/XS

#5713 chore: Bump e2e framework version to latest main
  examples/interactive/interactive_test.go
  go.mod
  go.sum
  test/e2e/compact_test.go
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/metadata_api_test.go
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
  test/e2e/rule_test.go
  test/e2e/rules_api_test.go
  test/e2e/store_gateway_test.go
  test/e2e/targets_api_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/XXL

#5685 Receive: Make head series limiting config per tenant
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/httpconfig/http.go
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/head_series_limiter.go
  pkg/receive/limiter.go
  pkg/receive/limiter_config.go
  pkg/receive/limiter_config_test.go
  pkg/receive/request_limiter.go
  pkg/receive/request_limiter_test.go
  pkg/receive/testdata/limits_config/good_limits.yaml
  test/e2e/e2ethanos/services.go
  test/e2e/receive_test.go
Labels: size/XL

#5714 Query Frontend: Split interval middleware sends query when start equals false
  internal/cortex/querier/queryrange/split_by_interval.go
  internal/cortex/querier/queryrange/split_by_interval_test.go
Labels: size/S

#5721 add metrics for bucket store empty postings count
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#5641 Remove hardcoded labels in store shard matcher and inject unshardable label in query analyzer
  CHANGELOG.md
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
  pkg/store/storepb/shard_info.go
Labels: size/S

#5723 Compactor: Support disable block viewer UI
  CHANGELOG.md
  cmd/thanos/compact.go
  docs/components/compact.md
Labels: size/M

#5724 Bump thanos-community/promql-engine to latest version
  go.mod
  go.sum
Labels: size/XS

#5731 Tests: Skip flaky compactor test
  test/e2e/compact_test.go
Labels: size/XS

#5674 query frontend, store: Add TLS support to redis_client
  CHANGELOG.md
  docs/components/query-frontend.md
  docs/components/store.md
  pkg/cacheutil/redis_client.go
  pkg/cacheutil/redis_client_test.go
Labels: size/L

#5726 Docs: Document how to delete an interval via `thanos tools bucket rewrite`
  docs/operating/modify-objstore-data.md
Labels: size/S

#5736 Compact: Make GatherNoCompactionMarkFilter.NoCompactMarkedBlocks concurrency safe
  CHANGELOG.md
  pkg/compact/compact.go
Labels: size/S

#5734 Store: Support disable block viewer UI.
  CHANGELOG.md
  cmd/thanos/store.go
  docs/components/store.md
Labels: size/S

#5739 chore: Log compaction run total time from block download
  pkg/compact/compact.go
Labels: size/S

#5740 Bump promql engine version
  go.mod
  go.sum
Labels: size/XS

#5738 replaced crypto/sha with https://github.com/minio/sha256-simd
  go.mod
  internal/cortex/chunk/schema_util.go
  pkg/block/metadata/hash.go
  pkg/reloader/reloader.go
Labels: size/XS

#5744 Adds Adfinis as adopter
  website/data/adopters.yml
  website/static/logos/adfinis.png
Labels: size/XS
