Repository thanos-io/thanos, pull requests merged in 2022-07, with the labels that each got.

#5459 Fixed lint on Go 1.18.3+
  .bingo/Variables.mk
  .bingo/faillint.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  pkg/ui/query.go
Labels: size/XXL

#5440 Add HTTP metrics for in-flight requests
  CHANGELOG.md
  pkg/extprom/http/instrument_server.go
  pkg/extprom/http/metrics.go
Labels: size/L

#5455 docs: Fix heading level of "Excluded from caching"
  docs/components/query-frontend.md
Labels: size/XS

#5447 Refactor DefaultTransport() from objstore to package exthttp
  cmd/thanos/query_frontend.go
  docs/storage.md
  pkg/exthttp/tlsconfig.go
  pkg/exthttp/transport.go
  pkg/objstore/azure/azure.go
  pkg/objstore/azure/azure_test.go
  pkg/objstore/azure/helpers.go
  pkg/objstore/cos/cos.go
  pkg/objstore/cos/cos_test.go
  pkg/objstore/s3/s3.go
  pkg/objstore/s3/s3_test.go
  test/e2e/e2ethanos/services.go
Labels: size/L

#5460 receive: Fix race condition when pruning tenants
  pkg/receive/multitsdb.go
Labels: size/S

#5466 Adding SCMP as an adopter
  website/data/adopters.yml
  website/static/logos/scmp.png
Labels: size/XS

#5471 Updated busybox version.
  .busybox-versions
Labels: size/S

#5473 *: Cut 0.27.0
  .busybox-versions
  CHANGELOG.md
  CONTRIBUTING.md
  VERSION
  docs/getting-started.md
  docs/quick-tutorial.md
  docs/release-process.md
  tutorials/katacoda/README.md
Labels: size/M

#5258 Build with Go 1.18
  .bingo/Variables.mk
  .bingo/golangci-lint.sum
  .bingo/minio.mod
  .bingo/minio.sum
  .bingo/prometheus.1.mod
  .bingo/prometheus.2.mod
  .bingo/prometheus.mod
  .bingo/variables.env
  .circleci/config.yml
  .github/workflows/go.yaml
  .go-version
  .promu.yml
  Dockerfile.multi-stage
  go.mod
  go.sum
Labels: size/XXL

#5465 Update compact.md
  docs/components/compact.md
Labels: size/XS

#5453 During 1h downsampling skip XOR chunks that may erroneously be present in 5m resolution blocks
  CHANGELOG.md
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
Labels: size/M

#5479 *: Merge release 0.27 to main
  CHANGELOG.md
  docs/release-process.md
Labels: size/M

#5468 Endpoint: Refactor get clients methods
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
  test/e2e/query_test.go
Labels: size/M

#5451 Use Azure BlobURL.Download instead of in-memory buffer
  CHANGELOG.md
  pkg/objstore/azure/azure.go
Labels: size/M, package: objstore

#5486 Typo fixed in storage.md file
  docs/storage.md
Labels: size/XS

#5472 [receive] Add per-tenant charts to Receive's example dashboard
  CHANGELOG.md
  examples/dashboards/receive.json
  mixin/dashboards/receive.libsonnet
Labels: size/XL

#5475 objstore: Download and Upload block files in parallel
  CHANGELOG.md
  cmd/thanos/compact.go
  docs/components/compact.md
  go.mod
  go.sum
  pkg/block/block.go
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/compact_test.go
  pkg/objstore/objstore.go
  pkg/objstore/objstore_test.go
Labels: size/L, package: objstore

#5483 E2E Tests: Use default HTTP config for minio tests
  test/e2e/e2ethanos/services.go
Labels: size/S

#5364 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: size/XS

#5495 CHANGELOG.md: regenerate
  CHANGELOG.md
Labels: size/XS

#5496 Update query.md
  docs/components/query.md
Labels: size/XS

#5500 Upgrade mdox with cache and some http settings to reduce CI failures
  .bingo/Variables.mk
  .bingo/mdox.mod
  .bingo/variables.env
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .github/workflows/react.yml
  .gitignore
  .mdox.validate.yaml
Labels: size/M

#5503 Fixing Race condition Introduced by #5493
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
  pkg/tracing/tracing.go
Labels: size/M

#5506 chore: Update busybox image versions
  .busybox-versions
Labels: size/S

#5484 chore: Update Prometheus dependency
  .bingo/minio.sum
  .bingo/prometheus.1.sum
  .bingo/prometheus.2.sum
  .bingo/prometheus.sum
  CHANGELOG.md
  examples/dashboards/query-frontend.json
  go.mod
  go.sum
  mixin/dashboards/query-frontend.libsonnet
  pkg/api/query/grpc.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/query/querier_test.go
  pkg/query/test.go
  pkg/queryfrontend/config.go
  pkg/queryfrontend/request.go
  pkg/queryfrontend/response.go
  pkg/rules/manager.go
  test/e2e/query_frontend_test.go
Labels: size/L

#5516 chore: Update Go modules
  go.mod
  go.sum
  pkg/extgrpc/client.go
  pkg/query/endpointset_test.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset_test.go
  test/e2e/query_test.go
Labels: size/S

#5518 chore: Update Go modules
  go.mod
  go.sum
Labels: size/XS

#5526 Reuse upstream TSDB status structs
  pkg/api/status/v1.go
Labels: size/M

#5530 Fix proposal on website
  docs/proposals-accepted/202106-automated-per-endpoint-mTLS.md
Labels: size/XS

#5529 delete_katacoda
  katacoda.yaml
Labels: size/XS

#5537 Remove empty RuleGroups in api/v1/rules when using matchers
  pkg/rules/rules.go
  pkg/rules/rules_test.go
Labels: size/M

#5534 query: Set struct return by query api alerts same as prometheus api
  CHANGELOG.md
  pkg/api/query/v1.go
Labels: size/XS

#5533 Receiver: Add benchmark for receive writer
  pkg/receive/writer_test.go
Labels: size/M

#5415 Submit a proposal for Active Series Limiting for Hashring Topology
  docs/img/get-ref-map.png
  docs/img/meta-monitoring-validator.png
  docs/img/per-receive.png
  docs/img/receive-validator.png
  docs/proposals-accepted/202206-active-series-limiting-hashring.md
Labels: size/L

#5538 Refactor EndpointSet
  cmd/thanos/query.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
  pkg/store/labelpb/label.go
Labels: size/XL
