Repository thanos-io/thanos, pull requests merged in 2023-09, with the labels that each got.

#6688 Merge release 0.32.2 to main
  CHANGELOG.md
Labels: size/S

#6689 Ruler: Add update label names routine for stateful ruler
  cmd/thanos/rule.go
Labels: size/S

#6691 Store: add some acceptance tests for label matching
  pkg/store/acceptance_test.go
  pkg/store/bucket_test.go
  pkg/store/prometheus_test.go
  pkg/store/tsdb_test.go
Labels: size/L

#6692 Store: fix regex matching with set that matches empty
  CHANGELOG.md
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
Labels: size/L

#6694 docs: Update lightstep link
  .mdox.validate.yaml
  docs/tracing.md
Labels: size/XS

#6693 Store: add failing test for potential dedup issue
  pkg/store/bucket_test.go
Labels: size/M

#6698 Receive: Change write log level from warn to info
  CHANGELOG.md
  pkg/receive/writer.go
Labels: size/S

#6697 Store: fix block dedup
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/proxy_heap.go
Labels: size/M

#6465 Optimize postings fetching by checking postings and series size
  cmd/thanos/store.go
  docs/components/store.md
  pkg/block/block_test.go
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/header.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader.go
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
  pkg/testutil/e2eutil/prometheus.go
  test/e2e/store_gateway_test.go
Labels: size/XXL

#6598 compact: data corruption during downsapmle, test and fix.
  CHANGELOG.md
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
Labels: size/XL

#6719 use single instance of typed error and use errors.Is() for comparison
  pkg/cacheutil/async_op.go
  pkg/cacheutil/memcached_client.go
Labels: size/XS

#6308 Ruler: Add alert source template
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/rule.go
  cmd/thanos/rule_test.go
  docs/components/rule.md
Labels: size/L

#6544 Add Shipper bytes uploaded metric #6438
  CHANGELOG.md
  cmd/thanos/main_test.go
  docs/storage.md
  go.mod
  go.sum
Labels: size/S

#6722 Update objstore library to latest main
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/S

#6706 Store: store responses should always be sorted
  CHANGELOG.md
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  docs/components/query.md
  go.mod
  go.sum
  pkg/receive/multitsdb.go
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/flushable.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/proxy_heap.go
  pkg/store/proxy_heap_test.go
  pkg/store/tsdb.go
  pkg/stringset/set.go
Labels: size/XL

#6725 Add BB as an Adopte
  website/data/adopters.yml
  website/static/logos/bb.png
Labels: size/XS

#6730 Add get_all_duration and merge_duration to SG query hints
  pkg/store/bucket.go
  pkg/store/hintspb/custom.go
  pkg/store/hintspb/hints.pb.go
  pkg/store/hintspb/hints.proto
Labels: size/XS

#6726 Add absolute total download time metrics for series and chunks
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6736 Cut patch release `v0.32.3`
  .busybox-versions
  CHANGELOG.md
  VERSION
  cmd/thanos/main_test.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  docs/components/query.md
  docs/storage.md
  go.mod
  go.sum
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1.go
  pkg/dedup/chunk_iter_test.go
  pkg/query/querier_test.go
  pkg/query/remote_engine.go
  pkg/query/test_test.go
  pkg/receive/multitsdb.go
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/flushable.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/proxy_heap.go
  pkg/store/proxy_heap_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb.go
  pkg/store/tsdb_test.go
  pkg/stringset/set.go
Labels: size/XXL

#6735 fix bug when merging query stats for chunkFetchDurationSum
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6738 Merge release v0.32.3 to main
  CHANGELOG.md
  VERSION
Labels: size/S

#6746 Update objstore version to latest
  go.mod
  go.sum
Labels: size/XS

#6750 Update go alpine image to 3.18 for multistage docker build
  Dockerfile.multi-stage
Labels: size/XS

#6729 StoreGateway: Add a metric to track block load duration
  pkg/store/bucket.go
Labels: size/XS

#6741 BinaryIndexReader: always lookup name symbol first
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/header_test.go
Labels: size/L

#6749 Add latency histogram for fetching index cache
  CHANGELOG.md
  pkg/store/cache/cache.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/memcached.go
Labels: size/M

#6753 Fix for mixin workflow actions rules check step failed cases
  .bingo/Variables.mk
  .bingo/promtool.mod
  .bingo/promtool.sum
  .bingo/variables.env
  CHANGELOG.md
  examples/alerts/rules.yaml
  mixin/rules/receive.libsonnet
  mixin/rules/store.libsonnet
Labels: size/XXL
