Repository thanos-io/thanos, pull requests merged in 2023-12, with the labels that each got.

#6949 errutil: fix deadlock
  pkg/errutil/multierror.go
  pkg/errutil/multierror_test.go
Labels: size/S

#6952 update runtime/CloseWithErrCapture comment
  pkg/runutil/runutil.go
Labels: size/XS

#6944 Added a new flag for maximum retention bytes for thanos
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/S

#6950 Upgrade prometheus to latest main
  go.mod
  go.sum
  pkg/block/index.go
  pkg/block/indexheader/binary_reader.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compactv2/chunk_series_set.go
  pkg/compactv2/compactor_test.go
  pkg/httpconfig/http.go
  pkg/store/storepb/testutil/series.go
Labels: size/L

#6955 Improve filtered index cache filtering
  pkg/store/cache/filter_cache.go
Labels: size/S

#6879 store: fix misc label_value issues related to external labels
  pkg/store/acceptance_test.go
  pkg/store/prometheus.go
  pkg/store/tsdb.go
Labels: size/S

#6964 receive: fix adding fields to logger
  pkg/receive/handler.go
Labels: size/XS

#6957 Copy labels coming from remote engines
  pkg/query/remote_engine.go
Labels: size/XS

#6954 Add tracing index cache
  CHANGELOG.md
  pkg/store/cache/factory.go
  pkg/store/cache/tracing_index_cache.go
Labels: size/M

#6966 Change order of log for finished compacting blocks
  pkg/compact/compact.go
Labels: size/XS

#6971 Use registerer for gRPC opts and endpoints
  pkg/extgrpc/client.go
  pkg/query/endpointset.go
Labels: size/XS

#6974 receive: upload compacted blocks if OOO enabled
  cmd/thanos/receive.go
  pkg/receive/handler_test.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
  pkg/receive/receive_test.go
  pkg/receive/writer_test.go
Labels: size/S

#6972 Add streaming series limit at block series client
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6976 Updated the defaultChecked property in Checkbox element
  pkg/ui/react-app/src/pages/graph/Panel.tsx
Labels: size/XS

#6978 Update prometheus to d0c2d9c
  cmd/thanos/query.go
  go.mod
  go.sum
  pkg/httpconfig/http.go
  pkg/receive/handler_test.go
  pkg/rules/manager_test.go
Labels: size/L

#6986 Release 0.33
  .busybox-versions
  CHANGELOG.md
  VERSION
  website/hugo.yaml
Labels: size/S

#6992 merge release 0.33 to main
  CHANGELOG.md
  website/hugo.yaml
Labels: size/XS

#6390 rule: native histogram support
  cmd/thanos/query.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  docs/components/rule.md
  pkg/alert/config.go
  pkg/alert/config_test.go
  pkg/clientconfig/config.go
  pkg/clientconfig/config_test.go
  pkg/clientconfig/grpc.go
  pkg/clientconfig/http.go
  pkg/httpconfig/config.go
  pkg/httpconfig/config_test.go
  pkg/promclient/promclient.go
  pkg/query/remote_engine.go
  pkg/query/remote_engine_test.go
  pkg/receive/head_series_limiter.go
  pkg/receive/limiter_config.go
  pkg/rules/queryable.go
  pkg/store/prometheus.go
  pkg/store/storepb/prompb/custom.go
  scripts/cfggen/main.go
  test/e2e/compatibility_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/native_histograms_test.go
  test/e2e/rule_test.go
  test/e2e/rules_api_test.go
Labels: component: rule, size/XXL

#7001 Mdox ignore checking twitter urls
  .mdox.validate.yaml
Labels: size/XS

#7006 Updated Grofers logo
  website/.hugo_build.lock
  website/data/adopters.yml
  website/static/logos/blinkit.png
  website/static/logos/grofers.png
Labels: size/XS

#6973 TraceID : Fetching TraceID
  pkg/ui/react-app/src/pages/graph/Panel.tsx
  pkg/ui/react-app/src/pages/graph/QueryStatsView.test.tsx
  pkg/ui/react-app/src/pages/graph/QueryStatsView.tsx
  pkg/ui/react-app/src/types/types.ts
Labels: size/M

#7008 docs: add promcon 2023 thanos talks
  docs/getting-started.md
Labels: size/XS

#7000 Added website page for companies who offer consultancy and enterprise…
  .mdox.yaml
  docs/support/welcome.md
  website/data/adopters.yml
  website/layouts/_default/baseof.html
  website/layouts/partials/versioning/version-picker.html
  website/layouts/support/list.html
  website/layouts/support/single.html
  website/static/cloudraft.png
  website/static/o11y.svg
Labels: size/M

#6984 Lazy downloaded index header
  CHANGELOG.md
  cmd/thanos/store.go
  docs/components/store.md
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader.go
  pkg/block/indexheader/lazy_binary_reader_test.go
  pkg/block/indexheader/reader_pool.go
  pkg/block/indexheader/reader_pool_test.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6998 Query Frontend splitting metrics check is flaky #6951
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
Labels: size/L

#7004 query-frontend: Added support of auto_discovery for memcached
  CHANGELOG.md
  internal/cortex/chunk/cache/memcached_client.go
  pkg/queryfrontend/config.go
Labels: size/S

#7009 Rule: Fix URI encoding of strings
  CHANGELOG.md
  cmd/thanos/rule.go
  cmd/thanos/rule_test.go
Labels: size/S

#6977 Partial Response : "Use Partial Response" enabled by default
  pkg/ui/react-app/src/pages/graph/Panel.test.tsx
  pkg/ui/react-app/src/pages/graph/Panel.tsx
  pkg/ui/react-app/src/pages/graph/PanelList.tsx
Labels: size/M

#7011 Query Frontend: queries with negative offset should check whether it is cacheable or not
  CHANGELOG.md
  internal/cortex/querier/queryrange/results_cache.go
  internal/cortex/querier/queryrange/results_cache_test.go
Labels: size/M

#7015 Update MAINTAINERS.md (Bartek's company)
  MAINTAINERS.md
Labels: size/XS
