Repository thanos-io/thanos, pull requests merged in 2023-05, with the labels that each got.

#6163 receive: Make max backoff configurable
  CHANGELOG.md
  cmd/thanos/receive.go
  pkg/receive/handler.go
Labels: size/XS

#6327 Replace summary in extprom metrics with histogram
  CHANGELOG.md
  pkg/extprom/http/metrics.go
Labels: size/M

#6299 Ignore common label-values in ProxyResponseHeap sort function
  pkg/store/proxy_heap.go
  pkg/store/proxy_heap_test.go
Labels: size/L

#6330 Fix inconsistent error for series limits in Store API
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
Labels: size/L

#6332 *: remove unmaintained gzip library
  Makefile
  cmd/thanos/query_frontend.go
  go.mod
  go.sum
  pkg/api/api.go
Labels: size/S

#6306 Traces sampler env var
  CHANGELOG.md
  docs/tracing.md
  pkg/tracing/otlp/config_yaml.go
  pkg/tracing/otlp/otlp.go
  pkg/tracing/otlp/otlp_test.go
Labels: size/M

#6342 cacheutil: upgrade `rueidis` to v1.0.2
  CHANGELOG.md
  go.mod
  go.sum
  pkg/cacheutil/cacheutil_test.go
  pkg/cacheutil/redis_client.go
Labels: size/M

#6345 fix: spelling errors DoInSpanWtihErr to DoInSpanWithErr
  pkg/tracing/tracing.go
Labels: size/XS

#6329 Expose info for each TSDB
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  pkg/info/infopb/custom.pb.go
  pkg/info/infopb/rpc.pb.go
  pkg/info/infopb/rpc.proto
  pkg/query/endpointset.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go
  pkg/query/remote_engine.go
  pkg/query/remote_engine_test.go
  pkg/receive/multitsdb.go
  pkg/store/bucket.go
  pkg/store/prometheus.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/testutil/client.go
  pkg/store/tsdb.go
Labels: size/L

#6349 Bump promql-engine to fix thanos-community/promql-engine/issues/239
  go.mod
  go.sum
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1.go
  pkg/query/querier_test.go
  pkg/query/remote_engine.go
  pkg/query/test_test.go
Labels: size/L

#6358 Query: Add +Inf bucket to query duration metrics
  CHANGELOG.md
  cmd/thanos/query.go
  pkg/store/telemetry.go
  pkg/testutil/e2eutil/prometheus.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#6363 Check context when expanding postings
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/S

#6373 docs: replace --store with --endpoint
  docs/components/query.md
  docs/operating/cross-cluster-tls-communication.md
  docs/quick-tutorial.md
Labels: size/M

#6376 Optimizing "grafana generated" regex matchers
  pkg/store/bucket_test.go
  pkg/store/opts.go
  pkg/store/opts_test.go
  pkg/store/storepb/testutil/series.go
Labels: size/M

#6374 Cache: various index cache client improvements
  pkg/store/bucket.go
  pkg/store/cache/cache.go
  pkg/store/cache/cache_test.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/memcached.go
Labels: size/M

#6379 Implementing Regex optimization on the `MatchNotRegexp` and `MatchNotEqual` matcher type
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#6386 add de-cix as adopter
  website/data/adopters.yml
  website/static/logos/de-cix.png
Labels: size/XS

#6392 [chore] Updating Query Engine and Prometheus
  cmd/thanos/query.go
  go.mod
  go.sum
  pkg/api/query/v1.go
  pkg/query/remote_engine.go
  pkg/receive/multitsdb.go
Labels: size/M

#5777 Receive: Allow specifying tenant-specific external labels in RouterIngestor
  CHANGELOG.md
  cmd/thanos/receive.go
  pkg/exemplars/tsdb.go
  pkg/receive/config.go
  pkg/receive/handler_test.go
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
  pkg/receive/multitsdb.go
  pkg/receive/receive_test.go
  pkg/shipper/shipper.go
  pkg/store/tsdb.go
Labels: size/XXL

#6352 Expose store gateway query stats in series response hints
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/hintspb/custom.go
  pkg/store/hintspb/hints.pb.go
  pkg/store/hintspb/hints.proto
  pkg/store/storepb/testutil/series.go
Labels: size/L

#6369 receive: make az aware ketama hashring
  CHANGELOG.md
  docs/components/receive.md
  pkg/receive/config.go
  pkg/receive/config_test.go
  pkg/receive/handler_test.go
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
  pkg/receive/receive_test.go
  test/e2e/native_histograms_test.go
  test/e2e/receive_test.go
Labels: size/XL

#6320 Proposal: query path tenancy
  docs/img/query-path-tenancy-proposal-diagram.svg
  docs/proposals-accepted/202304-query-path-tenancy.md
Labels: size/L

#6399 Fix double-counting bug in http_request_duration metric
  CHANGELOG.md
  pkg/extprom/http/instrument_server.go
Labels: size/XS

#6377 e2e(query): Reproduce dedup issue from #6257
  go.mod
  go.sum
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
Labels: size/XL
