Repository thanos-io/thanos, pull requests merged in 2023-04, with the labels that each got.

#6244 mixin(Rule): Add rule evaluation failures to the Rule dashboard
  CHANGELOG.md
  examples/dashboards/rule.json
  mixin/dashboards/rule.libsonnet
Labels: size/L

#6245 store/bucket: snappy-encoded postings reading improvements
  pkg/store/bucket.go
  pkg/store/postings_codec.go
  pkg/store/postings_codec_test.go
Labels: size/M

#6272 Update mentorship links
  docs/contributing/mentorship.md
Labels: size/XS

#6271 Fix segfault in LabelValues during head compaction
  CHANGELOG.md
  pkg/receive/multitsdb_test.go
  pkg/store/tsdb.go
Labels: size/L

#6275 Add Deno as adopter
  website/data/adopters.yml
  website/static/logos/deno.png
Labels: size/XS

#6276 Bump `make test` timeout due to CI reaching it
  Makefile
Labels: size/XS

#6282 docs: mismatch in changelog
  CHANGELOG.md
Labels: size/XS

#6287 Upgrade prometheus to 7309ac272195cb856b879306d6a27af7641d3346
  go.mod
  go.sum
  internal/cortex/util/metrics_helper.go
  pkg/alert/alert.go
  pkg/api/query/grpc.go
  pkg/api/query/v1_test.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/dedup/chunk_iter_test.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/promclient/promclient.go
  pkg/query/querier_test.go
  pkg/query/remote_engine.go
  pkg/query/test_test.go
  pkg/rules/manager_test.go
  pkg/store/storepb/prompb/samples.go
Labels: size/L

#6294 Add CarTrade Tech as new adopter
  website/data/adopters.yml
  website/static/logos/cartradetech.png
Labels: size/XS

#6310 tests: Remove custom Between test matcher
  go.mod
  go.sum
  test/e2e/compact_test.go
  test/e2e/e2ethanos/custom_test_matchers.go
Labels: size/S

#6303 store: add streamed snappy encoding for postings list
  CHANGELOG.md
  pkg/extgrpc/snappy/snappy.go
  pkg/store/bucket.go
  pkg/store/postings_codec.go
  pkg/store/postings_codec_test.go
Labels: size/L

#6319 compact: atomically replace no compact marked map
  pkg/compact/compact.go
  pkg/compact/compact_test.go
Labels: size/M

#6324 Fix broken Jaeger exporter specification link
  docs/tracing.md
Labels: size/XS
