Repository thanos-io/thanos, pull requests merged in 2023-06, with the labels that each got.

#6408 Fix series stats merge
  pkg/store/hintspb/custom.go
  pkg/store/hintspb/custom_test.go
Labels: size/M

#6406 Receive: allow unlimited head_series_limit tenants
  CHANGELOG.md
  docs/components/receive.md
  pkg/receive/head_series_limiter.go
  test/e2e/e2ethanos/services.go
  test/e2e/receive_test.go
Labels: size/M

#6418 Add `@douglascamata` to triagers
  MAINTAINERS.md
Labels: size/XS

#6411 Add Blog
  docs/blog/2023-06-02-lfx-mentorship-query-observability.md
  docs/blog/img/engine-1.png
  docs/blog/img/engine-2.png
  docs/blog/img/giedrius-sketch.png
  docs/blog/img/tree-1.png
  docs/blog/img/tree-2.png
  docs/blog/img/tree-3.png
Labels: size/M

#6422 blog: Fix images for LFX post
  docs/blog/2023-06-02-lfx-mentorship-query-observability.md
Labels: size/S

#6405 Index Cache: Change cache key for postings
  CHANGELOG.md
  pkg/store/cache/cache.go
  pkg/store/cache/cache_test.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/memcached.go
Labels: size/M

#6427 Receive: upgrading logs for failed uploads to error
  CHANGELOG.md
  cmd/thanos/receive.go
Labels: size/XS

#6429 Fix postings test
  pkg/store/bucket_test.go
Labels: size/XS

#6430 Add aiven as adopter... more soon!
  website/data/adopters.yml
  website/static/logos/aivenlogo.png
Labels: size/XS

#6428 Report gRPC connnection errors to the caller
  CHANGELOG.md
  pkg/query/endpointset.go
Labels: size/XS

#6432 chore: remove duplicated `gopkg.in/fsnotify.v1` dep
  CHANGELOG.md
  go.mod
  go.sum
  pkg/receive/config.go
Labels: size/XS

#6426 Expose estimated chunk and series size as configurable options
  cmd/thanos/store.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6437 Receive: make tsdb stats limit configurable
  CHANGELOG.md
  docs/components/receive.md
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/M

#6420 index cache: Cache expanded postings
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/cache/cache.go
  pkg/store/cache/cache_test.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/inmemory_test.go
  pkg/store/cache/memcached.go
  pkg/store/cache/memcached_test.go
  test/e2e/compact_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/info_api_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
Labels: size/XL

#6424 index stats: fix chunk size calculation
  pkg/block/index.go
Labels: size/XS

#6440 Remove some unused Cortex vendored code and metrics
  internal/cortex/chunk/cache/fifo_cache.go
  internal/cortex/chunk/cache/memcached_client.go
  internal/cortex/chunk/cache/redis_cache.go
  internal/cortex/cortexpb/compat.go
  internal/cortex/cortexpb/cortex.pb.go
  internal/cortex/cortexpb/timeseries.go
  internal/cortex/querier/queryrange/results_cache.go
  internal/cortex/util/flagext/deprecated.go
  internal/cortex/util/flagext/register.go
  internal/cortex/util/log/experimental.go
  internal/cortex/util/log/log.go
Labels: size/L

#6443 Avoid direct cortex vendor dependency in promclient
  pkg/promclient/promclient.go
  test/e2e/query_test.go
Labels: size/M

#6351 query.md: Added grpc_{client,server}_handled_total to metrics list
  docs/components/query.md
Labels: component: website/docs, component: query, size/XS

#6442 store: read postings directly into diffvarint format
  .bingo/promdoc.sum
  pkg/store/bucket.go
  pkg/store/postings.go
  pkg/store/postings_codec.go
Labels: size/L

#6441 compact: Add Index Stats to block metadata
  CHANGELOG.md
  cmd/thanos/downsample.go
  pkg/block/block_test.go
  pkg/block/metadata/meta.go
  pkg/block/metadata/meta_test.go
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
Labels: size/L

#6449 Estimate block chunk and series size from metadata
  cmd/thanos/store.go
Labels: size/S

#6049 Compact: Replace group with resolution in compact metrics.
  CHANGELOG.md
  examples/dashboards/compact.json
  examples/dashboards/overview.json
  mixin/dashboards/compact.libsonnet
  pkg/block/metadata/meta.go
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/compact_test.go
Labels: size/L

#6456 Store: fix crash on empty regex matcher
  CHANGELOG.md
  pkg/store/opts.go
  pkg/store/opts_test.go
Labels: size/XS

#6450 Website: Fix blog images width
  docs/blog/2023-06-02-lfx-mentorship-query-observability.md
  website/static/main.css
Labels: size/S

#6458 Cache calculated mint and maxt for each remote engine
  pkg/query/remote_engine.go
Labels: size/M

#6464 Cache expanded postings when there is an empty posting group
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#6467 receive/mixin: add alert for tenant reaching head series limit
  CHANGELOG.md
  examples/alerts/alerts.md
  examples/alerts/alerts.yaml
  mixin/alerts/receive.libsonnet
  mixin/runbook.md
  pkg/rules/rules_test.go
Labels: size/M

#6447 go.mod: bump rest of otel libs
  go.mod
  go.sum
  pkg/tracing/otlp/otlp.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#6473 store: disable pooling for postings benchmarks
  pkg/store/postings_codec.go
  pkg/store/postings_codec_test.go
Labels: size/M

#6461 New blog about Thanos adoption at Aiven
  docs/blog/2023-06-08-thanos-at-aiven.md
  docs/blog/img/aiven-thanos-architecture.png
  docs/blog/img/thanosvsm3perf.png
Labels: size/M

#6476 Fixing date and author for Aiven blog
  docs/blog/2023-06-08-thanos-at-aiven.md
Labels: size/XS

#6471 Check context when expanding postings 2nd attempt
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#6477 [FEAT] Add thanos ruler blog post
  docs/getting-started.md
Labels: size/XS

#6479 Rename series and postings fetch duration metrics
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/XS

#6485 go.mod: update rueidis client
  go.mod
  go.sum
Labels: size/XS

#6482 Introduce tenancy package
  cmd/thanos/receive.go
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/writer_test.go
  pkg/tenancy/tenancy.go
Labels: size/L
