Repository thanos-io/thanos, pull requests merged in 2023-03, with the labels that each got.

#6157 Remove global lock when pruning tenants
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/M

#6168 receive: fail early if ketama hashring is configured with number of nodes lower than the replication factor
  CHANGELOG.md
  pkg/receive/handler_test.go
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
Labels: size/M

#6172 Handle query parsing errors on QFE range split middleware
  CHANGELOG.md
  internal/cortex/querier/queryrange/split_by_interval.go
  pkg/queryfrontend/split_by_interval_test.go
Labels: size/S

#6126 Build with Go 1.20
  .bingo/Variables.mk
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  .circleci/config.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/container-version.yaml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .github/workflows/mixin.yaml
  .github/workflows/react.yml
  .go-version
  .promu.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile.multi-stage
  docs/contributing/coding-style-guide.md
  go.mod
  go.sum
  pkg/block/block_test.go
  pkg/testutil/e2eutil/prometheus.go
Labels: size/L

#6185 [tracing] tracing in OTLP support configuring service_name
  CHANGELOG.md
  docs/tracing.md
  pkg/tracing/otlp/config_yaml.go
  pkg/tracing/otlp/otlp.go
  pkg/tracing/otlp/otlp_test.go
Labels: size/S

#6189 rule: fix panic when calling API /api/v1/rules?type=alert
  pkg/rules/manager.go
Labels: size/XS

#6192 store: add flag to select the label to use as timeline title in web UI
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/store.go
  cmd/thanos/tools_bucket.go
  docs/components/compact.md
  docs/components/store.md
  docs/components/tools.md
Labels: size/S

#6178 Relay histograms from the gRPC Query API
  pkg/api/query/grpc.go
  pkg/query/remote_engine.go
  pkg/receive/writer.go
  pkg/store/storepb/custom.go
  pkg/store/storepb/prompb/samples.go
Labels: size/L

#6187 Unify gRPC flags for all servers
  cmd/thanos/config.go
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  docs/components/query.md
  docs/components/receive.md
  docs/components/rule.md
  docs/components/sidecar.md
  docs/components/store.md
  pkg/extkingpin/flags.go
Labels: size/L

#6193 e2e/store: fix flaky limits test
  test/e2e/store_gateway_test.go
Labels: size/S

#6197 Exemplar OTel: Fix exemplar for otel to use traceId instead of spanId and sample only if trace is sampled
  CHANGELOG.md
  pkg/extprom/http/instrument_server.go
Labels: size/XS

#6203 Copy chunk bytes in TSDB store before sending to client
  CHANGELOG.md
  pkg/store/tsdb.go
Labels: size/XS

#6210 Prepare 0.31.0-rc.1
  CHANGELOG.md
  VERSION
Labels: size/S

#6212 Disable scalar for vertical sharding
  CHANGELOG.md
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
Labels: size/XS

#6213 Reduce label values hash op
  pkg/store/cache/memcached.go
  pkg/store/cache/memcached_test.go
Labels: size/M

#6214 Reduce usage of fmt.Sprintf in cachekey string
  pkg/store/cache/cachekey/cachekey.go
Labels: size/XS

#6180 cache: detach Set operations from given context
  pkg/cache/cache.go
  pkg/cache/groupcache.go
  pkg/cache/inmemory.go
  pkg/cache/inmemory_test.go
  pkg/cache/memcached.go
  pkg/cache/memcached_test.go
  pkg/cache/redis.go
  pkg/cache/redis_test.go
  pkg/cache/tracing_cache.go
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/memcached_client_test.go
  pkg/cacheutil/redis_client.go
  pkg/cacheutil/redis_client_test.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/cache/cache.go
  pkg/store/cache/caching_bucket.go
  pkg/store/cache/caching_bucket_test.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/inmemory_test.go
  pkg/store/cache/memcached.go
  pkg/store/cache/memcached_test.go
  test/e2e/store_gateway_test.go
Labels: size/L

#6207 Remove tenant shipper after prunning
  CHANGELOG.md
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/M

#6107 feat: Use non root user as default user in container image
  CHANGELOG.md
  Dockerfile
  Dockerfile.multi-arch
  Dockerfile.multi-stage
Labels: size/S

#6225 Add support for vector and scalar types in gRPC query range
  pkg/api/query/grpc.go
  pkg/store/storepb/prompb/samples.go
Labels: size/M

#6228 Proxy: Only generate debug messages in debug mode
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/receive.go
  pkg/store/proxy.go
Labels: size/M

#6236 Prepare release 0.31.0
  .busybox-versions
  CHANGELOG.md
  VERSION
Labels: size/S

#6216 Enable and disable the examplers storage with flag
  CHANGELOG.md
  cmd/thanos/receive.go
Labels: size/XS

#6240 Merge 0.31
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
  pkg/store/tsdb.go
Labels: size/M

#6233 Tutorial grammar/capitalization fixes and improved readability
  docs/quick-tutorial.md
Labels: size/L

#6241 Fix 0.31 CHANGELOG
  CHANGELOG.md
Labels: size/S

#6232 Update dev container and add Codespaces docs
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/welcome-message.txt
  .gitignore
  CONTRIBUTING.md
  README.md
  scripts/quickstart.sh
Labels: size/L

#6242 *: Bump Go and git-shallow-clone orbs
  .circleci/config.yml
Labels: size/XS

#6222 mixin(Receive): Fix tenant series received charts
  CHANGELOG.md
  examples/dashboards/receive.json
  mixin/dashboards/receive.libsonnet
Labels: size/S

#6243 Revert grpc-server-max-connection-age default value
  cmd/thanos/config.go
  docs/components/query.md
  docs/components/receive.md
  docs/components/rule.md
  docs/components/sidecar.md
  docs/components/store.md
Labels: size/S

#6064 Compact: fix objstore bucket operations check to improve flakiness
  test/e2e/compact_test.go
  test/e2e/e2ethanos/custom_test_matchers.go
Labels: size/S

#6231 mixins: Add code/grpc-code dimension to error widgets
  CHANGELOG.md
  examples/dashboards/overview.json
  examples/dashboards/query-frontend.json
  examples/dashboards/query.json
  examples/dashboards/receive.json
  examples/dashboards/rule.json
  examples/dashboards/sidecar.json
  examples/dashboards/store.json
  mixin/lib/thanos-grafana-builder/builder.libsonnet
  mixin/lib/thanos-grafana-builder/grpc.libsonnet
  mixin/lib/thanos-grafana-builder/http.libsonnet
Labels: size/M
