Repository thanos-io/thanos, pull requests merged in 2023-08, with the labels that each got.

#6574 Replicate flags for min and max compaction level
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
Labels: size/M

#6548 Upgrade objstore
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/M

#6578 fix data race of chunk reader stats
  pkg/store/bucket.go
Labels: size/S

#6575 store/bucket: fix data race
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6581 store/bucket: fix bytes limiter data race
  pkg/store/bucket.go
Labels: size/XS

#6591 extprom: fix test
  go.mod
  pkg/extprom/tx_gauge_test.go
Labels: size/L

#6586 Fix data downloaded size sum race when loading chunks
  pkg/store/bucket.go
Labels: size/XS

#6589 go.mod: update Redis client
  go.mod
  go.sum
Labels: size/S

#6593 Add metric to track number of chunk refetches
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/XS

#6592 Fix vertical sharding bug in without and union operations
  CHANGELOG.md
  pkg/querysharding/analysis.go
  pkg/querysharding/analyzer_test.go
Labels: size/M

#6599 query/endpointset: fix races
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
Labels: size/M

#6317 Resort store response set on internal label dedup
  cmd/thanos/receive.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  go.mod
  go.sum
  pkg/receive/multitsdb.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/flushable.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb.go
  pkg/stringset/set.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
Labels: size/XL

#6602 store: properly handle snappy compression continuations
  pkg/store/6545postingsrepro
  pkg/store/postings_codec.go
  pkg/store/postings_codec_test.go
Labels: size/L

#6607 components/query: add a paragraph about filter
  docs/components/query.md
  docs/proposals-accepted/20221129-avoid-global-sort.md
Labels: size/S

#6603 cache: remove unnecessary nil check
  pkg/cache/caching_bucket_config.go
Labels: size/M

#6609 Bump go4.org/intern to fix build on go1.21
  go.mod
  go.sum
Labels: size/S

#6618 Update objstore and promql-engine to latest
  go.mod
  go.sum
Labels: size/S

#6582 store/bucket: wait until chunk loading ends in Close()
  pkg/store/bucket.go
Labels: size/S

#6617 CHANGELOG: Mark v0.32 as in progress
  CHANGELOG.md
  VERSION
Labels: size/M

#6620 Cut release candidate `v0.32.0-rc.0`
  CHANGELOG.md
  VERSION
Labels: size/XS

#6605 Vertical shard binary expression using metric name when no matching label
  CHANGELOG.md
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
Labels: size/M

#6612 store: fix missing flush when handling pushed down queries
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/testutil/e2eutil/prometheus.go
Labels: size/M

#6619 Handle warnings from remote engines
  pkg/query/remote_engine.go
  pkg/query/remote_engine_test.go
Labels: size/M

#6628 Bug fix in quickstart
  scripts/quickstart.sh
Labels: size/XS

#6630 Cut release candidate `v0.32.0-rc.1`
  CHANGELOG.md
  VERSION
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/testutil/e2eutil/prometheus.go
Labels: size/M

#6633 queryfrontend: fix explanation with query_range
  internal/cortex/querier/queryrange/results_cache.go
  pkg/queryfrontend/queryinstant_codec.go
  test/e2e/query_frontend_test.go
Labels: size/S

#6634 Cut final release for `v0.32.0`
  CHANGELOG.md
  VERSION
  internal/cortex/querier/queryrange/results_cache.go
  pkg/queryfrontend/queryinstant_codec.go
  test/e2e/query_frontend_test.go
Labels: size/M

#6638 Merge release 0.32 to main
  CHANGELOG.md
  docs/release-process.md
Labels: size/XS

#6640 [changelog] Add a breaking warning for #6107
  CHANGELOG.md
Labels: size/XS

#6650 store: fix error handling in decodePostings
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/S

#6654 Store: fix ignored error in postings
  pkg/store/postings.go
Labels: size/XS

#6655 Store: fix bufio pool handling
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/XS

#6646 Add `--disable-admin-operations` flag in Compactor UI and Bucket UI
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/tools_bucket.go
  docs/components/compact.md
  docs/components/tools.md
  pkg/api/blocks/v1.go
  pkg/ui/react-app/src/thanos/pages/blocks/BlockDetails.test.tsx
  pkg/ui/react-app/src/thanos/pages/blocks/BlockDetails.tsx
  pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
Labels: size/L

#6669 Fix mutable stringset memory usage
  pkg/store/bucket_e2e_test.go
  pkg/stringset/set.go
Labels: size/S

#6670 Cut patch release `v0.32.1`
  CHANGELOG.md
  VERSION
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/postings.go
  pkg/stringset/set.go
Labels: size/M

#6664 Update thanos engine and Prometheus dependencies
  CHANGELOG.md
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  go.mod
  go.sum
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1.go
  pkg/dedup/chunk_iter_test.go
  pkg/query/querier_test.go
  pkg/query/remote_engine.go
  pkg/query/test_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb_test.go
Labels: size/L

#6673 Merge release 0.32.1 to main
  CHANGELOG.md
Labels: size/S

#6675 store: fix race when iterating blocks
  pkg/store/bucket.go
Labels: size/XS

#6615 Build with Go 1.21
  .bingo/Variables.mk
  .bingo/bingo.mod
  .bingo/bingo.sum
  .bingo/goimports.mod
  .bingo/goimports.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/shfmt.mod
  .bingo/shfmt.sum
  .bingo/variables.env
  .circleci/config.yml
  .devcontainer/Dockerfile
  .github/workflows/codeql-analysis.yml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .github/workflows/mixin.yaml
  .go-version
  .promu.yml
  CONTRIBUTING.md
  Dockerfile.multi-stage
Labels: size/L

#6679 store: Record stats even on ExpandPostings error
  pkg/store/bucket.go
Labels: size/S

#6681 Store: fix forgotten field in store stats merge
  pkg/store/bucket.go
Labels: size/XS

#6684 Store: fix postings reader short reads
  pkg/store/bucket.go
  pkg/store/postings.go
Labels: size/XS

#6685 Cut patch release `v0.32.2`
  CHANGELOG.md
  VERSION
  pkg/store/bucket.go
  pkg/store/postings.go
Labels: size/M
