Repository thanos-io/thanos, pull requests merged in 2023-01, with the labels that each got.

#6009 fix duplicate metrics registration in redis client
  pkg/cacheutil/cacheutil_test.go
  pkg/cacheutil/redis_client.go
  pkg/cacheutil/redis_client_test.go
Labels: size/S

#5990 cacheutil: add support for Redis Sentinel
  CHANGELOG.md
  docs/components/query-frontend.md
  docs/components/store.md
  pkg/cacheutil/redis_client.go
  pkg/queryfrontend/config.go
Labels: size/S

#6011 Cut 0.30.0
  CHANGELOG.md
  VERSION
  docs/release-process.md
Labels: size/XS

#5995 Sidecar: Loads the TLS certificate during startup.
  CHANGELOG.md
  pkg/tls/options.go
  test/e2e/tls_test.go
Labels: size/M

#6008 Add counter metric to gate
  CHANGELOG.md
  pkg/gate/gate.go
Labels: size/M

#6017 *: cut 0.30.1
  CHANGELOG.md
  VERSION
  pkg/cacheutil/cacheutil_test.go
  pkg/cacheutil/redis_client.go
  pkg/cacheutil/redis_client_test.go
Labels: size/M

#6022 Fixes .gitignore to only ignore data folder on root
  .gitignore
Labels: size/XS

#6012 Add proposal for distributed execution
  docs/img/distributed-execution-proposal-1.png
  docs/img/distributed-execution-proposal-2.png
  docs/img/distributed-execution-proposal-3.png
  docs/img/distributed-execution-proposal-4.png
  docs/img/distributed-execution-proposal-5.png
  docs/proposals-accepted/202301-distributed-query-execution.md
Labels: size/L

#6034 remove vendored cortex chunk code
  internal/cortex/chunk/cache/background_test.go
  internal/cortex/chunk/cache/cache_test.go
  internal/cortex/chunk/chunk.go
  internal/cortex/chunk/chunk_test.go
  internal/cortex/chunk/encoding/bigchunk.go
  internal/cortex/chunk/encoding/bigchunk_test.go
  internal/cortex/chunk/encoding/chunk.go
  internal/cortex/chunk/encoding/chunk_test.go
  internal/cortex/chunk/encoding/delta_helpers.go
  internal/cortex/chunk/encoding/doubledelta.go
  internal/cortex/chunk/encoding/factory.go
  internal/cortex/chunk/encoding/instrumentation.go
  internal/cortex/chunk/encoding/prometheus_chunk.go
  internal/cortex/chunk/encoding/varbit.go
  internal/cortex/chunk/encoding/varbit_helpers.go
  internal/cortex/chunk/encoding/varbit_test.go
  internal/cortex/chunk/fixtures.go
  internal/cortex/chunk/schema_config.go
  internal/cortex/chunk/tags.go
  internal/cortex/querier/queryrange/queryable.go
  internal/cortex/querier/queryrange/queryable_test.go
  internal/cortex/querier/queryrange/querysharding.go
  internal/cortex/querier/queryrange/querysharding_test.go
  internal/cortex/querier/queryrange/roundtrip.go
  internal/cortex/querier/queryrange/roundtrip_test.go
Labels: size/XXL

#6042 Ashwinsrinivasmurthy patch 1
  website/data/adopters.yml
  website/static/logos/arlo.png
Labels: size/XS

#6035 support other type of matchers in replicate
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
  pkg/replicate/replicator.go
Labels: size/L

#6044 mark ErrTooOldSample as SampleConflict error
  CHANGELOG.md
  pkg/receive/handler.go
  pkg/receive/handler_test.go
Labels: size/S

#6010 Upgrade Prometheus to v0.41.0
  CHANGELOG.md
  go.mod
  go.sum
  pkg/block/indexheader/binary_reader.go
  pkg/receive/handler_test.go
  pkg/receive/writer.go
  pkg/receive/writer_test.go
Labels: size/L

#6045 remove unused cortex vendor files
  internal/cortex/ingester/client/compat.go
  internal/cortex/ingester/client/compat_test.go
  internal/cortex/ingester/client/fnv.go
  internal/cortex/ingester/client/ingester.pb.go
  internal/cortex/ingester/client/ingester.proto
  internal/cortex/prom1/storage/metric/metric.go
  internal/cortex/prom1/storage/metric/metric_test.go
  internal/cortex/prom1/storage/metric/sample.go
  internal/cortex/querier/astmapper/astmapper.go
  internal/cortex/querier/astmapper/astmapper_test.go
  internal/cortex/querier/astmapper/embedded.go
  internal/cortex/querier/astmapper/parallel.go
  internal/cortex/querier/astmapper/parallel_test.go
  internal/cortex/querier/astmapper/shard_summer.go
  internal/cortex/querier/astmapper/subtree_folder.go
  internal/cortex/querier/lazyquery/lazyquery.go
  internal/cortex/querier/querier.go
  internal/cortex/querier/queryrange/promql_test.go
  internal/cortex/querier/queryrange/series_test.go
  internal/cortex/querier/queryrange/test_utils.go
  internal/cortex/querier/queryrange/test_utils_test.go
  internal/cortex/querier/queryrange/value.go
  internal/cortex/querier/queryrange/value_test.go
  internal/cortex/querier/series/series_set.go
  internal/cortex/querier/store_gateway_client.go
  internal/cortex/storegateway/storegatewaypb/gateway.pb.go
  internal/cortex/storegateway/storegatewaypb/gateway.proto
  internal/cortex/tenant/resolver.go
  internal/cortex/tenant/resolver_test.go
  internal/cortex/tenant/tenant.go
  internal/cortex/tenant/tenant_test.go
Labels: size/XXL

#6041 Merge release 0.30 into main
  CHANGELOG.md
  cmd/thanos/compact.go
  docs/release-process.md
  pkg/tracing/jaeger/config_yaml.go
  pkg/tracing/jaeger/jaeger_test.go
Labels: size/L

#6055 Use `e2edb.NewMinio` to disable SSE-S3 in e2e tests
  go.mod
  go.sum
  test/e2e/compact_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/info_api_test.go
  test/e2e/query_test.go
  test/e2e/rules_api_test.go
  test/e2e/store_gateway_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/L

#6053 gate: allow disabling max concurrent
  pkg/gate/gate.go
  pkg/gate/gate_test.go
Labels: size/S

#6052 Use $__rate_inteval in Thanos mixin dashboards
  examples/dashboards/bucket-replicate.json
  examples/dashboards/compact.json
  examples/dashboards/overview.json
  examples/dashboards/query-frontend.json
  examples/dashboards/receive.json
  examples/dashboards/rule.json
  examples/dashboards/sidecar.json
  examples/dashboards/store.json
  mixin/dashboards/bucket-replicate.libsonnet
  mixin/dashboards/compact.libsonnet
  mixin/dashboards/query-frontend.libsonnet
  mixin/dashboards/receive.libsonnet
  mixin/dashboards/rule.libsonnet
  mixin/dashboards/sidecar.libsonnet
  mixin/dashboards/store.libsonnet
Labels: size/L

#6057 Add proposal for Querier selector config
  docs/img/distributed-execution-proposal-6.png
  docs/proposals-accepted/202301-distributed-query-execution.md
Labels: size/M

#6066 tracing: fixed panic because of nil sampler
  CHANGELOG.md
  pkg/tracing/jaeger/config_yaml.go
Labels: size/XS

#6067 Fix Receiver panic when querying uninitialized TSDBs
  CHANGELOG.md
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/M

#6032 sidecar, query, receiver: Native histogram support
  cmd/thanos/receive.go
  go.mod
  go.sum
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/dedup/pushdown_iter.go
  pkg/query/iter.go
  pkg/receive/writer.go
  pkg/receive/writer_test.go
  pkg/store/storepb/custom.go
  pkg/store/storepb/prompb/types.pb.go
  pkg/store/storepb/prompb/types.proto
  pkg/store/storepb/types.pb.go
  pkg/store/storepb/types.proto
  test/e2e/e2ethanos/services.go
  test/e2e/native_histograms_test.go
Labels: size/XL

#6069 Update Thanos engine to latest version
  go.mod
  go.sum
Labels: size/S

#5720 Receive: Tenants' external labels proposal
  docs/proposals-accepted/202209-receive-tenant-external-labels.md
Labels: size/M

#6072 Fixing doc CI
  docs/proposals-accepted/202209-receive-tenant-external-labels.md
Labels: size/XS

#6050 Store: Make bucket store initial sync more robust
  CHANGELOG.md
  cmd/thanos/store.go
Labels: size/S

#6077 Recover from panics in Series calls
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  pkg/receive/multitsdb.go
  pkg/store/proxy.go
  pkg/store/recover.go
  pkg/store/recover_test.go
  pkg/store/storepb/inprocess.go
Labels: size/L

#6079 query: reuse our own gate
  pkg/query/querier.go
Labels: size/XS

#5773 Store: Support disable cache index header file.
  CHANGELOG.md
  cmd/thanos/store.go
  docs/components/store.md
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader.go
  pkg/store/bucket.go
  test/e2e/store_gateway_test.go
Labels: size/XL

#5969 CVE: Fix Receiver malicious tenant
  pkg/receive/handler.go
  pkg/receive/handler_test.go
Labels: size/M

#6081 Cut 0.30.2
  .busybox-versions
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
  pkg/tracing/jaeger/config_yaml.go
  test/e2e/compact_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/info_api_test.go
  test/e2e/query_test.go
  test/e2e/rules_api_test.go
  test/e2e/store_gateway_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/L

#6084 Add Grupo MasMovil as adopter
  website/data/adopters.yml
  website/static/logos/gmasmovil.png
Labels: size/XS

#6087 Update typo from `delete-mark.json` to `deletion-mark.json`
  docs/storage.md
Labels: size/XS

#6076 optimize selector to string
  pkg/replicate/scheme.go
Labels: size/S

#6086 Fix: Failure to close BlockSeriesClient cause store-gateway deadlock
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
Labels: size/S

#6089 cherry pick store gateway fix to release 0.30
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
Labels: size/S
