Repository thanos-io/thanos, pull requests merged in 2023-07, with the labels that each got.

#6489 Ignore nginx.com links in mdox
  .mdox.validate.yaml
Labels: size/XS

#6487 blog: Update Aiven blog post
  docs/blog/2023-06-08-thanos-at-aiven.md
Labels: size/L

#6475 store: optimized snappy streamed reading
  pkg/pool/pool.go
  pkg/store/postings_codec.go
  pkg/store/postings_codec_test.go
Labels: size/L

#6493 e2e/store: use now instead of time.Now() each time
  test/e2e/store_gateway_test.go
Labels: size/XS

#6494 [FIX] Documentation issue #6492
  docs/quick-tutorial.md
Labels: size/XS

#6499 chore: pkg imported more than once
  pkg/queryfrontend/queryinstant_codec.go
  test/e2e/compatibility_test.go
Labels: size/S

#6496 *: Remove unnecessary configuration reload from `ContentPathReloader` and improve its tests
  CHANGELOG.md
  pkg/extkingpin/path_content_reloader.go
  pkg/extkingpin/path_content_reloader_test.go
Labels: size/S

#6503 *: Change the engine behind `ContentPathReloader` to be completely independent of any filesystem concept.
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/proposals-done/202005-query-logging.md
  pkg/extkingpin/path_content_reloader.go
  pkg/extkingpin/path_content_reloader_test.go
  pkg/receive/handler_test.go
  pkg/receive/limiter.go
  pkg/receive/limiter_test.go
Labels: bugfix, component: receive, size/L

#6323 receive: add float histogram support
  pkg/query/iter.go
  pkg/query/remote_engine.go
  pkg/receive/writer.go
  pkg/receive/writer_test.go
  pkg/store/storepb/prompb/custom.go
  pkg/store/storepb/prompb/samples.go
  pkg/store/storepb/prompb/types.pb.go
  pkg/store/storepb/prompb/types.proto
  pkg/store/storepb/types.pb.go
  pkg/store/storepb/types.proto
  test/e2e/native_histograms_test.go
Labels: component: receive, size/L

#6518 Add changelog for #6474
  CHANGELOG.md
Labels: size/XS

#6520 cortex/redisclient: use rueidis client
  CHANGELOG.md
  docs/components/query-frontend.md
  docs/components/store.md
  go.mod
  go.sum
  internal/cortex/chunk/cache/cache.go
  internal/cortex/chunk/cache/redis_cache_test.go
  internal/cortex/chunk/cache/redis_client.go
  internal/cortex/chunk/cache/redis_client_test.go
  pkg/cacheutil/redis_client.go
  pkg/queryfrontend/config.go
Labels: size/L

#6509 index header: Remove memWriter from fileWriter
  CHANGELOG.md
  pkg/block/indexheader/binary_reader.go
Labels: size/M

#6152 Wrap object store Prometheus registry
  .circleci/config.yml
  Makefile
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  cmd/thanos/tools_bucket.go
  go.mod
  go.sum
  pkg/block/block_test.go
  pkg/shipper/shipper_e2e_test.go
Labels: component: store, size/M

#6522 e2e/store: try to fix Series() limit test again
  .circleci/config.yml
  docs/storage.md
  pkg/replicate/replicator.go
  test/e2e/store_gateway_test.go
Labels: size/S

#6519 pkg/reloader: use watchInterval timeout for initial apply
  CHANGELOG.md
  pkg/reloader/reloader.go
Labels: size/XS

#6523 Standardize index cache metrics
  cmd/thanos/store.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/cache/cache.go
  pkg/store/cache/factory.go
  pkg/store/cache/factory_test.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/inmemory_test.go
  pkg/store/cache/memcached.go
  pkg/store/cache/memcached_test.go
Labels: size/L

#6507 Upgrade objstore
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  cmd/thanos/tools_bucket.go
  go.mod
  go.sum
  pkg/block/block_test.go
  pkg/replicate/replicator.go
  pkg/shipper/shipper_e2e_test.go
  pkg/verifier/verify.go
Labels: size/L

#5964 Make compact lifecycle more flexible to be overridden for sharded compaction
  pkg/block/fetcher.go
  pkg/block/metadata/meta.go
  pkg/block/metadata/meta_test.go
  pkg/compact/compact.go
  pkg/compact/planner.go
  pkg/compact/planner_test.go
Labels: size/L

#6531 BucketedBytes to buffer byte slices when decoding postings from cache
  pkg/store/postings_codec.go
Labels: size/S

#6526 Shipper: change upload compacted type from bool to a function
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  pkg/receive/multitsdb.go
  pkg/shipper/shipper.go
  pkg/shipper/shipper_e2e_test.go
  pkg/shipper/shipper_test.go
Labels: size/M

#6530 Query: Forward tenant information via StoreAPI
  cmd/thanos/query.go
  cmd/thanos/receive.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/query/querier.go
  pkg/receive/handler.go
  pkg/store/bucket.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/testutil/store_series_client.go
  pkg/tenancy/tenancy.go
  pkg/tenancy/tenancy_test.go
Labels: size/L

#6552 Remove tenant header logs in store gateway
  pkg/store/bucket.go
  pkg/store/proxy.go
  pkg/tenancy/tenancy.go
  pkg/tenancy/tenancy_test.go
Labels: size/M

#6564 store/prometheus: ensure sidecar respects ext labels
  pkg/store/prometheus.go
  test/e2e/query_test.go
Labels: size/M

#6560 Add flag to optionally disable adding Thanos params when querying metrics
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/rule.go
  pkg/promclient/promclient.go
Labels: size/M

#6567 test/e2e: do not share chromedp allocators
  test/e2e/query_test.go
Labels: size/S

#6571 Remove lift
  .lift/config.toml
  .muse/config.toml
Labels: size/XS

#6566 cacheutil: move redis SetAsync() out into worker architecture
  docs/components/query-frontend.md
  docs/components/store.md
  pkg/cacheutil/async_op.go
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/redis_client.go
  pkg/cacheutil/redis_client_test.go
  test/e2e/store_gateway_test.go
Labels: size/L

#6570 Extend posting histogram metrics bucket
  pkg/store/bucket.go
  pkg/store/cache/cache.go
Labels: size/XS
