Repository thanos-io/thanos, pull requests merged in 2023-02, with the labels that each got.

#6093 docs: improving the description for tsdb.retention on the receiver
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/XS

#5926 Receiver: Use `intern` package when reallocating label strings
  CHANGELOG.md
  cmd/thanos/receive.go
  go.mod
  go.sum
  pkg/receive/handler_test.go
  pkg/receive/writer.go
  pkg/receive/writer_test.go
  pkg/store/labelpb/label.go
  pkg/store/labelpb/label_test.go
Labels: size/L

#6078 Updaing README with drawing fixes and minor wording clarification
  README.md
  docs/quick-tutorial.md
Labels: size/M

#6092 Merge release 0.30 to main
  CHANGELOG.md
Labels: size/S

#6088 Compact: Remove spam of replica label removed log
  pkg/block/fetcher.go
Labels: size/XS

#6082 Store: Don't error when no stores are matched
  CHANGELOG.md
  pkg/store/proxy.go
  pkg/store/proxy_test.go
Labels: size/S

#6058 docs: Fix must have Ruler alerts definition
  docs/components/rule.md
Labels: size/XS

#5653 Receive: Allow setting hashing algorithm per tenant in hashrings config
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/config.go
  pkg/receive/hashring.go
Labels: size/M

#6103 Mixins(Rule): Fix query for long rule evaluations
  CHANGELOG.md
  examples/dashboards/rule.json
  mixin/dashboards/rule.libsonnet
Labels: size/XS

#6110 *: fix problems with pkg/gate
  cmd/thanos/query.go
  cmd/thanos/store.go
  pkg/api/query/v1_test.go
  pkg/cacheutil/cacheutil_test.go
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/redis_client.go
  pkg/gate/gate.go
  pkg/gate/gate_test.go
  pkg/query/querier.go
  pkg/receive/limiter.go
Labels: size/L

#6106 Fix: Large number of spans in thanos traces.
  pkg/store/proxy.go
Labels: size/XS

#6098 cacheutil: upgrade rueidis to 0.0.93 to fix https://github.com/rueian/rueidis/pull/170
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/L

#6104 objstore: Update to latest
  CHANGELOG.md
  docs/storage.md
  go.mod
  go.sum
  pkg/compact/planner_test.go
Labels: size/M

#5548 Implement endpoint groups
  cmd/thanos/query.go
  docs/components/query.md
  pkg/extgrpc/client.go
  pkg/query/endpointset.go
Labels: size/M

#6113 Add changelog entry for 5548
  CHANGELOG.md
Labels: size/XS

#6074 Instrumented servers
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  docs/components/query.md
  docs/components/receive.md
  docs/components/rule.md
  docs/components/sidecar.md
  docs/components/store.md
  pkg/store/limiter.go
  pkg/store/limiter_test.go
  pkg/store/telemetry.go
Labels: size/L

#6121 Deduplicate metamonitoring queries
  CHANGELOG.md
  pkg/receive/head_series_limiter.go
Labels: size/XS

#6119 Update prometheus to 0.42.0
  go.mod
  go.sum
  internal/cortex/querier/series/series_set.go
  pkg/alert/alert.go
  pkg/block/fetcher.go
  pkg/block/index.go
  pkg/block/index_test.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compactv2/chunk_series_set.go
  pkg/compactv2/compactor.go
  pkg/compactv2/compactor_test.go
  pkg/compactv2/modifiers.go
  pkg/dedup/chunk_iter.go
  pkg/dedup/chunk_iter_test.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/query/iter.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/writer.go
  pkg/rules/manager_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb.go
  test/e2e/native_histograms_test.go
Labels: size/L

#5988 querier: Avoid global sort for dedup when possible + proposal.
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  docs/img/bottleneck-globalsort.png
  docs/img/globalsort-nonoptimized.png
  docs/img/globalsort-optimized.png
  docs/proposals-accepted/20221129-avoid-global-sort.md
  go.mod
  pkg/api/query/v1_test.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/info/infopb/rpc.pb.go
  pkg/info/infopb/rpc.proto
  pkg/query/endpointset.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go
  pkg/query/iter.go
  pkg/query/iter_test.go
  pkg/query/querier.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/query/query_test.go
  pkg/query/test_test.go
  pkg/receive/multitsdb.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/local.go
  pkg/store/prometheus_test.go
  pkg/store/proxy.go
  pkg/store/proxy_heap.go
  pkg/store/proxy_heap_test.go
  pkg/store/proxy_test.go
  pkg/store/storepb/rpc.pb.go
  pkg/store/storepb/rpc.proto
  pkg/store/storepb/testutil/client.go
  test/e2e/query_frontend_test.go
Labels: size/XXL

#6114 Implement distributed query mode
  cmd/thanos/query.go
  pkg/query/endpointset.go
  pkg/query/remote_engine.go
  pkg/query/remote_engine_test.go
  test/e2e/distributed_query_test.go
  test/e2e/e2ethanos/services.go
Labels: size/L

#6128 Potential fix for e2e flake from 6114
  test/e2e/distributed_query_test.go
  test/e2e/e2ethanos/services.go
Labels: size/S

#6131 Store: Use Histograms for bucket metrics
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/M

#6136 Adding Open Systems as an adopter
  website/data/adopters.yml
  website/static/logos/open-systems.png
Labels: size/XS

#6134 docs: Fix the missed parenthesis after defer func
  docs/contributing/coding-style-guide.md
Labels: size/M

#6139 Fix error handling in gRPC query API
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/querypb/responses.go
Labels: size/L

#6127 sidecar: implement without replica labels capability
  cmd/thanos/sidecar.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/proxy_heap_test.go
Labels: size/M

#6143 receive: implement without replica labels capability
  cmd/thanos/receive.go
  pkg/store/tsdb.go
Labels: size/S

#6056 Support native histograms in store-gateway
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/storepb/testutil/series.go
  pkg/testutil/e2eutil/prometheus.go
  test/e2e/store_gateway_test.go
Labels: size/L

#6142 Document hashring algorithms
  docs/components/receive.md
Labels: size/S

#6148 Query-frontend: add traceID to `slow query detected` log line
  CHANGELOG.md
  internal/cortex/frontend/transport/handler.go
Labels: size/S

#6145 Update mixin for new histograms
  CHANGELOG.md
  examples/dashboards/store.json
  mixin/dashboards/store.libsonnet
Labels: size/M

#6137 Repair non-empty XOR chunks during 1h downsampling
  CHANGELOG.md
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
Labels: size/M

#6125 Fix sorted queries do not produce sorted results for shardable queries
  CHANGELOG.md
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/query_range_test.go
  internal/cortex/querier/queryrange/results_cache.go
  internal/cortex/querier/queryrange/split_by_interval.go
  internal/cortex/querier/queryrange/split_by_interval_test.go
  pkg/queryfrontend/downsampled.go
  pkg/queryfrontend/labels_codec.go
  pkg/queryfrontend/labels_codec_test.go
  pkg/queryfrontend/queryinstant_codec.go
  pkg/queryfrontend/queryinstant_codec_test.go
  pkg/queryfrontend/shard_query.go
  pkg/queryfrontend/split_by_interval.go
Labels: size/L

#6153 Add remoteUser (from http basic auth) and remoteAddr to Thanos slow query logs
  CHANGELOG.md
  internal/cortex/frontend/transport/handler.go
Labels: size/XS

#6161 Announce 0.31-rc release
  CHANGELOG.md
  VERSION
Labels: size/S

#6160 Prepare 0.31.0
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
Labels: size/M

#6162 Fix release version
  VERSION
Labels: size/XS

#6169 store: fix --no-cache-index-header flag
  cmd/thanos/store.go
  docs/components/store.md
Labels: size/XS

#6171 Store: fix error handling on limits
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
Labels: size/M
