Repository thanos-io/thanos, pull requests merged in 2023-11, with the labels that each got.

#6863 Bump go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp from 0.42.0 to 0.44.0
  go.mod
  go.sum
Labels: size/M

#6864 Bump go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp from 0.42.0 to 0.44.0
  go.mod
  go.sum
Labels: size/M

#6869 Doc: mdox ignore 503 link
  .mdox.validate.yaml
Labels: size/XS

#6868 Changed fetcher and syncer Histogram metric to Observer
  pkg/block/fetcher.go
  pkg/compact/compact.go
Labels: size/XS

#6870 extkingpin: fix Content/Rewrite race
  pkg/extkingpin/path_content_reloader.go
Labels: size/S

#6873 Makefile: enable race detection for unit tests
  Makefile
Labels: size/XS

#6874 Store: fix returned labels on external label conflict when skipping chunks
  CHANGELOG.md
  pkg/store/acceptance_test.go
  pkg/store/prometheus.go
Labels: size/M

#6892 Bump CircleCI unittest timeout
  .circleci/config.yml
Labels: size/XS

#6896 e2e: fix compactor test
  test/e2e/compact_test.go
Labels: size/S

#6891 Objstore: Bump Objstore for Azure Workload Identity support
  CHANGELOG.md
  docs/storage.md
  go.mod
  go.sum
Labels: size/M

#6886 sidecar: Allow customizing the shipper metadata file name
  cmd/thanos/config.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  docs/components/rule.md
  docs/components/sidecar.md
  pkg/receive/multitsdb.go
  pkg/shipper/shipper.go
  pkg/shipper/shipper_e2e_test.go
  pkg/shipper/shipper_test.go
Labels: size/M

#6901 Doc: remove dead Banzai Cloud link
  docs/getting-started.md
Labels: size/XS

#6903 tutorial to integrate thanos with cilium
  docs/img/Thanos_with_cilium.png
  docs/img/hubble_network_flow.png
  docs/quick-tutorial.md
  tutorials/thanos-with-cilium/README.md
Labels: size/M

#6875 CI: increase e2e test parallelism
  .github/workflows/go.yaml
Labels: size/XS

#6893 compact: hook nodownsamplemarkfilter into filters chain
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  pkg/compact/downsample/downsample.go
  test/e2e/compact_test.go
Labels: size/L

#6909 e2e/compact: fix assertion values
  test/e2e/compact_test.go
Labels: size/XS

#6908 Expose asyncOperationProcessor
  pkg/cacheutil/async_op.go
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/redis_client.go
Labels: size/M

#6907 Removed the gitpod from the contribution.md
  CONTRIBUTING.md
Labels: size/XS

#6910 .circleci: cache tool deps
  .circleci/config.yml
Labels: size/S

#6911 MAINTAINERS.md: add myself as maintainer
  MAINTAINERS.md
Labels: size/M

#6912 blog: Introducing ThanosCon in Paris KubeCon EU 2024
  docs/blog/2023-20-11-thanoscon.md
  docs/blog/img/ThanosCon.png
Labels: size/M

#6915 Update 2023-20-11-thanoscon.md (typo)
  docs/blog/2023-20-11-thanoscon.md
Labels: size/XS

#6917 Added info about ThanosCon to website and Readme.
  README.md
  website/layouts/index.html
Labels: size/XS

#6906 Update compactor backlog doc for checking halt
  docs/operating/compactor-backlog.md
Labels: size/S

#6920 Update LabyrinthLabs logo
  website/static/logos/lablabs.png
Labels: size/XS

#6919 Objstore: Bump Objstore for Azure Workload Identity support (#6891)
  CHANGELOG.md
  docs/storage.md
  go.mod
  go.sum
Labels: size/M

#6453 Support reload using signal
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/sidecar.go
  docs/components/sidecar.md
  go.mod
  go.sum
  pkg/reloader/reloader.go
  pkg/reloader/tracker.go
Labels: size/L

#6925 Support float histogram in store gateway
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/storepb/prompb/types.pb.go
  pkg/store/storepb/prompb/types.proto
  pkg/store/storepb/testutil/series.go
  pkg/testutil/e2eutil/prometheus.go
  test/e2e/store_gateway_test.go
Labels: size/L

#6933 Add TrueLayer to the list of adopters
  website/data/adopters.yml
  website/static/logos/truelayer.png
Labels: size/XS

#6902 Fetcher: Add a BlockIDsFetcher Interface to BaseFetcher
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
  cmd/thanos/store.go
  cmd/thanos/tools_bucket.go
  pkg/block/fetcher.go
  pkg/block/fetcher_test.go
  pkg/compact/clean_test.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/retention_test.go
  pkg/replicate/replicator.go
  pkg/store/acceptance_test.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
Labels: size/L

#6927 Update hugo file
  website/hugo.yaml
Labels: size/XS

#6937 cherrypick docker hash bumps
  .busybox-versions
Labels: size/S

#6938 Fix hotstar logo
  website/static/logos/hotstar.jpg
Labels: size/XS
