Repository thanos-io/thanos, pull requests merged in 2023-10, with the labels that each got.

#6761 Store: Don't hardcode series batch size
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/XS

#6758 Fix index fetch latency metric timer
  pkg/store/cache/memcached.go
Labels: size/XS

#6760 added tls config in downstream query
  CHANGELOG.md
  cmd/thanos/query_frontend.go
  pkg/queryfrontend/config.go
Labels: size/S

#6764 Add improbable.io to mdox ignore
  .mdox.validate.yaml
  CHANGELOG.md
Labels: size/XS

#6763 Cut patch release `v0.32.4`
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
Labels: size/S

#6767 Merge release 0.32.4 to main
  CHANGELOG.md
Labels: size/S

#6656 Enabled Navbar to automatically close on navigation
  pkg/ui/react-app/src/thanos/Navbar.tsx
Labels: component: UIs/ReactJS, size/XS

#6770 Force Tracing : checkbox in query frontend to force a trace to be collected
  pkg/ui/react-app/src/pages/graph/Panel.test.tsx
  pkg/ui/react-app/src/pages/graph/Panel.tsx
  pkg/ui/react-app/src/utils/utils.test.ts
Labels: size/S

#6690 Store: Add tenant label to exported metrics
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
  pkg/promclient/promclient.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/cache/cache.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/inmemory_test.go
  pkg/store/cache/memcached.go
  pkg/store/cache/memcached_test.go
  pkg/store/lazy_postings.go
  pkg/tenancy/tenancy.go
  test/e2e/store_gateway_test.go
Labels: feature request/improvement, component: store, size/XL

#6747 StoreGateway: Partition index-header download
  go.mod
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/parallel_bucket.go
  pkg/block/indexheader/parallel_bucket_test.go
Labels: size/L

#6765 Support filtered index cache
  CHANGELOG.md
  docs/components/store.md
  pkg/store/cache/factory.go
  pkg/store/cache/filter_cache.go
  pkg/store/cache/filter_cache_test.go
Labels: size/L

#6778 Use RWLock for value symbols cache
  pkg/block/indexheader/binary_reader.go
Labels: size/XS

#6772 *: bump prometheus and fix fallout
  CHANGELOG.md
  cmd/thanos/downsample.go
  go.mod
  go.sum
  internal/cortex/querier/series/series_set.go
  pkg/api/api.go
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/block/index.go
  pkg/block/index_test.go
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/header.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader.go
  pkg/compact/compact.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compactv2/chunk_series_set.go
  pkg/compactv2/compactor.go
  pkg/compactv2/compactor_test.go
  pkg/compactv2/modifiers.go
  pkg/dedup/chunk_iter_test.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/exemplars/exemplars.go
  pkg/extannotations/annotations.go
  pkg/metadata/metadata.go
  pkg/metadata/prometheus_test.go
  pkg/query/iter.go
  pkg/query/querier.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/query/remote_engine.go
  pkg/query/test_test.go
  pkg/receive/multitsdb.go
  pkg/rules/manager_test.go
  pkg/rules/queryable.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/flushable.go
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
  pkg/store/postings_codec_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb.go
  pkg/targets/prometheus_test.go
  pkg/targets/targets.go
  pkg/testutil/e2eutil/prometheus.go
  pkg/verifier/index_issue.go
  test/e2e/native_histograms_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
Labels: size/XL

#6781 Fix nil pointer and data race in parallel_bucket
  pkg/block/indexheader/parallel_bucket.go
Labels: size/S

#6779 Store Gateway: Allow skipping resorting
  pkg/store/bucket.go
Labels: size/M

#6773 Expose index cache ttl config for remote caches
  CHANGELOG.md
  docs/components/store.md
  pkg/store/cache/factory.go
  pkg/store/cache/factory_test.go
  pkg/store/cache/memcached.go
  pkg/store/cache/memcached_test.go
Labels: size/M

#6783 Bump prometheus to latest main
  go.mod
  go.sum
Labels: size/XS

#6790 test/e2e: fix same environment names
  test/e2e/tools_bucket_web_test.go
Labels: size/XS

#6786 Add dialer_timeout field to HTTP TransportConfig
  pkg/httpconfig/http.go
Labels: size/XS

#6791 api/blocks: fix race between get/set
  pkg/api/blocks/v1.go
Labels: size/S

#6787 Bucket reader: Initialize new query stats struct at each goroutine
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6792 use larger histogram bucket for result series metric
  pkg/store/bucket.go
Labels: size/XS

#6793 api/query: create engines once
  pkg/api/query/v1.go
Labels: size/M

#6795 store/proxy: fix label values span race
  pkg/store/proxy.go
Labels: size/S

#6801 compact: return metas copy from syncer
  pkg/compact/compact.go
Labels: size/XS

#6802 receive: fix head series limiter trigger from settings
  CHANGELOG.md
  pkg/receive/limiter.go
Labels: size/S

#6807 preallocate loaded series map size
  pkg/store/bucket.go
Labels: size/XS

#6817 Fix matchersToPostingGroups vals variable shadow bug
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/S

#6816 Store: fix prometheus store label values for matches on external labels
  CHANGELOG.md
  pkg/store/acceptance_test.go
  pkg/store/prometheus.go
Labels: size/S

#6806 Optimize inmemory index cache WithLabelValues call
  pkg/store/cache/inmemory.go
Labels: size/S

#6810 Add default keepalive to EndpointGroupGRPCOpts
  pkg/extgrpc/client.go
Labels: size/XS

#6820 Cut patch release `v0.32.5`
  .bingo/Variables.mk
  .bingo/bingo.mod
  .bingo/bingo.sum
  .bingo/goimports.mod
  .bingo/goimports.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/shfmt.mod
  .bingo/shfmt.sum
  .bingo/variables.env
  .busybox-versions
  .circleci/config.yml
  .devcontainer/Dockerfile
  .github/workflows/codeql-analysis.yml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .github/workflows/mixin.yaml
  .go-version
  .promu.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile.multi-stage
  VERSION
  go.mod
  go.sum
  pkg/receive/limiter.go
  pkg/store/acceptance_test.go
  pkg/store/prometheus.go
Labels: size/L

#6822 Merge release `v0.32.5` to main
  CHANGELOG.md
Labels: size/S

#6823 go.mod: update promql-engine
  go.mod
  go.sum
Labels: size/XS

#6825 receive/handler: fix label names/values race
  pkg/receive/handler.go
Labels: size/M

#6828 Fix devcontainer image
  .devcontainer/Dockerfile
Labels: size/XS

#6827 Block: Expose fetcher and syncer metrics to be provided by depending projects
  pkg/block/fetcher.go
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
Labels: size/L

#6826 receive: fix limits reloading race
  cmd/thanos/receive.go
  pkg/receive/handler.go
  pkg/receive/limiter.go
Labels: size/S

#6831 query: fix hints race
  pkg/query/querier.go
Labels: size/XS

#6832 Adding Grupo Olx as user
  website/data/adopters.yml
  website/static/logos/grupo-olx.png
Labels: size/XS

#6794 Query: Add tenant label to exported metrics
  CHANGELOG.md
  cmd/thanos/query.go
  pkg/api/query/v1.go
  pkg/extprom/http/instrument_tenant_server.go
  pkg/receive/handler.go
  pkg/store/telemetry.go
  test/e2e/query_test.go
Labels: size/L

#6819 Nit: allocate slice capacity correctly during intersection
  go.mod
  go.sum
  pkg/store/bucket.go
Labels: size/M

#6834 Fix: Removes Deprecated ioutil
  CHANGELOG.md
  internal/cortex/frontend/transport/handler.go
  internal/cortex/querier/queryrange/marshaling_test.go
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/query_range_test.go
  internal/cortex/querier/queryrange/roundtrip.go
  internal/cortex/querier/queryrange/roundtrip_test.go
  internal/cortex/querier/queryrange/split_by_interval_test.go
Labels: size/M

#6809 Vertically shard queries by le if no histogram_quantile function
  pkg/querysharding/analysis.go
  pkg/querysharding/analyzer.go
  pkg/querysharding/analyzer_test.go
Labels: size/S

#6838 Enable race detector for e2e tests
  Dockerfile.e2e-tests
  Makefile
  docs/contributing/how-to-change-go-version.md
  test/e2e/compact_test.go
Labels: size/S

#6595 Query Frontend: forward tenant information downstream
  cmd/thanos/query_frontend.go
  docs/components/query-frontend.md
  pkg/queryfrontend/config.go
  pkg/queryfrontend/roundtrip.go
  pkg/tenancy/tenancy.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_frontend_test.go
Labels: feature request/improvement, component: query-frontend, size/L

#6835 Expose common structs/types for index cache
  pkg/store/cache/cache.go
  pkg/store/cache/cache_test.go
  pkg/store/cache/factory.go
  pkg/store/cache/factory_test.go
  pkg/store/cache/filter_cache.go
  pkg/store/cache/filter_cache_test.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/inmemory_test.go
  pkg/store/cache/memcached.go
  pkg/store/cache/memcached_test.go
Labels: size/XL

#6829 Added the fix for npm installation in react-app-lint-fix
  Makefile
Labels: size/XS

#6846 CHANGELOG: mark v0.33 as in progress
  CHANGELOG.md
  VERSION
  docs/release-process.md
Labels: size/M

#6841 Cut 0.33.0-rc.0
  CHANGELOG.md
  VERSION
  docs/release-process.md
Labels: size/M

#6680 Create aligned blocks when flushing TSDBs
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/L

#6848 queryfrontend: fix race condition in unit test
  pkg/queryfrontend/roundtrip_test.go
Labels: size/S

#6849 Move to `e2eobs.Observable` API to make profiling tests easier
  .gitignore
  examples/interactive/interactive_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/query_test.go
  test/e2e/rule_test.go
  test/e2e/store_gateway_test.go
  test/e2e/tracing_test.go
Labels: size/L

#6850 Move block list on logs to the end
  pkg/compact/compact.go
Labels: size/XS

#6853 extkingpin: fix race in test
  pkg/extkingpin/path_content_reloader_test.go
Labels: size/XS

#6852 query: fix selectStore hints race
  pkg/query/query_test.go
Labels: size/XS

#6847 Improve index header metrics
  CHANGELOG.md
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader.go
  pkg/block/indexheader/lazy_binary_reader_test.go
  pkg/block/indexheader/reader_pool.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#6859 *: remove unnecessary label sorts
  pkg/promclient/promclient.go
  pkg/store/bucket.go
  pkg/store/labelpb/label.go
Labels: size/XS

#6855 extprom: fix tg_gauge With* race
  pkg/extprom/tx_gauge.go
Labels: size/XS

#6854 testutil/prometheus: fix start/stop race
  pkg/metadata/prometheus_test.go
  pkg/promclient/promclient_e2e_test.go
  pkg/rules/prometheus_test.go
  pkg/shipper/shipper_e2e_test.go
  pkg/store/acceptance_test.go
  pkg/store/prometheus_test.go
  pkg/targets/prometheus_test.go
  pkg/testutil/e2eutil/prometheus.go
Labels: size/L
