Repository thanos-io/thanos, pull requests merged in 2024-05, with the labels that each got.

#7301 fix reader getting wrong posting offsets when querying multiple values
  CHANGELOG.md
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/header_test.go
  pkg/store/lazy_postings.go
Labels: size/L

#7318 compact: recover from panics
  pkg/compact/compact.go
Labels: size/S

#7320 Cut release `v0.35.0`
  CHANGELOG.md
  VERSION
Labels: size/XS

#7322 Merge release 0.35 to main
  CHANGELOG.md
Labels: size/S

#7323 Sidecar: wait for prometheus on startup
  CHANGELOG.md
  cmd/thanos/sidecar.go
Labels: size/L

#7333 e2e/compact: add repro for issue #6775
  test/e2e/compact_test.go
  test/e2e/e2ethanos/services.go
Labels: size/L

#7332 Emit tracing span for remote queries
  pkg/query/remote_engine.go
Labels: size/M

#7331 Query: Fixing extended functions in distributed querier
  pkg/api/query/v1.go
  pkg/cacheutil/memcached_client_test.go
  pkg/extpromql/parser.go
  pkg/store/bucket_test.go
  pkg/tenancy/tenancy.go
  pkg/tenancy/tenancy_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#7330 level change
  internal/cortex/chunk/cache/redis_cache.go
Labels: size/XS

#7326 Query: fix exemplar proxying for receivers with multiple tenants
  CHANGELOG.md
  pkg/exemplars/proxy.go
  pkg/exemplars/proxy_test.go
  pkg/store/proxy.go
Labels: size/M

#7335 Dependency - Update minio-go to v7.0.70
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/S

#7338 *: Promql changes to add support to extended functions throught Thanos
  Makefile
  cmd/thanos/rule.go
  internal/cortex/querier/queryrange/results_cache.go
  internal/cortex/querier/queryrange/split_by_interval.go
  internal/cortex/querier/queryrange/split_by_interval_test.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1.go
  pkg/block/metadata/meta.go
  pkg/exemplars/multitsdb.go
  pkg/exemplars/proxy.go
  pkg/exemplars/proxy_test.go
  pkg/extpromql/parser.go
  pkg/extpromql/parser_test.go
  pkg/query/remote_engine_test.go
  pkg/query/test_test.go
  pkg/queryfrontend/queryinstant_codec.go
  pkg/queryfrontend/queryrange_codec.go
  pkg/querysharding/analyzer.go
  pkg/rules/rules.go
  pkg/store/storepb/custom_test.go
  pkg/tenancy/tenancy.go
Labels: size/L

#7299 Align tenant pruning according to wall clock
  cmd/thanos/receive.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/S

#7334 compact/planner: fix issue 6775
  CHANGELOG.md
  cmd/thanos/compact.go
  pkg/block/metadata/markers.go
  pkg/compact/planner.go
  test/e2e/compact_test.go
Labels: size/M

#7367 Allow configurable request logger in Store Gateway
  CHANGELOG.md
  cmd/thanos/store.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
Labels: size/L

#6948 Receive: fix serverAsClient.Series goroutines leak
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/proxy_merge.go
  pkg/store/storepb/inprocess.go
Labels: size/L

#7372 misc: convert more code to build with stringlabels
  pkg/api/blocks/v1_test.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader_test.go
  pkg/block/indexheader/reader_pool_test.go
  pkg/dedup/iter_test.go
  pkg/promclient/promclient_e2e_test.go
  pkg/store/tsdb_selector.go
  pkg/store/tsdb_selector_test.go
Labels: size/L

#7375 Docs: update my affiliation
  MAINTAINERS.md
Labels: size/XS

#7336 Add timeout to endpointset metric collector
  pkg/query/endpointset.go
Labels: size/S

#7382 *: Ensure objstore flag values are masked & disable debug/pprof/cmdline
  CHANGELOG.md
  cmd/thanos/main.go
  pkg/server/http/http.go
Labels: size/XS

#7384 Add request ID to client grpc spans
  cmd/thanos/query_frontend.go
  pkg/api/api.go
  pkg/query/remote_engine.go
  pkg/tracing/http.go
Labels: size/M

#7371 Proxy: unify store filtering
  pkg/store/acceptance_test.go
  pkg/store/proxy.go
  pkg/store/proxy_merge.go
  pkg/store/proxy_test.go
Labels: size/L

#7361 Query: adding stats to the remote engine
  CHANGELOG.md
  go.mod
  go.sum
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/querypb/query.pb.go
  pkg/api/query/querypb/query.proto
  pkg/api/query/querypb/responses.go
  pkg/query/remote_engine.go
Labels: size/L

#7388 Appending warn to changelog about breaking change
  CHANGELOG.md
Labels: size/XS

#7385 Query: set keepalive for store grpc client
  pkg/extgrpc/client.go
Labels: size/XS

#6651 Update go-grpc-middleware to v2.0.0
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  go.mod
  go.sum
  pkg/extgrpc/client.go
  pkg/logging/grpc.go
  pkg/logging/options.go
  pkg/query/remote_engine.go
  pkg/server/grpc/grpc.go
  pkg/store/proxy_merge.go
  pkg/tracing/grpc.go
  pkg/tracing/interceptors/client.go
  pkg/tracing/interceptors/reporter.go
  pkg/tracing/interceptors/server.go
  pkg/tracing/tracing_middleware/client.go
  pkg/tracing/tracing_middleware/doc.go
  pkg/tracing/tracing_middleware/grpctesting/gogotestpb/fields.pb.go
  pkg/tracing/tracing_middleware/grpctesting/gogotestpb/fields.proto
  pkg/tracing/tracing_middleware/grpctesting/interceptor_suite.go
  pkg/tracing/tracing_middleware/grpctesting/mutex_readerwriter.go
  pkg/tracing/tracing_middleware/grpctesting/pingservice.go
  pkg/tracing/tracing_middleware/grpctesting/testpb/test.manual_extractfields.pb.go
  pkg/tracing/tracing_middleware/grpctesting/testpb/test.manual_validator.pb.go
  pkg/tracing/tracing_middleware/grpctesting/testpb/test.pb.go
  pkg/tracing/tracing_middleware/grpctesting/testpb/test.proto
  pkg/tracing/tracing_middleware/interceptors_test.go
  pkg/tracing/tracing_middleware/metadata.go
  pkg/tracing/tracing_middleware/options.go
  pkg/tracing/tracing_middleware/server.go
  pkg/tracing/util/metautils/doc.go
  pkg/tracing/util/metautils/nicemd.go
  pkg/tracing/util/metautils/nicemd_test.go
  pkg/tracing/util/metautils/single_key.go
Labels: size/XXL

#7392 Query: dont pass query hints to avoid triggering pushdown
  CHANGELOG.md
  pkg/query/querier.go
  pkg/store/prometheus.go
Labels: size/M

#7393 *: Using native histograms for grpc middleware metrics
  CHANGELOG.md
  go.mod
  go.sum
  pkg/extgrpc/client.go
  pkg/server/grpc/grpc.go
Labels: size/M

#7394 Cut patch release `v0.35.1`
  CHANGELOG.md
  VERSION
  cmd/thanos/main.go
  cmd/thanos/sidecar.go
  pkg/compact/compact.go
  pkg/query/querier.go
  pkg/receive/handler.go
  pkg/server/http/http.go
  pkg/store/bucket.go
  pkg/store/prometheus.go
  pkg/store/proxy_merge.go
  pkg/store/storepb/inprocess.go
Labels: size/L

#7398 Merge release 0.35.1 to main
  CHANGELOG.md
Labels: size/S
