Repository thanos-io/thanos, pull requests merged in 2024-04, with the labels that each got.

#7246 Remove write method from Compactor interface
  pkg/compact/compact.go
Labels: size/XS

#7247 Change shipper to not overwrite all external labels
  pkg/shipper/shipper.go
  pkg/shipper/shipper_test.go
Labels: size/M

#7250 fix(changelog): fix GOMEMLIMIT pull request reference
  CHANGELOG.md
Labels: size/XS

#7251 Update kakkoyun's affiliation
  MAINTAINERS.md
Labels: size/XS

#7254 Added Shield in adopters
  website/data/adopters.yml
  website/static/logos/shield.png
Labels: size/XS

#7231 Tracing: added missing sampler types
  CHANGELOG.md
  pkg/tracing/otlp/otlp.go
Labels: size/S

#7258 fix query_test when --race enabled
  pkg/query/query_test.go
Labels: size/M

#7263 go.mod: bump promql-engine
  go.mod
  go.sum
Labels: size/XS

#7245 Fix 7244 error targets page
  CHANGELOG.md
  pkg/targets/targetspb/rpc.pb.go
  pkg/targets/targetspb/rpc.proto
Labels: size/XS

#7225 Don't halt compaction due to overlapping sources when vertical compac…
  pkg/compact/compact.go
Labels: size/XS

#7266 Clarify documentation around selecor.relabel-config option
  cmd/thanos/query.go
  docs/components/compact.md
  docs/components/query.md
  docs/components/store.md
  docs/components/tools.md
  docs/sharding.md
  pkg/extkingpin/flags.go
Labels: size/L

#7261 query: forward query plan in the remote query request
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/querypb/plan.go
  pkg/api/query/querypb/query.pb.go
  pkg/api/query/querypb/query.proto
  pkg/api/query/v1.go
  pkg/query/remote_engine.go
  pkg/query/remote_engine_test.go
Labels: size/L

#7256 receive/handler: implement tenant label splitting
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/writer.go
  test/e2e/e2ethanos/services.go
  test/e2e/receive_test.go
  test/e2e/store_gateway_test.go
Labels: size/L

#7271 query: fixing dedup iterator when working on mixed sample types
  CHANGELOG.md
  pkg/compact/downsample/downsample_test.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/testutil/testiters/iterators.go
Labels: size/L

#7143 change the reflect package to an unsafe package
  pkg/store/cache/inmemory.go
Labels: size/XS

#7267 Receive: fix issue-7248 with parallel receive_forward
  CHANGELOG.md
  cmd/thanos/receive.go
  pkg/pool/worker_pool.go
  pkg/pool/worker_pool_test.go
  pkg/receive/handler.go
Labels: size/L

#7268 Fix incorrect comments
  pkg/extkingpin/flags.go
Labels: size/XS

#7281 [CHORE] adding user agent
  CHANGELOG.md
  pkg/logging/http.go
Labels: size/S

#7283 Compact: Replace group with resolution in downsample metrics
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
Labels: size/M

#7219 Receive: stop relying on grpc server config to set grpc client secure/skipVerify
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/S

#7289 Show warnings in query frontend
  CHANGELOG.md
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/queryrange.pb.go
  internal/cortex/querier/queryrange/queryrange.proto
  internal/cortex/querier/queryrange/results_cache.go
  internal/cortex/querier/queryrange/results_cache_test.go
Labels: size/S

#7298 Optimize empty posting check in lazy posting
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
Labels: size/S

#7297 *: mark as unqueryable if status is not_ready/not_healthy
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  pkg/info/info.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
Labels: size/M

#7303 [CHORE] considering X-Forwarded-For on HTTP Logging
  CHANGELOG.md
  pkg/logging/http.go
Labels: size/XS

#7305 Query|Receiver: Do not log full request on ProxyStore by default
  CHANGELOG.md
  pkg/store/proxy.go
Labels: size/XS

#7306 *: Updating hashicorp LRU cache to v2
  go.mod
  go.sum
  pkg/cache/inmemory.go
  pkg/querysharding/analyzer.go
  pkg/store/cache/inmemory.go
  pkg/store/cache/inmemory_test.go
Labels: size/M

#7308 Store: batch tsdb infos
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/L

#7309 Proxy: acceptance tests for relabel filter
  pkg/store/acceptance_test.go
  pkg/store/proxy.go
Labels: size/M

#7310 Stores: respect replica labels in LabelValues and LabelNames
  pkg/query/querier.go
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/prometheus.go
  pkg/store/proxy.go
  pkg/store/storepb/rpc.pb.go
  pkg/store/storepb/rpc.proto
  pkg/store/tsdb.go
Labels: size/L

#7312 CHANGELOG: Mark 0.35 as in progress
  CHANGELOG.md
  VERSION
Labels: size/S

#7314 Cut release candidate v0.35.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/S

#7107 web:added Trademark URL
  website/layouts/index.html
Labels: size/XS

#7317 Allow specifying OTLP resource attributes for traces
  CHANGELOG.md
  docs/tracing.md
  pkg/tracing/otlp/config_yaml.go
  pkg/tracing/otlp/otlp.go
  pkg/tracing/otlp/otlp_test.go
Labels: size/M
