Repository thanos-io/thanos, pull requests merged in 2024-02, with the labels that each got.

#7112 receive/handler: fix locking twice
  pkg/receive/handler.go
  pkg/receive/handler_test.go
Labels: size/M

#7123 rule: default to alertmanager v2 api
  CHANGELOG.md
  pkg/alert/config.go
  pkg/alert/config_test.go
Labels: size/S

#7100 Receive: dont rely on slice labels
  pkg/receive/config.go
  pkg/receive/handler_test.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
  pkg/receive/receive_test.go
Labels: size/L

#7129 docs: fix link
  docs/getting-started.md
Labels: size/XS

#7132 docs: update helm installation instruction
  CHANGELOG.md
  tutorials/kubernetes-helm/README.md
Labels: size/L

#7133 Fixing log line for remote engine in debug mode
  pkg/query/remote_engine.go
Labels: size/XS

#7137 Adding new method on BucketedBytes to expose used memory
  pkg/pool/pool.go
Labels: size/XS

#7141 Adding InfraCloud as Enterprise support partner
  website/layouts/support/list.html
  website/static/infracloud.svg
Labels: size/S

#7131 Cut patch release 0.34.1
  CHANGELOG.md
  VERSION
  docs/getting-started.md
  go.mod
  go.sum
Labels: size/XL

#6880 cache: attach object storage hash to iter key
  pkg/cache/caching_bucket_config.go
  pkg/store/cache/cachekey/cachekey.go
  pkg/store/cache/cachekey/cachekey_test.go
  pkg/store/cache/caching_bucket.go
  pkg/store/cache/caching_bucket_factory.go
  pkg/store/cache/caching_bucket_test.go
Labels: size/M

#7150 Merge release 0.34.1 to main
  CHANGELOG.md
Labels: size/S

#7105 rule: Add support for extended promql functions
  CHANGELOG.md
  cmd/thanos/rule.go
Labels: size/S

#7161 Extended func support - doc update
  CHANGELOG.md
  docs/components/rule.md
Labels: size/XS

#7151 Copy labels from remote instant queries
  pkg/query/remote_engine.go
Labels: size/S

#7160 e2e/query_frontend: add tests for explain/analyze
  test/e2e/query_frontend_test.go
Labels: size/M

#7134 Allow using different listing strategies
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/main_test.go
  cmd/thanos/store.go
  cmd/thanos/tools_bucket.go
  docs/components/compact.md
  docs/components/store.md
  pkg/block/fetcher.go
  pkg/block/fetcher_test.go
  pkg/compact/clean_test.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/retention_test.go
  pkg/replicate/replicator.go
  pkg/store/acceptance_test.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
Labels: size/L

#7010 cache: implement the circuit breaker pattern for asynchronous set operations in the cache client
  CHANGELOG.md
  docs/components/query-frontend.md
  docs/components/store.md
  pkg/cacheutil/cacheutil.go
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/memcached_client_test.go
  pkg/cacheutil/redis_client.go
  pkg/cacheutil/redis_client_test.go
Labels: size/L

#7163 queryfrontend: fix analysis after API changes
  go.mod
  go.sum
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/query_range_test.go
  internal/cortex/querier/queryrange/queryrange.pb.go
  internal/cortex/querier/queryrange/queryrange.proto
  internal/cortex/querier/queryrange/results_cache.go
  internal/cortex/querier/queryrange/results_cache_test.go
  pkg/queryfrontend/queryinstant_codec.go
  pkg/queryfrontend/queryinstant_codec_test.go
  pkg/queryfrontend/queryrange_codec.go
  pkg/queryfrontend/request.go
  test/e2e/query_frontend_test.go
Labels: size/L
