Repository thanos-io/thanos, pull requests merged in 2024-12, with the labels that each got.

#7941 [Receive] Fix race condition when adding multiple new tenants at once
  CHANGELOG.md
  docs/sharding.md
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
  pkg/receive/receive_test.go
Labels: size/L

#7953 Update promql-engine for subquery fix
  go.mod
  go.sum
Labels: size/XS

#7954 Sidecar: Ensure limit param is positive for compatibility with older Prometheus
  pkg/promclient/promclient.go
Labels: size/S

#7959 Merge release 0.37.1 to main
  CHANGELOG.md
Labels: size/S

#7962 Fix potential deadlock in hedging request
  pkg/exthttp/hedging.go
Labels: size/XS

#7961 Mark posting group lazy if it has a lot of keys
  CHANGELOG.md
  cmd/thanos/store.go
  docs/components/store.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
Labels: size/L

#7970 sidecar: fix limit mintime
  CHANGELOG.md
  cmd/thanos/sidecar.go
Labels: size/XS

#7979 store gateway: fix merge fetched postings with lazy postings
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
Labels: size/L

#7980 Cut patch release `v0.37.2`
  CHANGELOG.md
  VERSION
  cmd/thanos/sidecar.go
  pkg/exthttp/hedging.go
Labels: size/S

#7982 Merge release 0.37.2 back to main
  CHANGELOG.md
Labels: size/S

#8000 api: bump promql engine and fix fallout
  CHANGELOG.md
  cmd/thanos/query.go
  go.mod
  go.sum
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
Labels: size/L

#8003 query: distributed engine - allow querying overlapping intervals (commit signed)
  Makefile
  cmd/thanos/query.go
  pkg/query/remote_engine.go
  pkg/receive/writer_errors.go
  test/e2e/distributed_query_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#8005 Fixing E2E tests using headless Chrome
  .github/workflows/go.yaml
  test/e2e/query_test.go
Labels: size/M

#8004 .github: run e2e tests on newer ubuntu
  .github/workflows/go.yaml
  test/e2e/query_test.go
Labels: size/M

#8021 *: replace `golang.org/x/exp` with standard library
  go.mod
  internal/cortex/util/validation/notifications_limit_flag.go
  pkg/receive/expandedpostingscache/cache_test.go
  pkg/receive/handler.go
  pkg/receive/hashring.go
  pkg/receive/multitsdb.go
  pkg/rules/rules_test.go
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/cache/filter_cache.go
  pkg/store/flushable.go
  pkg/store/lazy_postings.go
  pkg/store/tsdb_selector.go
Labels: size/L

#8018 *: replace `cespare/xxhash` with `cespare/xxhash/v2`
  go.mod
  go.sum
  internal/cortex/chunk/cache/memcached_client_selector.go
  pkg/cacheutil/memcached_server_selector.go
  pkg/receive/expandedpostingscache/cache.go
  pkg/receive/hashring.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/prometheus_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb_test.go
Labels: size/M

#8016 QFE: Fix @ modifier not being applied correctly on subqueries
  CHANGELOG.md
  internal/cortex/querier/queryrange/split_by_interval.go
  internal/cortex/querier/queryrange/split_by_interval_test.go
Labels: size/S

#8031 Bump devcontainer Dockerfile base image from go1.22 to go1.23
  .devcontainer/Dockerfile
Labels: size/XS
