Repository thanos-io/thanos, pull requests merged in 2024-09, with the labels that each got.

#7679 query: queryable is not respecting limits
  CHANGELOG.md
  cmd/thanos/query.go
Labels: size/S

#7642 website: max-height for version-picker dropdown
  website/static/main.css
Labels: size/XS

#7694 test: Fix flaky receive/multitsdb test
  pkg/receive/multitsdb_test.go
Labels: size/XS

#7643 Receive: fix `thanos_receive_write_{timeseries,samples}` stats
  CHANGELOG.md
  docs/components/receive.md
  pkg/receive/handler.go
Labels: size/M

#7652 store: Implement metadata API limit in stores
  CHANGELOG.md
  pkg/promclient/promclient.go
  pkg/query/querier.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/prometheus.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/rpc.pb.go
  pkg/store/storepb/rpc.proto
  pkg/store/tsdb.go
  test/e2e/exemplars_api_test.go
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
Labels: component: store, size/XL

#7698 Fix CodeQL checks on main
  .github/workflows/codeql-analysis.yml
Labels: size/XS

#7658 Store: Fix panic too smaller buffer
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/XS

#7700 receive/multitsdb: remove double lock
  pkg/receive/multitsdb.go
Labels: size/XS

#7704 *: get rid of store info api
  CHANGELOG.md
  cmd/thanos/query.go
  pkg/component/component.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset_test.go
  pkg/query/query_test.go
  pkg/receive/multitsdb.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/local.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/inprocess.go
  pkg/store/storepb/inprocess_test.go
  pkg/store/storepb/rpc.pb.go
  pkg/store/storepb/rpc.proto
  pkg/store/tsdb.go
  pkg/store/tsdb_test.go
  pkg/tenancy/tenancy_test.go
  test/e2e/query_test.go
Labels: size/XXL

#7707 receive: mark too-far-in-future flag as non-experimental
  .mdox.validate.yaml
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/S

#7722 query: add partition labels flag
  cmd/thanos/query.go
  docs/components/query.md
  pkg/query/remote_engine.go
  pkg/query/remote_engine_test.go
Labels: size/M

#7706 util: Pass limit to strutil.MergeSlices
  pkg/store/bucket.go
  pkg/store/proxy.go
  pkg/strutil/merge.go
  pkg/strutil/merge_test.go
Labels: size/L

#7683 store: added a log error print when proxy limit are violated
  pkg/store/proxy.go
Labels: size/XS

#7741 dep: bump objstore
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/M

#7742 *: enable gRPC pooling
  cmd/thanos/main.go
  scripts/genproto.sh
Labels: size/M

#7745 *: build with stringlabels
  .promu.yml
  Makefile
  cmd/thanos/main_test.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1_test.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/compact_test.go
  pkg/compact/downsample/downsample_test.go
  pkg/extprom/tx_gauge_test.go
  pkg/query/endpointset_test.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/query/query_test.go
  pkg/query/test_test.go
  pkg/query/testdata/promql/prometheus/aggregators.test
  pkg/query/testdata/promql/prometheus/collision.test
  pkg/query/testdata/promql/prometheus/functions.test
  pkg/query/testdata/promql/prometheus/histograms.test
  pkg/query/testdata/promql/prometheus/literals.test
  pkg/query/testdata/promql/prometheus/operators.test
  pkg/query/testdata/promql/prometheus/selectors.test
  pkg/query/testdata/promql/prometheus/staleness.test
  pkg/query/testdata/promql/prometheus/subquery.test
  pkg/query/testdata/promql/thanos/aggregators.test
  pkg/rules/rulespb/custom_test.go
  pkg/tenancy/tenancy_test.go
Labels: size/XXL

#7748 Blog article submission: Life of a Sample in Thanos Part I
  docs/blog/2023-11-20-life-of-a-sample-part-1.md
  docs/blog/img/life-of-a-sample/close-integration.png
  docs/blog/img/life-of-a-sample/ingestor-router.png
  docs/blog/img/life-of-a-sample/receive-limits.png
  docs/blog/img/life-of-a-sample/remote-write.png
  docs/blog/img/life-of-a-sample/router-and-ingestor.png
  docs/blog/img/life-of-a-sample/series-terminology.png
  docs/blog/img/life-of-a-sample/storage-terminology.png
Labels: size/L

#7756 Generalize the bucketed bytes pool
  pkg/pool/pool.go
  pkg/pool/pool_test.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/postings_codec.go
Labels: size/L

#7761 Fix blog article img rendering for Life of a sample Part I
  docs/blog/2023-11-20-life-of-a-sample-part-1.md
Labels: size/M

#7762 store: don't create intermediate labels
  pkg/store/labelpb/custom.go
  pkg/store/proxy_merge.go
Labels: size/M

#7765 Adding @pedro-stanaka as Triager
  MAINTAINERS.md
Labels: size/XS

#7766 store: compare labels directly
  pkg/store/proxy_merge.go
Labels: size/XS

#7767 query/store: memoize PromLabels() call
  pkg/query/iter.go
  pkg/store/storepb/custom.go
Labels: size/M

#7768 Website: remove ThanosCon banner
  website/layouts/index.html
Labels: size/XS

#7772 e2e/e2ethanos: fix avalanche version
  test/e2e/e2ethanos/services.go
Labels: size/XS

#7773 Update affiliation of kakkoyun
  MAINTAINERS.md
Labels: size/XS

#7771 store: add chunk pooling
  go.mod
  go.sum
  pkg/query/querier.go
  pkg/store/local.go
  pkg/store/storepb/types.pb.go
  pkg/store/storepb/types.proto
  pkg/store/storepb/types_vtproto.pb.go
  scripts/genproto.sh
Labels: size/M

#7764 chore: add GOMEMLIMIT in runtimeinfo api
  pkg/api/api.go
Labels: size/XS

#7782 receive: memoize exemplar/TSDB clients
  docs/sharding.md
  pkg/receive/multitsdb.go
Labels: size/M

#7763 ruler: use native histograms for client metrics
  CHANGELOG.md
  pkg/extprom/http/instrument_client.go
Labels: size/S

#7785 Add XNET to Adopters
  website/data/adopters.yml
  website/static/logos/XNET.png
Labels: size/XS
