Repository thanos-io/thanos, pull requests merged in 2024-10, with the labels that each got.

#7783 store: reuse chunks map
  pkg/query/querier_test.go
  pkg/store/proxy_merge.go
  pkg/store/proxy_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/storepb/testutil/store_series_client.go
Labels: size/M

#7793 Disable dedup proxy in multi-tsdb
  cmd/thanos/receive.go
  pkg/store/proxy.go
  pkg/store/proxy_merge.go
Labels: size/S

#7787 receive/multitsdb: add cuckoo filter on metric names
  cmd/thanos/receive.go
  docs/components/receive.md
  go.mod
  go.sum
  pkg/filter/cuckoo.go
  pkg/filter/filter.go
  pkg/query/endpointset.go
  pkg/receive/multitsdb.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/testutil/client.go
  pkg/store/tsdb.go
Labels: size/L

#7678 Query: Skip formatting strings if debug logging is disabled
  pkg/store/proxy.go
  pkg/store/proxy_test.go
Labels: size/M

#7796 Use iterators for in-process Series calls
  .bingo/.gitignore
  .bingo/README.md
  .bingo/Variables.mk
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  .github/workflows/go.yaml
  Dockerfile.e2e-tests
  go.mod
  go.sum
  pkg/block/block.go
  pkg/query/endpointset.go
  pkg/queryfrontend/labels_codec.go
  pkg/queryfrontend/queryinstant_codec.go
  pkg/receive/multitsdb.go
  pkg/store/limiter_test.go
  pkg/store/recover_test.go
  pkg/store/storepb/custom.go
  pkg/store/storepb/inprocess.go
  pkg/store/storepb/inprocess_test.go
  pkg/tracing/util/metautils/nicemd_test.go
Labels: size/XL

#7813 *: bump deps + enable compaction randomization
  CHANGELOG.md
  go.mod
  go.sum
  pkg/block/metadata/markers_test.go
  pkg/compact/downsample/downsample_test.go
  pkg/query/querier_test.go
  pkg/receive/multitsdb.go
  pkg/store/prometheus.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
Labels: size/L

#7816 api: use jsoniter
  pkg/api/api.go
  pkg/api/api_test.go
Labels: size/M

#7815 Disable chunk trimming in Receivers
  docs/components/receive.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/components/tools.md
  docs/storage.md
  pkg/store/storepb/rpc.pb.go
  pkg/store/storepb/rpc.proto
  pkg/store/tsdb.go
  pkg/store/tsdb_test.go
Labels: size/S

#7821 Fix coroutine leak
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/proxy_merge.go
  pkg/store/proxy_merge_test.go
  pkg/store/proxy_test.go
  pkg/store/storepb/inprocess.go
  pkg/store/storepb/testutil/store_series_client.go
Labels: size/L

#7833 Update go to 1.23 in the CI
  .bingo/Variables.mk
  .bingo/alertmanager.mod
  .bingo/alertmanager.sum
  .bingo/minio.mod
  .bingo/minio.sum
  .bingo/prometheus.mod
  .bingo/prometheus.sum
  .bingo/variables.env
  .circleci/config.yml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .go-version
  .promu.yml
  Dockerfile.e2e-tests
  Dockerfile.multi-stage
  Makefile
  pkg/rules/manager_test.go
  pkg/rules/prometheus_test.go
  pkg/rules/rules_test.go
  pkg/testutil/e2eutil/prometheus.go
Labels: size/XXL

#7834 docs: add Thanos store memcached deployment note
  docs/components/store.md
Labels: size/XS

#7835 rule: add concurrent evals functionality
  cmd/thanos/rule.go
  docs/components/rule.md
Labels: size/M

#7814 store: label_values: fetch less postings
  CHANGELOG.md
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
Labels: size/M

#7838 Optimize validateLabels
  pkg/receive/capnproto_writer.go
  pkg/receive/capnproto_writer_bench_test.go
Labels: size/M

#7843 QFE: only log slow query, if it is a query endpoint
  CHANGELOG.md
  internal/cortex/frontend/transport/handler.go
  internal/cortex/frontend/transport/handler_test.go
Labels: size/L

#7852 QFE: pass "stats" parameter to queriers, fix prometheus stats merging
  CHANGELOG.md
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/query_range_test.go
  internal/cortex/querier/queryrange/queryrange.pb.go
  internal/cortex/querier/queryrange/queryrange.proto
  pkg/queryfrontend/queryinstant_codec.go
  pkg/queryfrontend/queryinstant_codec_test.go
  pkg/queryfrontend/queryrange_codec.go
  pkg/queryfrontend/queryrange_codec_test.go
Labels: size/M

#7857 receive/multitsdb: defer unlock properly
  pkg/receive/multitsdb.go
Labels: size/XS

#7859 Add Logz.io to adopters
  website/data/adopters.yml
  website/static/logos/logzio.png
Labels: size/XS

#7855 query,store: Improve replica flag handling
  CHANGELOG.md
  cmd/thanos/compact.go
  cmd/thanos/query.go
  docs/components/compact.md
  docs/components/query.md
  pkg/strutil/labels.go
  pkg/strutil/labels_test.go
Labels: size/L

#7861 Cut down test times
  .circleci/config.yml
  .github/workflows/go.yaml
  go.mod
  go.sum
  pkg/compact/clean_test.go
  pkg/compact/compact_test.go
  pkg/compact/planner_test.go
  pkg/compact/retention_test.go
  pkg/query/endpointset_test.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/query/remote_engine_test.go
  pkg/receive/capnproto_server_test.go
  pkg/receive/config_test.go
  pkg/receive/handler_test.go
  pkg/receive/hashring_test.go
  pkg/receive/limiter_config_test.go
  pkg/receive/limiter_test.go
  pkg/receive/multitsdb_test.go
  pkg/receive/receive_test.go
  pkg/receive/request_limiter_test.go
  pkg/receive/writer_test.go
  pkg/reloader/reloader_test.go
  pkg/store/acceptance_test.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/io_test.go
  pkg/store/lazy_postings_test.go
  pkg/store/limiter_test.go
  pkg/store/postings_codec_test.go
  pkg/store/prometheus_test.go
  pkg/store/proxy_merge_test.go
  pkg/store/proxy_test.go
  pkg/store/recover_test.go
  pkg/store/tsdb_selector_test.go
  pkg/store/tsdb_test.go
Labels: size/L

#7654 allow user to specify tls version for backward compatibility
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/query.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  docs/components/query.md
  docs/components/receive.md
  docs/components/rule.md
  docs/components/sidecar.md
  docs/components/store.md
  pkg/tls/options.go
  pkg/tls/options_test.go
  test/e2e/tls_test.go
Labels: size/L
