Repository thanos-io/thanos, pull requests merged in 2024-07, with the labels that each got.

#7429 reloader: don't fail on envvar expansion errors
  .mdox.validate.yaml
  CHANGELOG.md
  pkg/reloader/reloader.go
  pkg/reloader/reloader_test.go
Labels: size/L

#7506 chore: Add nirmata to adopters
  website/data/adopters.yml
  website/static/logos/Nirmata.png
Labels: size/XS

#7509 Close endpoints after the gRPC server has terminated
  cmd/thanos/query.go
Labels: size/XS

#7515 removed mention of unused pkg
  .bingo/minio.sum
Labels: size/XS

#7511 QFE: disable double compression middleware
  CHANGELOG.md
  cmd/thanos/query_frontend.go
Labels: size/XS

#7494 Ruler: remove trailing period from SRV records returned by discovery `dnsnosrva` lookups
  CHANGELOG.md
  pkg/discovery/dns/resolver.go
Labels: size/XS

#7492 compact: Update filtered blocks list before second downsample pass
  CHANGELOG.md
  cmd/thanos/compact.go
  test/e2e/compact_test.go
Labels: size/S

#7510 Cut release candidate 0.36.0 rc.1
  CHANGELOG.md
  VERSION
  cmd/thanos/query.go
  pkg/server/grpc/grpc.go
Labels: size/S

#7559 Build with Go 1.22
  .bingo/Variables.mk
  .bingo/bingo.mod
  .bingo/bingo.sum
  .bingo/faillint.mod
  .bingo/faillint.sum
  .bingo/goimports.mod
  .bingo/goimports.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/shfmt.mod
  .bingo/shfmt.sum
  .bingo/variables.env
  .circleci/config.yml
  .devcontainer/Dockerfile
  .github/workflows/codeql-analysis.yml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .github/workflows/mixin.yaml
  .go-version
  .promu.yml
  CONTRIBUTING.md
  Dockerfile.multi-stage
  pkg/errors/errors.go
Labels: size/XL

#7552 *: Fix issue #7550 - Check correct error when opening rule files in tools
  cmd/thanos/testdata/rules-files/unreadable_valid.yaml
  cmd/thanos/tools.go
  cmd/thanos/tools_test.go
Labels: size/M

#7558 Update prometheus and promql-engine dependencies
  Dockerfile.e2e-tests
  cmd/thanos/rule.go
  go.mod
  go.sum
  internal/cortex/querier/queryrange/split_by_interval_test.go
  pkg/api/query/v1.go
  pkg/query/querier.go
  pkg/rules/queryable.go
  pkg/store/tsdb.go
  test/e2e/native_histograms_test.go
Labels: size/L

#7560 api/rules: Add filtering on rule name/group/file
  CHANGELOG.md
  pkg/api/query/v1.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/rules/rulespb/rpc.pb.go
  pkg/rules/rulespb/rpc.proto
Labels: size/L

#7568 Update Thanos PromQL Engine docs
  docs/components/query.md
Labels: size/S

#7567 Remove metalmatze from Thanos maintainers
  MAINTAINERS.md
Labels: size/XS

#7565 discovery: use thanos resolver for endpoint groups
  CHANGELOG.md
  cmd/thanos/query.go
  pkg/discovery/dns/grpc.go
  pkg/discovery/dns/provider.go
Labels: size/L

#7576 Add @harry671003 to triagers
  MAINTAINERS.md
Labels: size/S

#7578 Cut release v0.36.0
  CHANGELOG.md
  VERSION
Labels: size/XS
