Repository thanos-io/thanos, pull requests merged in 2024-11, with the labels that each got.

#7877 upgrade Prometheus to fix round function
  go.mod
  go.sum
Labels: size/S

#7854 QFE: new middleware to force query statistics collection
  CHANGELOG.md
  cmd/thanos/query_frontend.go
  docs/components/query-frontend.md
  internal/cortex/frontend/transport/handler.go
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/stats_middleware.go
  internal/cortex/querier/queryrange/stats_middleware_test.go
  internal/cortex/querier/stats/stats.go
  internal/cortex/querier/stats/stats.pb.go
  internal/cortex/querier/stats/stats.proto
  pkg/queryfrontend/roundtrip.go
  pkg/queryfrontend/roundtrip_test.go
  scripts/genproto.sh
Labels: size/L

#7832 query-frontend: Fix cache keys for dynamic split intervals
  CHANGELOG.md
  pkg/queryfrontend/cache.go
  pkg/queryfrontend/cache_test.go
  pkg/queryfrontend/request.go
  pkg/queryfrontend/roundtrip.go
  pkg/queryfrontend/split_by_interval.go
  pkg/queryfrontend/split_by_interval_test.go
  test/e2e/query_frontend_test.go
Labels: size/L

#7886 discovery: preserve results from other resolve calls
  cmd/thanos/query.go
  cmd/thanos/rule.go
  internal/cortex/chunk/cache/memcached_client.go
  pkg/cache/groupcache.go
  pkg/cacheutil/memcached_client.go
  pkg/clientconfig/http.go
  pkg/discovery/dns/grpc.go
  pkg/discovery/dns/provider.go
  pkg/discovery/dns/provider_test.go
  pkg/discovery/memcache/provider.go
  pkg/discovery/memcache/provider_test.go
Labels: size/L

#7820 Sidecar: use prometheus metrics for min timestamp
  cmd/thanos/sidecar.go
  pkg/promclient/promclient.go
  pkg/promclient/promclient_e2e_test.go
Labels: size/L

#7887 compact: add SyncMetas() timeout
  cmd/thanos/compact.go
  cmd/thanos/tools_bucket.go
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
Labels: size/M

#7885 Fix bug in Bucket Series
  CHANGELOG.md
  pkg/store/bucket.go
Labels: size/XS

#7860 store: support hedged requests
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/store.go
  cmd/thanos/tools_bucket.go
  docs/components/store.md
  go.mod
  go.sum
  pkg/exthttp/hedging.go
  pkg/replicate/replicator.go
  test/e2e/compact_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/L

#7909 receive/capnp: remove close
  pkg/receive/capnp_server.go
Labels: size/XS

#7904 store, query: remote engine bug
  pkg/query/remote_engine.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  test/e2e/query_test.go
Labels: size/L

#7911 Skip TestDistributedEngineWithDisjointTSDBs
  test/e2e/query_test.go
Labels: size/XS

#7915 Close block series client at the end to not reuse chunk buf
  pkg/store/bucket.go
Labels: size/XS

#7924 Update objstore and promql-engine to latest
  cmd/thanos/main_test.go
  go.mod
  go.sum
  pkg/api/query/v1.go
  pkg/block/fetcher.go
  pkg/cache/groupcache.go
Labels: size/M

#7926 docs: Add link to ignore
  .mdox.validate.yaml
Labels: size/XS

#7928 docs: Fix formatting again
  docs/components/receive.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/components/tools.md
  docs/storage.md
Labels: size/XS

#7921 Cut first release candidate for `v0.37.0`
  CHANGELOG.md
  VERSION
  website/hugo.yaml
Labels: size/M

#7936 Cut release for `v0.37.0`
  CHANGELOG.md
  VERSION
Labels: size/XS

#7937 receive/expandedpostingscache: fix race
  pkg/receive/expandedpostingscache/cache.go
  pkg/receive/expandedpostingscache/cache_test.go
  pkg/receive/multitsdb.go
Labels: size/M

#7907 receive: Allow specifying a custom gRPC service config via flag
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/S

#7674 Query-frontend: Fix connection to Redis cluster with TLS.
  CHANGELOG.md
  pkg/queryfrontend/config.go
Labels: size/S

#7942 Documentation: Remove redundant redis config
  docs/components/store.md
Labels: size/XS

#7945 Capnp: Use segment from existing message
  go.mod
  go.sum
  pkg/receive/writecapnp/client.go
  pkg/receive/writecapnp/marshal.go
Labels: size/M

#7946 Merge release 0.37 to main
  CHANGELOG.md
  website/hugo.yaml
Labels: size/S
