Repository thanos-io/thanos, pull requests merged in 2024-03, with the labels that each got.

#7177 .circleci: bump setup_docker_version version
  .circleci/config.yml
Labels: size/XS

#7179 cortex/querier: fix analysis merging
  go.mod
  go.sum
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/query_range_test.go
  pkg/queryfrontend/queryinstant_codec.go
Labels: size/L

#7180 Fix docs
  CHANGELOG.md
  docs/components/query.md
Labels: size/XS

#7181 Added platformengineers in adopters
  website/data/adopters.yml
  website/layouts/support/list.html
  website/static/logos/platformengineers.png
  website/static/platformengineers.png
Labels: size/XS

#7191 Bump google.golang.org/protobuf to v1.33.0
  go.mod
  go.sum
Labels: size/XS

#7192 rule: do not turn off if resolving fails
  cmd/thanos/rule.go
  pkg/runutil/runutil.go
Labels: size/S

#7193 change platform-engineer logo size and make 'https://thanos.io/support/' responsive
  website/layouts/support/list.html
  website/static/platformengineers.png
Labels: size/M

#7164 compact: properly treat native histogram deduplication in chunk series merger
  pkg/dedup/chunk_iter.go
  pkg/dedup/chunk_iter_test.go
Labels: size/L

#7202 [FEAT] Adding blog post
  docs/getting-started.md
Labels: size/XS

#7207 storepb: make ServerAsClient channels unbuffered
  pkg/api/query/v1_test.go
  pkg/query/querier_test.go
  pkg/query/query_test.go
  pkg/receive/multitsdb.go
  pkg/store/acceptance_test.go
  pkg/store/storepb/inprocess.go
  pkg/store/storepb/inprocess_test.go
Labels: size/M

#7200 Add support for TSDB selector in querier
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/receive.go
  docs/components/query.md
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/tsdb_selector.go
  pkg/store/tsdb_selector_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#7194 downsample: retry objstore related errors
  CHANGELOG.md
  cmd/thanos/downsample.go
  pkg/compact/compact.go
Labels: size/S

#7215 Update thanos-io/promql-engine
  cmd/thanos/rule.go
  go.mod
  go.sum
  pkg/query/remote_engine.go
  pkg/query/remote_engine_test.go
Labels: size/M

#7214 Expose NewPromSeriesSet function
  pkg/query/iter.go
  pkg/query/querier.go
Labels: size/M

#7223 [CHORE] adding auto GOMEMLIMIT flag
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/main.go
  docs/components/compact.md
  docs/components/query-frontend.md
  docs/components/query.md
  docs/components/receive.md
  docs/components/rule.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/components/tools.md
  go.mod
  go.sum
Labels: size/XL

#7228 Bump objstore package version to latest main
  docs/components/receive.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/components/tools.md
  docs/storage.md
  go.mod
  go.sum
Labels: size/L

#7224 Query-frontend: fix missing redis username config
  CHANGELOG.md
  internal/cortex/chunk/cache/redis_client.go
  pkg/queryfrontend/config.go
Labels: size/XS

#7220 Fix lazy expanded postings cache and bug of non equal matcher
  CHANGELOG.md
  go.mod
  go.sum
  pkg/store/bucket.go
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
  pkg/testutil/e2eutil/prometheus.go
  pkg/testutil/e2eutil/rand.go
  test/e2e/store_gateway_test.go
Labels: size/L

#7232 Bump Prometheus to include new label regex optimization
  cmd/thanos/main.go
  go.mod
  go.sum
  pkg/api/query/grpc.go
  pkg/api/query/grpc_test.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/block/index_test.go
  pkg/block/testdata/out_of_order_chunks/index
  pkg/compact/compact_e2e_test.go
  pkg/query/remote_engine.go
  pkg/query/testdata/promql/prometheus/functions.test
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/lazy_postings_test.go
  pkg/store/opts.go
  pkg/store/opts_test.go
  pkg/store/storepb/custom_test.go
  pkg/testutil/e2eutil/prometheus.go
  test/e2e/query_frontend_test.go
Labels: size/XL

#7241 docs: Update receive limits configuration for routing receivers dual
  docs/components/receive.md
Labels: size/XS

#7243 docs: add thanoscon 2024 talks
  docs/getting-started.md
Labels: size/S
