Repository thanos-io/thanos, pull requests merged in 2024-06, with the labels that each got.

#7363 Query-frontend: Set value of remote_user field in Slow Query Logs from HTTP header
  CHANGELOG.md
  cmd/thanos/query_frontend.go
  docs/components/query-frontend.md
  internal/cortex/frontend/transport/handler.go
Labels: size/S

#7412 Added Conclusion Xforce in adopters
  website/data/adopters.yml
  website/static/logos/conclusion-xforce.png
Labels: size/XS

#7411 receive: remove serverAsClient usage
  pkg/receive/multitsdb.go
  pkg/store/flushable.go
  pkg/store/tsdb.go
Labels: size/L

#7409 Split promql span into query create and exec spans
  pkg/api/query/grpc.go
  pkg/api/query/v1.go
Labels: size/L

#7403 Sidecar: fix startup sequence
  CHANGELOG.md
  cmd/thanos/sidecar.go
Labels: size/L

#7416 [Chore] Update Prometheus
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/compact/downsample/aggr.go
  pkg/compact/downsample/aggr_test.go
  pkg/compactv2/chunk_series_set.go
  pkg/query/endpointset.go
  pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go
  pkg/receive/handler.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/prometheus_test.go
  pkg/store/tsdb_test.go
  pkg/tracing/tracing_middleware/grpctesting/interceptor_suite.go
  test/e2e/query_test.go
  test/e2e/tls_test.go
Labels: size/XXL

#7423 Changelog - update the changelog entry position
  CHANGELOG.md
Labels: size/XS

#7420 Use cached label sets
  pkg/query/endpointset.go
Labels: size/XS

#7428 Updates devcontainer dockerfile
  .devcontainer/Dockerfile
Labels: size/XS

#7421 Fixup dependabot config
  .github/dependabot.yml
Labels: size/S

#7414 Enhanced bytes limiter with data type param
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/store/limiter.go
Labels: size/L

#7457 Use the default dependabot labeling
  .github/dependabot.yml
Labels: size/XS

#7462 chore: bump objstore package version
  go.mod
  go.sum
Labels: size/S

#7465 Upgrade Prometheus common and Prometheus to latest main
  go.mod
  go.sum
  pkg/clientconfig/http.go
  pkg/compact/compact.go
  pkg/store/acceptance_test.go
  pkg/store/bucket_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb_test.go
  pkg/testutil/e2eutil/prometheus.go
Labels: size/L

#7469 Bump objstore version
  go.mod
  go.sum
Labels: size/XS

#7471 Put query stats logging under s.debugLogging
  pkg/store/bucket.go
Labels: size/S

#7468 Store: add failing test to show an issue with tsdb selector
  pkg/store/acceptance_test.go
Labels: size/L

#7476 Store: fix merge race
  pkg/store/acceptance_test.go
Labels: size/XS

#7478 chore: fix docs check
  .mdox.validate.yaml
  docs/storage.md
Labels: size/XS

#7477 chore: update objstore
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/S

#7484 Proxy: fix response set panic
  CHANGELOG.md
  pkg/store/proxy_merge.go
Labels: size/S

#7486 CHANGELOG: Mark 0.36 as in progress
  CHANGELOG.md
  VERSION
Labels: size/S

#7490 Cut release candidate v0.36.0-rc.0
  CHANGELOG.md
  VERSION
  docs/release-process.md
Labels: size/XS

#7493 *: fix server grpc histograms
  CHANGELOG.md
  pkg/server/grpc/grpc.go
Labels: size/XS
