Repository thanos-io/thanos, pull requests merged in 2024-08, with the labels that each got.

#7581 Add Synology to adopters
  website/data/adopters.yml
  website/static/logos/synology.png
Labels: size/XS

#7589 docs: add saswatas youtube introduction to blog
  docs/getting-started.md
Labels: size/XS

#7588 Merge release 0.36 to main
  CHANGELOG.md
  docs/release-process.md
Labels: size/S

#7608 website: Update amadeus logo to latest
  website/static/logos/amadeus.png
Labels: size/XS

#7592 Only increment ruler warning eval metric for non PromQL warnings
  CHANGELOG.md
  cmd/thanos/rule.go
  cmd/thanos/rule_test.go
Labels: size/M

#7609 API: Add limit param in metadata APIs
  CHANGELOG.md
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
Labels: size/L

#7614 *: fix debug log on exit
  cmd/thanos/main.go
Labels: size/XS

#7619 Update CHANGELOG.md after #7614
  CHANGELOG.md
Labels: size/XS

#7621 Fix GetActiveAndPartialBlockIDs panic
  pkg/block/fetcher.go
Labels: size/XS

#7620 Fix failing e2e test
  test/e2e/receive_test.go
Labels: size/S

#7618 Proxy: Query goroutine leak when `store.response-timeout` is set
  pkg/store/proxy_merge.go
Labels: size/XS

#7634 pkg/clientconfig: fix TLS configs with only CA
  CHANGELOG.md
  cmd/thanos/rule.go
  pkg/clientconfig/http.go
  pkg/clientconfig/http_test.go
  pkg/clientconfig/testdata/invalid.pem
  pkg/clientconfig/testdata/self-signed-client.crt
  pkg/clientconfig/testdata/self-signed-client.key
  pkg/clientconfig/testdata/tls-ca-chain.pem
Labels: size/L

#7635 Fix changelog on main after 0.36 release
  CHANGELOG.md
Labels: size/M

#7639 Merge release 0.36.1 to main
  CHANGELOG.md
Labels: size/S

#7622 Check context cancellation every 128 iterations
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/cache/inmemory.go
  pkg/store/lazy_postings.go
Labels: size/M

#7641 golangci-lint: Update deprecated linter configurations
  .errcheck_excludes.txt
  .golangci.yml
Labels: size/M

#7645 Add support for stringlabels in Thanos Query
  .github/workflows/go.yaml
  cmd/thanos/config.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/tools_bucket.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
Labels: size/M

#7646 Fix spelling issues discovered by codespell
  .github/workflows/go.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  cmd/thanos/rule_test.go
  docs/components/store.md
  docs/contributing/mentorship.md
  docs/operating/cross-cluster-tls-communication.md
  docs/proposals-accepted/202012-deletions-object-storage.md
  docs/proposals-accepted/202108-more-granular-query-performance-metrics.md
  docs/proposals-accepted/202205-vertical-query-sharding.md
  docs/proposals-accepted/202206-active-series-limiting-hashring.md
  docs/proposals-done/201812-thanos-remote-receive.md
  docs/proposals-done/201909-thanos-sharding.md
  docs/proposals-done/202001-thanos-query-health-handling.md
  docs/proposals-done/202203-grpc-query-api.md
  docs/proposals-done/202301-distributed-query-execution.md
  docs/storage.md
  examples/alerts/alerts.md
  examples/alerts/alerts.yaml
  examples/dashboards/receive.json
  mixin/README.md
  mixin/alerts/query.libsonnet
  mixin/dashboards/receive.libsonnet
  mixin/runbook.md
  test/e2e/e2ethanos/services.go
  tutorials/interactive-example/README.md
Labels: size/M

#7649 fix: fixed the token-permission and pinned dependencies issue
  .github/workflows/codeql-analysis.yml
  .github/workflows/container-version.yaml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .github/workflows/mixin.yaml
  .github/workflows/react.yml
Labels: size/M

#7653 Added Scaling Prometheus with Thanos Blog from CloudRaft
  docs/getting-started.md
Labels: size/XS

#7661 Store: Fix LabelNames and LabelValues when using non-equal matchers
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#7610 Memcached: Skip reqs if the item is larger than the max allowed size
  internal/cortex/chunk/cache/memcached_client.go
Labels: size/S

#7655 codespell: check `pkg` folder
  .github/workflows/go.yaml
  pkg/block/indexheader/reader_pool.go
  pkg/cacheutil/memcached_client.go
  pkg/compact/compact.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compact/planner.go
  pkg/errors/errors.go
  pkg/prober/grpc.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
  pkg/query/querier_test.go
  pkg/query/testdata/promql/prometheus/functions.test
  pkg/receive/handler.go
  pkg/receive/writer.go
  pkg/rules/manager.go
  pkg/rules/proxy_test.go
  pkg/runutil/runutil.go
  pkg/store/bucket_test.go
  pkg/store/cache/tracing_index_cache.go
  pkg/store/io.go
  pkg/store/limiter_test.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/prompb/samples.go
  pkg/store/tsdb_test.go
  pkg/tracing/util/metautils/nicemd_test.go
  pkg/verifier/duplicated_compaction.go
Labels: size/L

#7669 receive: change quorum calculation for RF=2
  docs/components/receive.md
  pkg/receive/handler.go
Labels: size/S
