Repository thanos-io/thanos, pull requests merged in 2024-01, with the labels that each got.

#7023 added tasrie it services as support partner
  website/layouts/support/list.html
  website/static/tasrie-it-services.png
Labels: size/XS

#6887 Query Frontend: Add tenant label to metrics
  CHANGELOG.md
  cmd/thanos/query_frontend.go
  test/e2e/query_frontend_test.go
Labels: size/L

#7017 Query Frontend splitting metrics check is flaky
  test/e2e/query_frontend_test.go
Labels: size/L

#7026 resolved issue #7024
  docs/components/rule.md
Labels: size/XS

#7028 QueryFrontend|Query: Create new arg to enable extended functions
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/query_frontend.go
  docs/components/query-frontend.md
  docs/components/query.md
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/queryfrontend/config.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#7018 store: add chunksize tests to acceptance tests
  pkg/store/acceptance_test.go
  pkg/store/prometheus_test.go
  pkg/store/tsdb_test.go
Labels: size/L

#7030 receive: respect forward timeout in http handler buckets
  pkg/receive/handler.go
Labels: size/S

#7031 receive: do not leak grpc connections
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/hashring.go
Labels: size/L

#7032 docs: fix multi-tenancy link
  docs/operating/multi-tenancy.md
Labels: size/XS

#7037 removing todo comment from query docs
  docs/components/query.md
Labels: size/XS

#6756 Query: add optional tenancy enforcement
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
  go.mod
  go.sum
  pkg/api/query/v1.go
  pkg/tenancy/tenancy.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#7038 Tests: unique docker env name for tenant tests
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
Labels: size/XS

#6539 changed store api's --sync-block-duration to 15m
  CHANGELOG.md
  cmd/thanos/store.go
  docs/components/store.md
Labels: component: store, size/XS

#7039 Fix docs
  CHANGELOG.md
  docs/components/store.md
Labels: size/XS

#7053 Revert "receive: upload compacted blocks if OOO enabled (#6974)"
  cmd/thanos/receive.go
  pkg/receive/handler_test.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
  pkg/receive/receive_test.go
  pkg/receive/writer_test.go
Labels: size/S

#6884 [CHORE] adding thanos upload-blocks command
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
  pkg/block/metadata/meta.go
  pkg/component/component.go
  pkg/promclient/promclient.go
Labels: size/L

#7057 docs: fix docs error
  docs/components/tools.md
Labels: size/XS

#7059 cmd: make bucket upload command take lset from flags
  cmd/thanos/config.go
  cmd/thanos/rule.go
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
Labels: size/L

#7055 CHANGELOG: mark 0.34 as in progress
  CHANGELOG.md
  VERSION
Labels: size/S

#7061 VERSION: cut release 0.34.0-rc.0
  VERSION
Labels: size/XS

#7047 go.mod: update Prometheus & promql-engine version
  go.mod
  go.sum
  pkg/api/query/v1_test.go
Labels: size/M

#7043 Make RetryError and HaltError able to be fetched for root cause
  pkg/compact/compact.go
  pkg/errutil/multierror.go
  pkg/errutil/multierror_test.go
Labels: size/M

#7065 receive: disable overlapping compaction
  go.mod
  go.sum
  pkg/receive/multitsdb.go
Labels: size/S

#6898 Receive: refactor handler for improved readability and organization
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/server/http/middleware/request_id.go
Labels: difficulty: hard, size/XL

#7078 Upgrade grpc to 1.57.2
  go.mod
  go.sum
Labels: size/XL

#7084 Store: acceptance test for proxy store
  pkg/store/acceptance_test.go
  pkg/store/proxy.go
Labels: size/M

#7083 Fix lazy postings with zero length
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/lazy_postings.go
Labels: size/M

#7082 Store: fix label values edge case
  CHANGELOG.md
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/prometheus.go
  pkg/store/tsdb.go
Labels: size/M

#7086 VERSION: cut release 0.34.0-rc.1
  CHANGELOG.md
  VERSION
  pkg/store/acceptance_test.go
  pkg/store/bucket.go
  pkg/store/prometheus.go
  pkg/store/tsdb.go
Labels: size/M

#7087 Receive: race condition in handler Close() when stopped early
  CHANGELOG.md
  pkg/receive/handler.go
  pkg/receive/handler_test.go
Labels: size/M

#7045 receive: use async remote writing
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/handler.go
  pkg/receive/handler_test.go
Labels: size/L

#7095 CHANGELOG: cut release 0.34
  CHANGELOG.md
  VERSION
  docs/release-process.md
  website/hugo.yaml
Labels: size/XS

#7098 Stores: convert tests to not rely on slice labels
  pkg/store/acceptance_test.go
  pkg/store/bucket_test.go
  pkg/store/proxy_heap_test.go
  pkg/store/proxy_test.go
  pkg/store/tsdb_test.go
Labels: size/M

#7014 all: get rid of query pushdown to simplify query path
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
  pkg/api/query/grpc.go
  pkg/api/query/querypb/query.pb.go
  pkg/api/query/querypb/query.proto
  pkg/api/query/v1.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/dedup/pushdown_iter.go
  pkg/query/querier.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/query/query_test.go
  pkg/query/test_test.go
  pkg/store/prometheus.go
  pkg/store/prometheus_test.go
  pkg/store/proxy_heap_test.go
  pkg/store/storepb/custom.go
  test/e2e/native_histograms_test.go
  test/e2e/query_test.go
Labels: size/XL

#7099 Store: dont rely on slice labels continued
  go.mod
  go.sum
  pkg/store/bucket.go
  pkg/store/labelpb/label.go
  pkg/store/labelpb/label_test.go
  pkg/store/proxy_heap.go
  pkg/store/tsdb.go
Labels: size/L

#7096 Update prometheus/prometheus
  cmd/thanos/query.go
  go.mod
  go.sum
  internal/cortex/querier/series/series_set.go
  pkg/clientconfig/http.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compactv2/chunk_series_set.go
  pkg/compactv2/modifiers.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/query/iter.go
  pkg/query/querier_test.go
Labels: size/L
