Repository thanos-io/thanos, pull requests merged in 2025-09, with the labels that each got.

#8456 docs: clarify Compactor wording in compact.md
  .mdox.validate.yaml
  CHANGELOG.md
  MAINTAINERS.md
  docs/components/compact.md
  docs/components/receive.md
  docs/components/sidecar.md
  docs/components/store.md
  docs/components/tools.md
  docs/getting-started.md
  docs/internals/buffers-guide.md
  docs/storage.md
Labels: size/L

#8466 scripts/genproto: add missing dir
  internal/cortex/cortexpb/cortex.pb.go
  scripts/genproto.sh
Labels: size/XS

#8482 chore: fix comment typo
  pkg/info/info.go
Labels: size/XS

#8499 fix: support UTF-8 label names for label values API
  CHANGELOG.md
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
Labels: size/S
