Repository thanos-io/thanos, pull requests merged in 2025-07, with the labels that each got.

#8349 qfe: defer properly
  cmd/thanos/query_frontend.go
Labels: size/M

#8352 Merge release-0.39 to main
  CHANGELOG.md
Labels: size/XS

#8287 query: make grpc service config for endpoint groups configurable
  cmd/thanos/endpointset.go
  pkg/extgrpc/client.go
Labels: size/S

#8364 *: use prometheus consts
  pkg/api/query/v1.go
  pkg/queryfrontend/labels_codec.go
Labels: size/S

#8370 fix: query announced endpoints match relabel-config
  CHANGELOG.md
  cmd/thanos/query.go
  pkg/api/query/v1.go
  pkg/store/acceptance_test.go
  pkg/store/proxy.go
Labels: size/L

#8375 query: add custom values to prompb methods
  pkg/store/storepb/prompb/samples.go
  pkg/store/storepb/prompb/types.pb.go
  pkg/store/storepb/prompb/types.proto
Labels: size/S

#8379 Release 0.39.2
  CHANGELOG.md
  VERSION
  pkg/api/query/v1.go
  pkg/store/storepb/prompb/samples.go
  pkg/store/storepb/prompb/types.pb.go
  pkg/store/storepb/prompb/types.proto
Labels: size/S

#8389 block: bust cache if modified timestamp differs
  cmd/thanos/main_test.go
  examples/interactive/interactive_test.go
  go.mod
  go.sum
  pkg/block/block_test.go
  pkg/block/fetcher.go
  pkg/block/fetcher_test.go
  scripts/cfggen/main.go
  test/e2e/compact_test.go
  test/e2e/distributed_query_test.go
  test/e2e/info_api_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/L

#8398 block: output cleanup err
  pkg/block/block.go
Labels: size/XS

#8334 Query: wait for initial endpoint discovery before becoming ready
  CHANGELOG.md
  cmd/thanos/endpointset.go
  cmd/thanos/query.go
  pkg/discovery/dns/grpc.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
Labels: size/L

#8402 query/receive: trim labelsets from String()
  pkg/query/endpointset.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
Labels: size/S

#8404 Don't start sidecar if REMOTE_WRITE_ENABLED env var present
  scripts/quickstart.sh
Labels: size/M
