Repository thanos-io/thanos, pull requests merged in 2025-08, with the labels that each got.

#8427 refactor: chown on COPY in Dockerfile to reduce image size
  Dockerfile
Labels: size/XS

#8437 Remove @matej-g from maintainers
  MAINTAINERS.md
  docs/components/store.md
Labels: size/XS

#8439 Update to Go 1.25
  .bingo/.gitignore
  .bingo/README.md
  .bingo/Variables.mk
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  .circleci/config.yml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .golangci.yml
  .promu.yml
  Dockerfile.e2e-tests
  cmd/thanos/query_frontend.go
  pkg/api/blocks/v1_test.go
  pkg/api/query/grpc.go
  pkg/api/query/v1_test.go
  pkg/block/fetcher_test.go
  pkg/cacheutil/async_op_test.go
  pkg/cacheutil/redis_client.go
  pkg/compact/compact.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/discovery/memcache/resolver.go
  pkg/discovery/memcache/resolver_test.go
  pkg/query/endpointset_test.go
  pkg/query/remote_engine.go
  pkg/queryfrontend/config.go
  pkg/querysharding/analyzer.go
  pkg/receive/handler.go
  pkg/receive/hashring.go
  pkg/receive/otlptranslator/helper.go
  pkg/replicate/scheme.go
  pkg/replicate/scheme_test.go
  pkg/shipper/shipper.go
  pkg/shipper/shipper_e2e_test.go
  pkg/shipper/shipper_test.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/postings.go
  pkg/store/proxy_merge.go
  pkg/testutil/e2eutil/prometheus.go
  pkg/tracing/tracing_middleware/interceptors_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/XXL

#8443 query: remove unused replica labels map in querier
  pkg/query/querier.go
Labels: size/XS

#8452 *: Restore certain omitempty tags after modernize
  internal/cortex/querier/queryrange/util.go
  pkg/api/query/v1.go
  pkg/block/metadata/meta.go
  pkg/receive/config.go
Labels: size/S
