Repository thanos-io/thanos, pull requests merged in 2025-03, with the labels that each got.

#8131 Optimize wildcard matchers for .* and .+
  CHANGELOG.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#8110 compact: implement native histogram downsampling
  cmd/thanos/main_test.go
  docs/components/compact.md
  pkg/api/blocks/v1_test.go
  pkg/block/block_test.go
  pkg/block/index_test.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader_test.go
  pkg/block/indexheader/reader_pool_test.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/downsample/aggr_test.go
  pkg/compact/downsample/downsample.go
  pkg/compact/downsample/downsample_test.go
  pkg/compact/downsample/testutils.go
  pkg/promclient/promclient_e2e_test.go
  pkg/store/bucket.go
  pkg/store/bucket_e2e_test.go
  pkg/store/bucket_test.go
  pkg/testutil/e2eutil/prometheus.go
  test/e2e/compact_test.go
  test/e2e/distributed_query_test.go
  test/e2e/query_test.go
  test/e2e/store_gateway_test.go
  test/e2e/tools_bucket_web_test.go
Labels: size/XXL

#8134 Bump common+client_golang to deal with utf-8
  cmd/thanos/rule_test.go
  go.mod
  go.sum
  pkg/receive/writer_test.go
  pkg/store/labelpb/label_zlabel_test.go
Labels: size/M

#7808 query: Support chain deduplication algorithm
  CHANGELOG.md
  cmd/thanos/query.go
  docs/components/query.md
  pkg/api/query/grpc_test.go
  pkg/api/query/v1_test.go
  pkg/dedup/iter.go
  pkg/dedup/iter_test.go
  pkg/query/querier.go
  pkg/query/querier_test.go
  pkg/query/query_bench_test.go
  pkg/query/query_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/query_test.go
Labels: size/L

#8157 test(interactve): update interactive tests to update non-supported querier store flags
  examples/interactive/interactive_test.go
Labels: size/S

#8165 e2e: use prom 3
  cmd/thanos/receive.go
  docs/components/receive.md
  test/e2e/distributed_query_test.go
  test/e2e/e2ethanos/services.go
  test/e2e/native_histograms_test.go
  test/e2e/query_frontend_test.go
  test/e2e/query_test.go
  test/e2e/receive_test.go
Labels: size/M

#8173 Changelog: mark 0.38 as in-progress
  CHANGELOG.md
  VERSION
Labels: size/S

#8175 Query: fix endpointset setup
  CHANGELOG.md
  cmd/thanos/endpointset.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/info_api_test.go
  test/e2e/metadata_api_test.go
  test/e2e/rules_api_test.go
  test/e2e/targets_api_test.go
Labels: size/M
