Repository thanos-io/thanos, pull requests merged in 2025-06, with the labels that each got.

#8284 store: Add --disable-admin-operations Flag to Store Gateway
  CHANGELOG.md
  cmd/thanos/store.go
  docs/components/store.md
Labels: size/S

#8259 shipper: allow shipper sync to skip corrupted blocks
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/receive.go
  cmd/thanos/rule.go
  cmd/thanos/sidecar.go
  cmd/thanos/tools_bucket.go
  pkg/receive/handler_test.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
  pkg/receive/receive_test.go
  pkg/receive/writer_test.go
  pkg/shipper/shipper.go
  pkg/shipper/shipper_e2e_test.go
  pkg/shipper/shipper_test.go
Labels: size/XL

#8299 Resolve GitHub Actions Failure
  docs/blog/welcome.md
  docs/components/store.md
Labels: size/XS

#8300 receive: Revert capnp to v3.0.0-alpha
  go.mod
  go.sum
Labels: size/XS

#8252 tools: fix tool bucket inspect output arg description
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
Labels: size/XS

#8306 [docs] Updating documentation around --compact flags
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/S

#8296 Query: limit LazyRetrieval memory buffer size
  CHANGELOG.md
  cmd/thanos/query.go
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/proxy.go
  pkg/store/proxy_merge.go
  pkg/store/proxy_test.go
Labels: size/L

#8320 *: add CHANGELOG, update VERSION
  CHANGELOG.md
  VERSION
Labels: size/S

#8322 e2e: Check rule group label works
  test/e2e/rule_test.go
  test/e2e/rules_api_test.go
Labels: size/S

#8330 *: release 0.39.0
  CHANGELOG.md
  VERSION
Labels: size/XS

#8331 Merge release 0.39 to main
  CHANGELOG.md
Labels: size/S

#8333 e2e: add repro for 8224
  test/e2e/receive_test.go
Labels: size/S

#8336 indexheader: fix race between lazy index header creation
  pkg/block/indexheader/reader_pool.go
  pkg/block/indexheader/reader_pool_test.go
Labels: size/M

#8338 cmd/query_frontend: use original roundtripper + close immediately
  cmd/thanos/query_frontend.go
Labels: size/XS
