Repository thanos-io/thanos, pull requests merged in 2025-04, with the labels that each got.

#8180 Changelog: cut release 0.38.0-rc.1
  CHANGELOG.md
  VERSION
  cmd/thanos/endpointset.go
  go.mod
  go.sum
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/info_api_test.go
  test/e2e/metadata_api_test.go
  test/e2e/rules_api_test.go
  test/e2e/targets_api_test.go
Labels: size/M

#8185 CHANGELOG: cut release 0.38
  CHANGELOG.md
  VERSION
Labels: size/XS

#8186 merge release 0.38.0 to main
  CHANGELOG.md
  docs/release-process.md
  website/hugo.yaml
Labels: size/S

#8190 Fix changelog markdown.
  CHANGELOG.md
Labels: size/XS

#8192 Sidecar: increase default prometheus timeout
  CHANGELOG.md
  cmd/thanos/config.go
  docs/components/sidecar.md
Labels: size/XS

#8202 receive: Unhide tsdb.enable-native-histograms flag
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/XS

#8211 Query: fix partial response for distributed instant query
  CHANGELOG.md
  pkg/api/query/grpc.go
Labels: size/XS

#8210 query.md example uses --query.tenant-default-id incorrectly
  docs/components/query.md
Labels: size/XS

#8212 Receive: Ensure forward/replication metrics are incremented in err cases
  CHANGELOG.md
  docs/components/receive.md
  pkg/receive/handler.go
Labels: size/XS

#8226 receive: remove Get() method from hashring
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
Labels: size/XS

#8225 tools: Extend bucket ls options
  CHANGELOG.md
  cmd/thanos/tools_bucket.go
  docs/components/tools.md
Labels: size/M
