Repository thanos-io/thanos, pull requests merged in 2025-02, with the labels that each got.

#8084 skip match label values for certain matchers
  pkg/store/bucket.go
Labels: size/S

#8083 Extend posting-group-max-key-series-ratio for add all posting group
  pkg/store/bucket.go
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
Labels: size/M

#7969 Add a func converting go-kit log to slog
  go.mod
  go.sum
  pkg/logging/logger.go
  pkg/logutil/logutil.go
  pkg/logutil/logutil_test.go
Labels: size/M

#8091 fix: add POST into allowed CORS methods header
  CHANGELOG.md
  pkg/api/api.go
Labels: size/XS

#8092 Fix deadlock in metadata fetcher
  pkg/block/fetcher.go
Labels: size/XS

#8088 store: lock around iterating over s.blocks
  docs/getting-started.md
  pkg/extprom/http/instrument_client.go
  pkg/query/endpointset.go
  pkg/runutil/runutil.go
  pkg/store/bucket.go
Labels: size/S

#8090 Use update-prometheus-3.0 branch
  cmd/thanos/compact.go
  cmd/thanos/downsample.go
  cmd/thanos/endpointset.go
  cmd/thanos/query.go
  cmd/thanos/rule.go
  cmd/thanos/tools_bucket.go
  go.mod
  go.sum
  internal/cortex/querier/queryrange/roundtrip_test.go
  pkg/api/query/v1.go
  pkg/api/query/v1_test.go
  pkg/block/index.go
  pkg/block/index_test.go
  pkg/block/indexheader/header_test.go
  pkg/clientconfig/http.go
  pkg/compact/compact_e2e_test.go
  pkg/compact/downsample/downsample_test.go
  pkg/compactv2/compactor.go
  pkg/compactv2/compactor_test.go
  pkg/dedup/chunk_iter_test.go
  pkg/dedup/iter_test.go
  pkg/logging/http.go
  pkg/logging/httputil.go
  pkg/query/querier_test.go
  pkg/query/query_test.go
  pkg/query/testdata/promql/prometheus/aggregators.test
  pkg/query/testdata/promql/prometheus/functions.test
  pkg/query/testdata/promql/prometheus/histograms.test
  pkg/query/testdata/promql/prometheus/operators.test
  pkg/query/testdata/promql/prometheus/staleness.test
  pkg/query/testdata/promql/prometheus/subquery.test
  pkg/receive/handler_test.go
  pkg/receive/multitsdb.go
  pkg/rules/manager_test.go
  pkg/server/http/http.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/storepb/testutil/series.go
  pkg/store/tsdb_test.go
  pkg/testutil/e2eutil/prometheus.go
Labels: size/XL

#8105 *: bump Go to 1.24
  .bingo/README.md
  .bingo/Variables.mk
  .bingo/faillint.mod
  .bingo/faillint.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  .circleci/config.yml
  .github/workflows/docs.yaml
  .github/workflows/go.yaml
  .go-version
  .golangci.yml
  Dockerfile.e2e-tests
  Dockerfile.multi-stage
  go.mod
  internal/cortex/frontend/transport/handler.go
  internal/cortex/querier/queryrange/limits.go
  internal/cortex/querier/queryrange/query_range.go
  internal/cortex/querier/queryrange/results_cache.go
  internal/cortex/querier/queryrange/roundtrip.go
  internal/cortex/querier/queryrange/util.go
Labels: size/L

#8075 Docs: Remove quote from replica label
  docs/components/compact.md
Labels: size/XS

#8113 Query: dynamic endpointgroups are allowed
  cmd/thanos/endpointset.go
Labels: size/XS

#8107 [Issue-8106] Fix tenant hashring glob with multiple tenant match patterns
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
Labels: size/L

#8120 query : add missing xincrease/xrate aggregation
  pkg/query/querier.go
Labels: size/XS

#7012 Infer max query downsample resolution from promql query
  CHANGELOG.md
  pkg/query/querier.go
  pkg/query/querier_test.go
Labels: size/L
