Repository thanos-io/thanos, pull requests merged in 2025-01, with the labels that each got.

#7353 Receiver: cache matchers for series calls
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/query/query_test.go
  pkg/receive/handler_test.go
  pkg/receive/multitsdb.go
  pkg/receive/multitsdb_test.go
  pkg/receive/receive_test.go
  pkg/receive/writer_test.go
  pkg/store/cache/matchers_cache.go
  pkg/store/cache/matchers_cache_test.go
  pkg/store/local.go
  pkg/store/prometheus.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/custom.go
  pkg/store/tsdb.go
Labels: size/XL

#8034 build(deps): bump golang.org/x/net from v0.30.0 to v0.33.0
  go.mod
  go.sum
Labels: size/XS

#8035 add pool for expanded posting slice
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/lazy_postings.go
Labels: size/M

#8032 receive: unhide tsdb.out-of-order.time-window and tsdb.out-of-order.cap-max
  cmd/thanos/receive.go
  docs/components/receive.md
Labels: size/S

#8025 optimize store gateway bytes limiter reserve with type request
  pkg/store/bucket.go
Labels: size/M

#8039 Fix matcher cache
  pkg/store/cache/matchers_cache.go
  pkg/store/cache/matchers_cache_test.go
Labels: size/M

#8026 Optimize sort keys by server in memcache client
  pkg/cacheutil/memcached_client.go
  pkg/cacheutil/memcached_client_test.go
  pkg/cacheutil/memcached_server_selector.go
Labels: size/L

#8036 Add block lifecycle callback
  pkg/store/bucket.go
  pkg/store/bucket_test.go
Labels: size/M

#8017 Fix binary reader download duration histogram
  CHANGELOG.md
  pkg/block/indexheader/binary_reader.go
  pkg/block/indexheader/header_test.go
  pkg/block/indexheader/lazy_binary_reader.go
Labels: size/M

#8045 Matcher cache/series
  CHANGELOG.md
  cmd/thanos/receive.go
  cmd/thanos/store.go
  docs/components/receive.md
  docs/components/store.md
  pkg/receive/multitsdb.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/cache/matchers_cache.go
  pkg/store/cache/matchers_cache_test.go
  pkg/store/local.go
  pkg/store/prometheus.go
  pkg/store/proxy.go
  pkg/store/proxy_test.go
  pkg/store/storepb/custom.go
  pkg/store/tsdb.go
Labels: size/L

#8050 query: fix panic when selecting non-default engine
  pkg/api/query/v1.go
Labels: size/M

#8044 pkg/cacheutil: Async op fix
  pkg/cacheutil/async_op.go
  pkg/cacheutil/async_op_test.go
Labels: size/M

#8049 make lazy posting series match ratio configurable
  cmd/thanos/store.go
  pkg/store/bucket.go
  pkg/store/bucket_test.go
  pkg/store/lazy_postings.go
  pkg/store/lazy_postings_test.go
Labels: size/M

#8046 QFE: fixing stats middleware when cache is enabled
  CHANGELOG.md
  cmd/thanos/query_frontend.go
  pkg/queryfrontend/config.go
Labels: size/S

#7996 [FEATURE] adding otlp endpoint
  cmd/thanos/receive.go
  docs/components/receive.md
  go.mod
  pkg/errutil/multierror.go
  pkg/receive/handler.go
  pkg/receive/handler_otlp.go
  pkg/receive/handler_otlp_test.go
  pkg/receive/handler_test.go
  pkg/receive/otlptranslator/context.go
  pkg/receive/otlptranslator/context_test.go
  pkg/receive/otlptranslator/helper.go
  pkg/receive/otlptranslator/helper_test.go
  pkg/receive/otlptranslator/helpers_from_stdlib.go
  pkg/receive/otlptranslator/histograms.go
  pkg/receive/otlptranslator/histograms_test.go
  pkg/receive/otlptranslator/metrics_to_prw.go
  pkg/receive/otlptranslator/metrics_to_prw_test.go
  pkg/receive/otlptranslator/normalize_name.go
  pkg/receive/otlptranslator/number_data_points.go
  pkg/receive/otlptranslator/number_data_points_test.go
  pkg/receive/otlptranslator/otlp_to_openmetrics_metadata.go
  pkg/receive/otlptranslator/testutil_test.go
  pkg/receive/otlptranslator/timeseries.go
  test/e2e/e2ethanos/services.go
  test/e2e/receive_test.go
Labels: size/XXL

#7890 query, rule: make endpoint discovery dynamically reloadable
  CHANGELOG.md
  cmd/thanos/config.go
  cmd/thanos/endpointset.go
  cmd/thanos/query.go
  cmd/thanos/rule.go
  docs/components/query.md
  pkg/discovery/dns/grpc.go
  pkg/extkingpin/flags.go
  pkg/extkingpin/path_content_reloader.go
  pkg/query/endpointset.go
  pkg/query/endpointset_test.go
  pkg/receive/handler_test.go
  pkg/receive/limiter.go
  test/e2e/e2ethanos/services.go
  test/e2e/exemplars_api_test.go
  test/e2e/metadata_api_test.go
Labels: size/XXL
