Repository thanos-io/thanos, pull requests merged in 2025-05, with the labels that each got.

#8240 reloader: disable some flaky tests
  pkg/reloader/reloader_test.go
Labels: size/XS

#8241 e2e: disable some more flaky tests
  test/e2e/tools_bucket_web_test.go
Labels: size/XS

#8243 Optimize OTLP ClientType enumerate
  pkg/tracing/otlp/config_yaml.go
  pkg/tracing/otlp/otlp.go
Labels: size/S

#8014 test(tools_test.go/Test_CheckRules_Glob): take into consideration RO current dirs while changing files permissions.
  cmd/thanos/tools_test.go
Labels: size/S

#8260 shipper: delete unused functions
  pkg/shipper/shipper.go
  pkg/shipper/shipper_e2e_test.go
  pkg/shipper/shipper_test.go
Labels: size/L

#8263 feat(promu): add darwin/arm64
  .promu.yml
Labels: size/XS

#8238 receive: implement shuffle sharding
  CHANGELOG.md
  cmd/thanos/receive.go
  docs/components/receive.md
  pkg/receive/config.go
  pkg/receive/handler.go
  pkg/receive/handler_test.go
  pkg/receive/hashring.go
  pkg/receive/hashring_test.go
Labels: size/XL

#8267 docs: fix receive page
  docs/components/receive.md
Labels: size/XS

#8262 query: fix query analyze to return appropriate results
  pkg/api/query/v1.go
Labels: size/M

#8266 fix: maintain expanded state based on current page
  CHANGELOG.md
  website/layouts/partials/_default/sidemenu.html
Labels: size/XS

#8199 query: handle query.Analyze returning nil gracefully
  CHANGELOG.md
  pkg/api/query/grpc.go
  pkg/api/query/v1.go
Labels: size/S
